# SafeGraph Foot Traffic Dataset

The purpose of this notebook is to do some EDA of the SafeGraph Foot Traffic dataset as well as create Zip Code level maps for change in foot traffic rates in San Diego.

In [1]:
# import statements 

# SAFEGRAPH DATA CLEANING 
import pyodbc
import datetime
from datetime import date
import pandas as pd
pd.options.mode.chained_assignment = None # to suppress the Setting with Copy Warning

# ZIP CODE DATA
import geopandas as gpd
import numpy as np
# import re

# FOLIUM MAPPING
import folium

### SafeGraph Data Loading + Cleaning

In [2]:
# this block takes approximately 15-30 minutes to run
# try to find a way to make this quicker

# BEGIN CODE BLOCK

hh_query = """SELECT [id]
      ,[safegraph_place_id]
      ,[location_name]
      ,[street_address]
      ,[city]
      ,[region]
      ,[postal_code]
      ,[iso_country_code]
      ,[safegraph_brand_ids]
      ,[brands]
      ,[date_range_start]
      ,[date_range_end]
      ,[raw_visit_counts]
      ,[raw_visitor_counts]
      ,[visits_by_day]
      ,[visits_by_each_hour]
      ,[poi_cbg]
      ,[visitor_country_of_origin]
      ,[distance_from_home]
      ,[median_dwell]
      ,[bucketed_dwell_times]
      ,[related_same_day_brand]
      ,[related_same_week_brand]
      ,[device_type]
  FROM [ws].[staging].[safegraph_v2]
  WHERE postal_code BETWEEN '91901' and '92199';
  """

sql_conn3 = pyodbc.connect('''DRIVER={ODBC Driver 17 for SQL Server};
                           SERVER=SQL2014A8;
                           DATABASE=ws;
                           Trusted_Connection=yes''')

hh_result = pd.read_sql(hh_query, sql_conn3)

# END CODE BLOCK

OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: An established connection was aborted by the software in your host machine.\r\n (10053) (SQLGetData); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (10053)')

In [3]:
# save the result as a copy to not mess with original df 
hh_res = hh_result.copy()
display(hh_res.head(2))
hh_res.info()

,id,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_day,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type
0,671788070,sg:1713db60c6b042d29993eecf02f5b14a,North County Rebuilders,445 N Hale Ave,Escondido,CA,92029,US,,,...,"[0,0,0,0,1,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203072,{},0,8.0,"{""<5"":0,""5-10"":1,""11-20"":0,""21-60"":0,""61-120"":...",{},{},"{""android"":0,""ios"":0}"
1,671799609,sg:56a3c1d9be38456a9e8412e06d462328,Color Vie,1542 Lancaster Point Way,San Diego,CA,92154,US,,,...,"[0,0,0,0,1,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730100141,{},0,8.0,"{""<5"":0,""5-10"":1,""11-20"":0,""21-60"":0,""61-120"":...",{},{},"{""android"":0,""ios"":0}"

In [4]:
# checks which dates are in the dataset
dates = hh_res['date_range_end'].unique()
sorted_dates = sorted(dates)
sorted_dates

[datetime.date(2019, 1, 7),
 datetime.date(2019, 1, 14),
 datetime.date(2019, 1, 21),
 datetime.date(2019, 1, 28),
 datetime.date(2019, 2, 4),
 datetime.date(2019, 2, 11),
 datetime.date(2019, 2, 18),
 datetime.date(2019, 2, 25),
 datetime.date(2019, 3, 4),
 datetime.date(2019, 3, 11),
 datetime.date(2019, 3, 18),
 datetime.date(2019, 3, 25),
 datetime.date(2019, 4, 1),
 datetime.date(2019, 4, 8),
 datetime.date(2019, 4, 15),
 datetime.date(2019, 4, 22),
 datetime.date(2019, 4, 29),
 datetime.date(2019, 5, 6),
 datetime.date(2019, 5, 13),
 datetime.date(2019, 5, 20),
 datetime.date(2019, 5, 27),
 datetime.date(2019, 6, 3),
 datetime.date(2019, 6, 10),
 datetime.date(2019, 6, 17),
 datetime.date(2019, 6, 24),
 datetime.date(2019, 7, 1),
 datetime.date(2019, 7, 8),
 datetime.date(2019, 7, 15),
 datetime.date(2019, 7, 22),
 datetime.date(2019, 7, 29),
 datetime.date(2019, 8, 5),
 datetime.date(2019, 8, 12),
 datetime.date(2019, 8, 19),
 datetime.date(2019, 8, 26),
 datetime.date(2019, 9, 2),
 datetime.date(2019, 9, 9),
 datetime.date(2019, 9, 16),
 datetime.date(2019, 9, 23),
 datetime.date(2019, 9, 30),
 datetime.date(2019, 10, 7),
 datetime.date(2019, 10, 14),
 datetime.date(2019, 10, 21),
 datetime.date(2019, 10, 28),
 datetime.date(2019, 11, 4),
 datetime.date(2019, 11, 11),
 datetime.date(2019, 11, 18),
 datetime.date(2019, 11, 25),
 datetime.date(2019, 12, 2),
 datetime.date(2019, 12, 9),
 datetime.date(2019, 12, 16),
 datetime.date(2019, 12, 23),
 datetime.date(2019, 12, 30),
 datetime.date(2020, 1, 6),
 datetime.date(2020, 1, 13),
 datetime.date(2020, 1, 27),
 datetime.date(2020, 2, 3),
 datetime.date(2020, 2, 10),
 datetime.date(2020, 2, 17),
 datetime.date(2020, 2, 24),
 datetime.date(2020, 3, 2),
 datetime.date(2020, 3, 9),
 datetime.date(2020, 3, 16),
 datetime.date(2020, 3, 23),
 datetime.date(2020, 3, 30),
 datetime.date(2020, 4, 6),
 datetime.date(2020, 4, 13),
 datetime.date(2020, 4, 20),
 datetime.date(2020, 4, 27),
 datetime.date(2020, 5, 4),
 datetime.date(2020, 5, 11),
 datetime.date(2020, 5, 18),
 datetime.date(2020, 5, 25),
 datetime.date(2020, 6, 1),
 datetime.date(2020, 6, 8),
 datetime.date(2020, 6, 15),
 datetime.date(2020, 6, 22),
 datetime.date(2020, 6, 29),
 datetime.date(2020, 7, 6),
 datetime.date(2020, 7, 13),
 datetime.date(2020, 7, 20),
 datetime.date(2020, 7, 27),
 datetime.date(2020, 8, 3),
 datetime.date(2020, 8, 10),
 datetime.date(2020, 8, 17),
 datetime.date(2020, 8, 24),
 datetime.date(2020, 8, 31),
 datetime.date(2020, 9, 7),
 datetime.date(2020, 9, 14),
 datetime.date(2020, 9, 21),
 datetime.date(2020, 9, 28),
 datetime.date(2020, 10, 5),
 datetime.date(2020, 10, 12),
 datetime.date(2020, 10, 19),
 datetime.date(2020, 10, 26),
 datetime.date(2020, 11, 2),
 datetime.date(2020, 11, 9),
 datetime.date(2020, 11, 16),
 datetime.date(2020, 11, 23),
 datetime.date(2020, 11, 30),
 datetime.date(2020, 12, 7),
 datetime.date(2020, 12, 14),
 datetime.date(2020, 12, 21),
 datetime.date(2020, 12, 28),
 datetime.date(2021, 1, 4),
 datetime.date(2021, 1, 11),
 datetime.date(2021, 1, 18),
 datetime.date(2021, 1, 25),
 datetime.date(2021, 2, 1),
 datetime.date(2021, 2, 8),
 datetime.date(2021, 2, 15),
 datetime.date(2021, 2, 22),
 datetime.date(2021, 3, 1),
 datetime.date(2021, 3, 8),
 datetime.date(2021, 3, 15),
 datetime.date(2021, 3, 22)]

In [19]:
# reads in the Zip Code geographies
sd_geo_zip = gpd.read_file('location_data/Zip_Codes.geojson')

# list of relevant zipcodes in SD (provided by Stephanie)
relevant_zip_codes = ['91901', '91902', '91910', '91911', '91913', '91914', '91915', '91916', '91917', '91932', '91935', 
                        '91941', '91942', '91945', '91950', '91977', '91978', '92003', '92007', '92008', '92009', '92010', '92011', '92014', '92019', 
                        '92020', '92021', '92024', '92025', '92026', '92027', '92028', '92029', '92036', '92037', '92040', '92054', '92056', '92057', 
                        '92058', '92059', '92061', '92064', '92065', '92067', '92069', '92070', '92071', '92075', '92078', '92081', '92082', '92083', 
                        '92084', '92086', '92091', '92093', '92096', '92101', '92102', '92103', '92104', '92105', '92106', '92107', '92108', '92109', 
                        '92110', '92111', '92113', '92114', '92115', '92116', '92117', '92118', '92119', '92120', '92121', '92122', '92123', '92124', 
                        '92126', '92127', '92128', '92129', '92130', '92131', '92139', '92154', '92173']

# checks which zip codes were deleted from the original geojson file
non_included_zips = sd_geo_zip[~sd_geo_zip.zip.isin(relevant_zip_codes)]
print("Non-included Zip Codes")
display(non_included_zips['zip'])

# updates dataset with only relevant locations
sd_geo_zip = sd_geo_zip[sd_geo_zip.zip.isin(relevant_zip_codes)]
print("Included Zip Codes")
sd_geo_zip.head(2)

,community,shape_star,shape_stle,zip,geometry
0,Alpine,4149939944.16,326045.262676,91901,"MULTIPOLYGON (((-116.74539 32.96063, -116.7408..."
1,Bonita,273909416.836,113257.374615,91902,"MULTIPOLYGON (((-116.97172 32.70838, -116.9712..."

In [21]:
# dissolve by the zip code since some zips have multiple rows
sd_geo_zip = sd_geo_zip.dissolve(by = 'zip', aggfunc = 'sum', as_index = False)
sd_geo_zip.head(2)

,zip,geometry,community,shape_star,shape_stle
0,91901,"POLYGON ((-116.74539 32.96063, -116.74085 32.9...",Alpine,4149939944.16,326045.262676
1,91902,"POLYGON ((-116.97172 32.70838, -116.97124 32.7...",Bonita,273909416.836,113257.374615

In [23]:
# sanity check that we're retaining all the relevant zip codes
print(len(relevant_zip_codes))
print(len(sd_geo_zip))

90
90

### SafeGraph Data EDA

Compare the foot traffic per business in each zip code between the two lockdowns as well as the months in between those lockdowns.

In [ ]:
# there's missing data from this week in Jan --> fix this when we have access to the data again 
# missing_jan_data = pd.read_csv('//sandag.org/home/shared/Technical Services/EDAM/SafeGraph_COVID19/v2/main-file/2020-01-13-weekly-patterns.csv')

In [30]:
# FUTURE WORK: get the foot traffic per business in each zip code for each month

# def set_dates(hh_res, date1, date2, date3):
#     '''Filters the original hh_res dataset to only include values from a certain time period'''
#     first_week = hh_res['date_range_end'] == date1
#     second_week = hh_res['date_range_end'] == date2
#     third_week = hh_res['date_range_end'] == date3
#     visits = hh_res[(first_week) | (second_week) | (third_week)]
#     return visits

# # last three full weeks of data in each month 
# relevant_dates = {#'jan': [datetime.date(2020, 1, 13), datetime.date(2020, 1, 20), datetime.date(2020, 1, 27)], # first case of covid in US
#                   'feb': [datetime.date(2020, 2, 10), datetime.date(2020, 2, 17), datetime.date(2020, 2, 24)], # refer to this as pre-covid
#                   'mar': [datetime.date(2020, 3, 16), datetime.date(2020, 3, 23), datetime.date(2020, 3, 30)], # first shutdown
#                   'apr': [datetime.date(2020, 4, 13), datetime.date(2020, 4, 20), datetime.date(2020, 4, 27)], 
#                   'may': [datetime.date(2020, 5, 11), datetime.date(2020, 5, 18), datetime.date(2020, 5, 25)], 
#                   'jun': [datetime.date(2020, 6, 15), datetime.date(2020, 6, 22), datetime.date(2020, 6, 29)], 
#                   'jul': [datetime.date(2020, 7, 13), datetime.date(2020, 7, 20), datetime.date(2020, 7, 27)], 
#                   'aug': [datetime.date(2020, 8, 17), datetime.date(2020, 8, 24), datetime.date(2020, 8, 31)], 
#                   'sep': [datetime.date(2020, 9, 14), datetime.date(2020, 9, 21), datetime.date(2020, 9, 28)], 
#                   'oct': [datetime.date(2020, 10, 12), datetime.date(2020, 10, 19), datetime.date(2020, 10, 26)], 
#                   'nov': [datetime.date(2020, 11, 16), datetime.date(2020, 11, 23), datetime.date(2020, 11, 30)], 
#                   'dec': [datetime.date(2020, 12, 14), datetime.date(2020, 12, 21), datetime.date(2020, 12, 28)]} # second lockdown

# # input the filtered dfs into here
# relevant_dfs = {'jan': [], 
#                 'feb': [], 
#                 'mar': [], 
#                 'apr': [], 
#                 'may': [], 
#                 'jun': [], 
#                 'jul': [], 
#                 'aug': [], 
#                 'sep': [], 
#                 'oct': [], 
#                 'nov': [], 
#                 'dec': []}

# for month, dates in relevant_dates.items():
#     visits = set_dates(hh_res, dates[0], dates[1], dates[2])
#     relevant_dfs[month] = visits

##### Normalized Foot Traffic in January

- Gets  3 week rolling average of foot traffic at the end of Jan/beginning of Feb, which is then normalized to the number of devices seen in the panel and number of stores per zip code
- Normalizing to the number of devides seen in the panel accounts for growth/shrinking of recorded businesses
- Normalizing to the number of store per zip code ensures that foot traffic isn't high/low simply due to the number of businesses in that area

In [24]:
# end of january/beginning of feb dates
jan_first_condition = hh_res['date_range_end'] == datetime.date(2020, 1, 27)
jan_second_condition = hh_res['date_range_end'] == datetime.date(2020, 2, 3)
jan_third_condition = hh_res['date_range_end'] == datetime.date(2020, 2, 10)
jan_week_visits = hh_res[(jan_first_condition) | (jan_second_condition) | (jan_third_condition)] # date range = 1/20 - 2/10

# find the number of visits in each zip code
jan_week_visits_per_zip = jan_week_visits.groupby('postal_code', as_index = False).sum()[['postal_code','raw_visit_counts']]
jan_week_visits_per_zip['raw_visit_counts'] = jan_week_visits_per_zip['raw_visit_counts']/3

# --- start normalization ---
# divide each foot count by the number of devices in the panel
jan_norm_stats_w1 = pd.read_csv('normalization_stats/2020-01-20-normalization-stats.csv')
jan_norm_stats_w2 = pd.read_csv('normalization_stats/2020-01-27-normalization-stats.csv')
jan_norm_stats_w3 = pd.read_csv('normalization_stats/2020-02-03-normalization-stats.csv')
agg_jan_norm_stats = sum(jan_norm_stats_w1['total_devices_seen'].astype(int)) + sum(jan_norm_stats_w2['total_devices_seen'].astype(int)) + sum(jan_norm_stats_w3['total_devices_seen'].astype(int))
jan_week_visits_per_zip['normalized_visit_counts'] = (jan_week_visits_per_zip['raw_visit_counts']/agg_jan_norm_stats)

# divide this by the number of stores in each zip code
jan_stores_counts = jan_week_visits.groupby('postal_code', as_index = False).count()[['postal_code','id']]
jan_week_visits_per_zip = pd.merge(jan_week_visits_per_zip, jan_stores_counts, on = "postal_code")
jan_week_visits_per_zip['normalized_visit_counts'] = (jan_week_visits_per_zip['normalized_visit_counts']/jan_week_visits_per_zip['id']) 
# --- end normalization ---

# adding a column to specify that this data is representative of January data
jan_week_visits_per_zip['month'] = "JAN"

print(jan_week_visits_per_zip.shape)
jan_week_visits_per_zip.head()

(138, 5)

  postal_code  raw_visit_counts  normalized_visit_counts    id month
0       91901      13135.666667             5.352563e-08   570   JAN
1       91902       9056.333333             4.337058e-08   485   JAN
2       91905        118.000000             7.212453e-09    38   JAN
3       91906       1549.333333             3.869425e-08    93   JAN
4       91910      72721.000000             5.804321e-08  2910   JAN

##### Normalized Foot Traffic in March

- Gets  3 week rolling average of foot traffic at the end of March/beginning of April (indicating the start of quarantine), which is then normalized to the number of devices seen in the panel and number of stores per zip code
- Normalizing to the number of devides seen in the panel accounts for growth/shrinking of recorded businesses
- Normalizing to the number of store per zip code ensures that foot traffic isn't high/low simply due to the number of businesses in that area

In [47]:
# the week of the national emergency dates
nm_first_condition = hh_res['date_range_end'] == datetime.date(2020, 3, 23)
nm_second_condition = hh_res['date_range_end'] == datetime.date(2020, 3, 30)
nm_third_condition = hh_res['date_range_end'] == datetime.date(2020, 4, 6)
nat_emerg_week = hh_res[(nm_first_condition) | (nm_second_condition) | (nm_third_condition)] # range = 3/16 - 4/6

# find the number of visits in each zip code
nat_emerg_week_per_zip = nat_emerg_week.groupby('postal_code', as_index = False).sum()[['postal_code','raw_visit_counts']]
nat_emerg_week_per_zip['raw_visit_counts'] = nat_emerg_week_per_zip['raw_visit_counts']/3

# --- start normalization ---
# divide each foot count by the number of devices in the panel
nat_emerg_norm_stats_w1 = pd.read_csv('normalization_stats/2020-03-16-normalization-stats.csv') 
nat_emerg_norm_stats_w2 = pd.read_csv('normalization_stats/2020-03-23-normalization-stats.csv')
nat_emerg_norm_stats_w3 = pd.read_csv('normalization_stats/2020-03-30-normalization-stats.csv')
agg_nat_emerg_norm_stats = sum(nat_emerg_norm_stats_w1['total_devices_seen'].astype(int)) + sum(nat_emerg_norm_stats_w2['total_devices_seen'].astype(int)) + sum(nat_emerg_norm_stats_w3['total_devices_seen'].astype(int))
nat_emerg_week_per_zip['normalized_visit_counts'] = (nat_emerg_week_per_zip['raw_visit_counts']/agg_nat_emerg_norm_stats)

# divide this by the number of stores in each zip code
nat_emerg_stores_counts = nat_emerg_week.groupby('postal_code', as_index = False).count()[['postal_code','id']]
nat_emerg_week_per_zip = pd.merge(nat_emerg_week_per_zip, nat_emerg_stores_counts, on = "postal_code")
nat_emerg_week_per_zip['normalized_visit_counts'] = (nat_emerg_week_per_zip['normalized_visit_counts']/nat_emerg_week_per_zip['id'])
# --- end normalization ---

# adding a column to specify that this data is representative of national emergency data
nat_emerg_week_per_zip['month'] = "MAR"

print(nat_emerg_week_per_zip.shape)
nat_emerg_week_per_zip.head(2)

(136, 5)

  postal_code  raw_visit_counts  normalized_visit_counts   id month
0       91901       5883.666667             3.268857e-08  523   MAR
1       91902       3992.333333             2.660663e-08  436   MAR

##### Normalized Foot Traffic in December

- Gets  3 week rolling average of foot traffic at the end of December (indicating the second shut down of CA), which is then normalized to the number of devices seen in the panel and number of stores per zip code
- Normalizing to the number of devides seen in the panel accounts for growth/shrinking of recorded businesses
- Normalizing to the number of store per zip code ensures that foot traffic isn't high/low simply due to the number of businesses in that area

In [48]:
# the week of the second california shut down
dec_first_condition = hh_res['date_range_end'] == datetime.date(2020, 12, 14)
dec_second_condition = hh_res['date_range_end'] == datetime.date(2020, 12, 21)
dec_third_condition = hh_res['date_range_end'] == datetime.date(2020, 12, 28)
dec_week = hh_res[(dec_first_condition) | (dec_second_condition) | (dec_third_condition)] # range = 12/07 - 12/28

# find the number of visits in each zip code
dec_week_per_zip = dec_week.groupby('postal_code', as_index = False).sum()[['postal_code','raw_visit_counts']]
dec_week_per_zip['raw_visit_counts'] = dec_week_per_zip['raw_visit_counts']/3

# --- start normalization --- 
# divide each foot count by the number of devices in the panel
dec_norm_stats_w1 = pd.read_csv('normalization_stats/2020-12-14-normalization-stats.csv')
dec_norm_stats_w2 = pd.read_csv('normalization_stats/2020-12-21-normalization-stats.csv')
dec_norm_stats_w3 = pd.read_csv('normalization_stats/2020-12-28-normalization-stats.csv')
dec_norm_stats_w1 = dec_norm_stats_w1[dec_norm_stats_w1['region'] == 'ALL_STATES'] # to match jan and mar/apr
dec_norm_stats_w2 = dec_norm_stats_w2[dec_norm_stats_w2['region'] == 'ALL_STATES']
dec_norm_stats_w3 = dec_norm_stats_w3[dec_norm_stats_w3['region'] == 'ALL_STATES']
agg_dec_norm_stats = sum(dec_norm_stats_w1['total_devices_seen'].astype(int)) + sum(dec_norm_stats_w2['total_devices_seen'].astype(int)) + sum(dec_norm_stats_w3['total_devices_seen'].astype(int))
dec_week_per_zip['normalized_visit_counts'] = (dec_week_per_zip['raw_visit_counts']/agg_dec_norm_stats)
# --- start normalization ---

# divide this by the number of stores in each zip code
dec_week_stores_counts = dec_week.groupby('postal_code', as_index = False).count()[['postal_code','id']]
dec_week_per_zip = pd.merge(dec_week_per_zip, dec_week_stores_counts, on = "postal_code")
dec_week_per_zip['normalized_visit_counts'] = (dec_week_per_zip['normalized_visit_counts']/dec_week_per_zip['id'])

# adding a column to specify that this data is representative of december data
dec_week_per_zip['month'] = "DEC"

print(dec_week_per_zip.shape)
dec_week_per_zip.head(2)

(137, 5)

  postal_code  raw_visit_counts  normalized_visit_counts   id month
0       91901      12209.333333             6.137538e-08  588   DEC
1       91902       5360.333333             3.300883e-08  480   DEC

##### Combining the DataFrames

This portion combines the above dataframes for the different months in order to standardize the normalized visit counts to each other. This makes the different months comparable and set up our analysis for percentage changes between Jan-Mar and Jan-Dec.

In [49]:
combined = pd.concat([jan_week_visits_per_zip, nat_emerg_week_per_zip, dec_week_per_zip])

norm_input = combined['normalized_visit_counts']
minimum = 0
maximum = max(norm_input)
combined['rescaled_normalized_visit_counts'] = ((norm_input - minimum)*100) / (maximum - minimum) #rescale the numbers to be between 0 and 100

combined.head()

,postal_code,raw_visit_counts,normalized_visit_counts,id,month,rescaled_normalized_visit_counts
0,91901,13135.666667,5.352563e-08,570,JAN,3.606421
1,91902,9056.333333,4.337058e-08,485,JAN,2.922199
2,91905,118.000000,7.212453e-09,38,JAN,0.485957
3,91906,1549.333333,3.869425e-08,93,JAN,2.607120
4,91910,72721.000000,5.804321e-08,2910,JAN,3.910803
...,...,...,...,...,...,...
132,92178,1.666667,2.463192e-09,2,DEC,0.165964
133,92179,57.333333,1.882974e-08,9,DEC,1.268700
134,92182,938.666667,3.963628e-08,70,DEC,2.670592
135,92187,121.333333,1.195469e-07,3,DEC,8.054768
136,92199,378.666667,1.865458e-07,6,DEC,12.568979

In [56]:
jan_week_visits_per_zip = combined[combined['month'] == 'JAN']

In [57]:
nat_emerg_week_per_zip = combined[combined['month'] == 'MAR']

In [59]:
dec_week_per_zip =  combined[combined['month'] == 'DEC']

In [3]:
# get percentage change in foot traffic between january --> march and january --> december 

df = pd.DataFrame()
df['postal_code'] = jan_week_visits_per_zip['postal_code']
df['R1'] = jan_week_visits_per_zip['normalized_visit_counts']

nat_emerg_week_per_zip_relevant = nat_emerg_week_per_zip[['postal_code', 'normalized_visit_counts']]
dec_week_per_zip_relevant = dec_week_per_zip[['postal_code', 'normalized_visit_counts']]

df = df.merge(nat_emerg_week_per_zip_relevant, how = 'inner', on='postal_code').rename(columns={"normalized_visit_counts": "R2"})
df = df.merge(dec_week_per_zip_relevant, how = 'inner', on='postal_code').rename(columns={"normalized_visit_counts": "R3"})

df.head()

NameError: name 'jan_week_visits_per_zip' is not defined

In [ ]:
# sanity check that all zip codes got added to the above table

In [61]:
# get the percentage change between values

df['jan_to_march'] = df[['R2', 'R1']].apply(lambda row: (row.iloc[0]-row.iloc[1])/row.iloc[0]*100, axis=1)
df['jan_to_december'] = df[['R3', 'R1']].apply(lambda row: (row.iloc[0]-row.iloc[1])/row.iloc[0]*100, axis=1)
df

In [78]:
# update the sd geozip file to reflect which zip codes have percentage changes
sd_geo_zip_updated = sd_geo_zip.merge(df, left_on = 'zip', right_on='postal_code')
sd_geo_zip_updated.head(3)

,zip,geometry,community,shape_star,shape_stle,postal_code,R1,R2,R3,jan_to_march,jan_to_december
0,91901,"POLYGON ((-116.74539 32.96063, -116.74085 32.9...",Alpine,4149939944.16,326045.262676,91901,5.352563e-08,3.268857e-08,6.137538e-08,-63.744208,12.789733
1,91902,"POLYGON ((-116.97172 32.70838, -116.97124 32.7...",Bonita,273909416.836,113257.374615,91902,4.337058e-08,2.660663e-08,3.300883e-08,-63.006683,-31.390837
2,91910,"POLYGON ((-117.06354 32.65011, -117.06345 32.6...",Chula Vista,403437442.009,112587.791814,91910,5.804321e-08,2.982016e-08,4.050239e-08,-94.644181,-43.308121

In [77]:
# check why this zip code is being taken out later

for i in sd_geo_zip['zip'].to_list():
    if i not in sd_geo_zip_updated['zip'].to_list():
        print(i)

92536

##### Maps

This portion lays out the code for the maps created with the cleaned and revised dataframes.

In [52]:
# m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

# choropleth = folium.Choropleth(
#     geo_data = sd_geo_zip, 
#     data = jan_week_visits_per_zip,
#     columns=['postal_code', 'rescaled_normalized_visit_counts'],
#     key_on='feature.properties.zip',
#     fill_color='YlOrRd',
#     threshold_scale = scale,
#     fill_opacity=0.4,
#     line_opacity=0.3
# ).add_to(m)

# style_function = "font-size: 15px; font-weight: bold"
# choropleth.geojson.add_child(
#     folium.features.GeoJsonTooltip(['zip'], style=style_function, labels=False))

# m.save('maps/Normalized Foot Traffic per Business/January.html')

In [47]:
# #map
# m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

# choropleth = folium.Choropleth(
#     geo_data = sd_geo_zip, 
#     data = nat_emerg_week_per_zip,
#     columns=['postal_code', 'rescaled_normalized_visit_counts'],
#     key_on='feature.properties.zip',
#     fill_color='YlOrRd',
#     threshold_scale = scale,
#     fill_opacity=0.4,
#     line_opacity=0.3
# ).add_to(m)

# style_function = "font-size: 15px; font-weight: bold"
# choropleth.geojson.add_child(
#     folium.features.GeoJsonTooltip(['zip'], style=style_function, labels=False))

# m.save('maps/Normalized Foot Traffic per Business/March.html')

In [20]:
# #map
# m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

# choropleth = folium.Choropleth(
#     geo_data = sd_geo_zip, 
#     data = june_week_per_zip,
#     columns=['postal_code', 'rescaled_normalized_visit_counts'],
#     key_on='feature.properties.zip',
#     fill_color='YlOrRd',
#     threshold_scale = scale,
#     fill_opacity=0.4,
#     line_opacity=0.3
# ).add_to(m)

# style_function = "font-size: 15px; font-weight: bold"
# choropleth.geojson.add_child(
#     folium.features.GeoJsonTooltip(['zip'], style=style_function, labels=False))

# m.save('maps/Normalized Foot Traffic per Business/June.html')

In [21]:
# #map
# m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

# choropleth = folium.Choropleth(
#     geo_data = sd_geo_zip, 
#     data = dec_week_per_zip,
#     columns=['postal_code', 'rescaled_normalized_visit_counts'],
#     key_on='feature.properties.zip',
#     fill_color='YlOrRd',
#     threshold_scale = scale,
#     fill_opacity=0.4,
#     line_opacity=0.3
# ).add_to(m)

# style_function = "font-size: 15px; font-weight: bold"
# choropleth.geojson.add_child(
#     folium.features.GeoJsonTooltip(['zip'], style=style_function, labels=False))

# m.save('maps/Normalized Foot Traffic per Business/December.html')

##### Create Base Maps (w/o any prettifying)

In [80]:
print(min(sd_geo_zip_updated.jan_to_march))
print(max(sd_geo_zip_updated.jan_to_march))

print('\n')
print(min(sd_geo_zip_updated.jan_to_december))
print(max(sd_geo_zip_updated.jan_to_december))

-4491.447424215054
9.011205906752268


-839.7013991317853
27.8058897552105

In [82]:
scale_list = sd_geo_zip_updated.jan_to_march.to_list() + sd_geo_zip_updated.jan_to_december.to_list()
print(max(scale_list))

27.8058897552105

In [83]:
scale = []
count = 0


for i in [0, 20, 40, 60, 80, 100]: #list(scale_list.quantile([0,0.25,0.5,0.75, 1])):
    scale.append(np.percentile(scale_list, i))

scale.sort()
scale

[-4491.447424215054,
 -115.3274615780237,
 -73.12065321217841,
 -54.28556615188203,
 -34.09224112298252,
 27.8058897552105]

In [101]:
#map
m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

choropleth = folium.Choropleth(
    geo_data = sd_geo_zip_updated, 
    data = sd_geo_zip_updated,
    columns=['postal_code', 'jan_to_march'],
    key_on='feature.properties.zip',
    fill_color='YlOrRd',
    threshold_scale = [-4491.447424215054, -115.3274615780237, -73.12065321217841, -54.28556615188203, -34.09224112298252, 0, 27.8058897552105],
    fill_opacity=0.4,
    line_opacity=0.3
).add_to(m)

style_function = "font-size: 15px; font-weight: bold"
choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(['zip', 'jan_to_march'], style=style_function, labels=False))

m.save('maps/Normalized Foot Traffic per Business/First_Lockdown.html')

In [102]:
#map
m = folium.Map([32.7, -117.2], tiles="cartodbpositron", zoom_start=12)

choropleth = folium.Choropleth(
    geo_data = sd_geo_zip_updated, 
    data = sd_geo_zip_updated,
    columns=['postal_code', 'jan_to_december'],
    key_on='feature.properties.zip',
    fill_color='YlOrRd',
    threshold_scale = [-4491.447424215054, -115.3274615780237, -73.12065321217841, -54.28556615188203, -34.09224112298252, 0, 27.8058897552105],
    fill_opacity=0.4,
    line_opacity=0.3
).add_to(m)

style_function = "font-size: 15px; font-weight: bold"
choropleth.geojson.add_child(
    folium.features.GeoJsonTooltip(['zip', 'jan_to_december'], style=style_function, labels=False))

m.save('maps/Normalized Foot Traffic per Business/Second_Lockdown.html')

### Prettify the maps

In [216]:
import branca.colormap as cm

colormap_dept = cm.StepColormap(
    colors=['#ee0028', '#ff9a61', '#ffe6a4', '#daf8aa', '#86dc76', '#00ae53'],
    vmin=min(scale_list),
    vmax=max(scale_list),
    index= [-4491.447424215054, -115.3274615780237, -73.12065321217841, -54.28556615188203, -34.09224112298252, 0, 27.8058897552105])

colormap_dept

In [217]:
import folium
first_lockdown_map = folium.Map([33, -116.8],
                    zoom_start = 9.7, tiles='cartodbpositron')

In [218]:
from folium import plugins

def style_zero_function(feature):
    default_style = {
        'fillOpacity': 0.07,
        'color': 'gray',
        'weight': 0.0001
    }
        
    default_style['fillPattern'] = plugins.pattern.StripePattern(angle=-45)
    
    return default_style

folium.GeoJson(
    non_included_zips,
    style_function = style_zero_function,
    name='Community').add_to(first_lockdown_map)

first_lockdown_dict = sd_geo_zip_updated.set_index('zip')['jan_to_march']

folium.GeoJson(
    sd_geo_zip_updated,
    style_function=lambda feature:{
        'fillColor': colormap_dept(feature['properties']['jan_to_march']),
    'color': '',
    'weight': 0.0001,
    'fillOpacity': 0.7
    },
    ).add_to(first_lockdown_map)

folium.GeoJson(
    sd_geo_zip_updated,
    style_function = lambda x: {
        'color': 'black',
        'weight': 1.5,
        'fillOpacity': 0
    }, 
    tooltip=folium.GeoJsonTooltip(
        fields=['postal_code', 'jan_to_march'],
        aliases=['Zip Code', 'Rate of Change'],
        localize=True
    ),
    name='Zip Codes').add_to(first_lockdown_map)

folium.map.CustomPane('labels').add_to(first_lockdown_map)
folium.TileLayer('CartoDBPositronOnlyLabels',
                 pane='labels').add_to(first_lockdown_map)

from branca.element import Template, MacroElement

template = """
{% macro html(this, kwargs) %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Draggable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script>
  $( function() {
    $( "#maplegend" ).draggable({
                    start: function (event, ui) {
                        $(this).css({
                            right: "auto",
                            top: "auto",
                            bottom: "auto"
                        });
                    }
                });
});

  </script>
</head>
<body>

<div id='maplegend' class='maplegend' 
    style='position: absolute; z-index:9999; border:0px; background-color:rgba(255, 255, 255, 0.8);
     border-radius:6px; padding: 10px; font-size:25px; left: 0px; top: 0px;'>
     
<div class='legend-title'>Rate of Change in Foot Traffic Between January 2020 and March 2020</div>
<div class='legend-scale'><font size="3"></font></div>
</div>

<div id='maplegend' class='maplegend' 
    style='position: absolute; z-index:9999; border:2px solid grey; background-color:rgba(255, 255, 255, 0.8);
     border-radius:6px; padding: 10px; font-size:14px; right: 20px; bottom: 20px;'>
     
<div class='legend-title'>Legend</div>
<div class='legend-scale'>
  <ul class='legend-labels'>
    <li><span style='background:#ee0028;opacity:0.7;'></span>-4491% to -115%</li>
    <li><span style='background:#ff9a61;opacity:0.7;'></span>-115% to -73%</li>
    <li><span style='background:#ffe6a4;opacity:0.7;'></span>-73% to -54%</li>
    <li><span style='background:#daf8aa;opacity:0.7;'></span>-54% to -34%</li>
    <li><span style='background:#86dc76;opacity:0.7;'></span>-34% to 0%</li>
    <li><span style='background:#00ae53;opacity:0.7;'></span>0% to 28%</li>
    <li><span style='background:repeating-linear-gradient(
    -55deg,
    #ffffff,
    #ffffff 5px,
    #b2b2b2 5px,
    #b2b2b2 10px);
    opacity:0.7;'></span>Zip Code Data Not Included</li>

  </ul>
</div>
</div>
 
</body>
</html>

<style type='text/css'>
  .maplegend .legend-title {
    text-align: left;
    margin-bottom: 5px;
    font-weight: bold;
    font-size: 90%;
    }
  .maplegend .legend-scale ul {
    margin: 0;
    margin-bottom: 5px;
    padding: 0;
    float: left;
    list-style: none;
    }
  .maplegend .legend-scale ul li {
    font-size: 80%;
    list-style: none;
    margin-left: 0;
    line-height: 18px;
    margin-bottom: 2px;
    }
  .maplegend ul.legend-labels li span {
    display: block;
    float: left;
    height: 16px;
    width: 30px;
    margin-right: 5px;
    margin-left: 0;
    border: 1px solid #999;
    }
  .maplegend .legend-source {
    font-size: 80%;
    color: #777;
    clear: both;
    }
  .maplegend a {
    color: #777;
    }
</style>
{% endmacro %}"""

macro = MacroElement()
macro._template = Template(template)

first_lockdown_map.get_root().add_child(macro)

first_lockdown_map.save('maps/Normalized Foot Traffic per Business/First_Lockdown.html')

In [219]:
from folium import plugins

first_lockdown_map = folium.Map([33, -116.8],
                    zoom_start = 9.7, tiles='cartodbpositron')

def style_zero_function(feature):
    default_style = {
        'fillOpacity': 0.07,
        'color': 'gray',
        'weight': 0.0001
    }
        
    default_style['fillPattern'] = plugins.pattern.StripePattern(angle=-45)
    
    return default_style

folium.GeoJson(
    non_included_zips,
    style_function = style_zero_function,
    name='Community').add_to(first_lockdown_map)

first_lockdown_dict = sd_geo_zip_updated.set_index('zip')['jan_to_december']

folium.GeoJson(
    sd_geo_zip_updated,
    style_function=lambda feature:{
        'fillColor': colormap_dept(feature['properties']['jan_to_december']),
    'color': '',
    'weight': 0.0001,
    'fillOpacity': 0.7
    },
    ).add_to(first_lockdown_map)

folium.GeoJson(
    sd_geo_zip_updated,
    style_function = lambda x: {
        'color': 'black',
        'weight': 1.5,
        'fillOpacity': 0
    }, 
    tooltip=folium.GeoJsonTooltip(
        fields=['postal_code', 'jan_to_december'],
        aliases=['Zip Code', 'Rate of Change'],
        localize=True
    ),
    name='Zip Codes').add_to(first_lockdown_map)

folium.map.CustomPane('labels').add_to(first_lockdown_map)
folium.TileLayer('CartoDBPositronOnlyLabels',
                 pane='labels').add_to(first_lockdown_map)

from branca.element import Template, MacroElement

template = """
{% macro html(this, kwargs) %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Draggable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script>
  $( function() {
    $( "#maplegend" ).draggable({
                    start: function (event, ui) {
                        $(this).css({
                            right: "auto",
                            top: "auto",
                            bottom: "auto"
                        });
                    }
                });
});

  </script>
</head>
<body>

<div id='maplegend' class='maplegend' 
    style='position: absolute; z-index:9999; border:0px; background-color:rgba(255, 255, 255, 0.8);
     border-radius:6px; padding: 10px; font-size:25px; left: 0px; top: 0px;'>
     
<div class='legend-title'>Rate of Change in Foot Traffic Between January 2020 and December 2020</div>
<div class='legend-scale'><font size="3"></font></div>
</div>

<div id='maplegend' class='maplegend' 
    style='position: absolute; z-index:9999; border:2px solid grey; background-color:rgba(255, 255, 255, 0.8);
     border-radius:6px; padding: 10px; font-size:14px; right: 20px; bottom: 20px;'>
     
<div class='legend-title'>Legend</div>
<div class='legend-scale'>
  <ul class='legend-labels'>
  <li><span style='background:#ee0028;opacity:0.7;'></span>-4491% to -115%</li>
    <li><span style='background:#ff9a61;opacity:0.7;'></span>-115% to -73%</li>
    <li><span style='background:#ffe6a4;opacity:0.7;'></span>-73% to -54%</li>
    <li><span style='background:#daf8aa;opacity:0.7;'></span>-54% to -34%</li>
    <li><span style='background:#86dc76;opacity:0.7;'></span>-34% to 0%</li>
    <li><span style='background:#00ae53;opacity:0.7;'></span>0% to 28%</li>
    <li><span style='background:repeating-linear-gradient(
    -55deg,
    #ffffff,
    #ffffff 5px,
    #b2b2b2 5px,
    #b2b2b2 10px);
    opacity:0.7;'></span>Zip Code Data Not Included</li>

  </ul>
</div>
</div>
 
</body>
</html>

<style type='text/css'>
  .maplegend .legend-title {
    text-align: left;
    margin-bottom: 5px;
    font-weight: bold;
    font-size: 90%;
    }
  .maplegend .legend-scale ul {
    margin: 0;
    margin-bottom: 5px;
    padding: 0;
    float: left;
    list-style: none;
    }
  .maplegend .legend-scale ul li {
    font-size: 80%;
    list-style: none;
    margin-left: 0;
    line-height: 18px;
    margin-bottom: 2px;
    }
  .maplegend ul.legend-labels li span {
    display: block;
    float: left;
    height: 16px;
    width: 30px;
    margin-right: 5px;
    margin-left: 0;
    border: 1px solid #999;
    }
  .maplegend .legend-source {
    font-size: 80%;
    color: #777;
    clear: both;
    }
  .maplegend a {
    color: #777;
    }
</style>
{% endmacro %}"""

macro = MacroElement()
macro._template = Template(template)

first_lockdown_map.get_root().add_child(macro)

first_lockdown_map.save('maps/Normalized Foot Traffic per Business/Second_Lockdown.html')

### Finding the Top 5 businesses That Are the Most Prevalent in Each Zip Code
This portion of the notebook finds the top 5 businesses prevelant in each zip code so we can see if there's a correlation between business type and foot traffic. This portion is not finished and will be slated as future work when SANDAG has access to the dataset again. 

__Relevant notes from Stephanie:__
* NAICS Codes: 71 and 72 --> tourism
* NAICS Codes: 62 --> hospitals (look into 92123)
* Check out testing center foot traffic

In [134]:
##BEGIN CODE BLOCK

hh_naics_query = """SELECT [safegraph_place_id]
      ,[parent_safegraph_place_id]
      ,[location_name]
      ,[safegraph_brand_ids]
      ,[brands]
      ,[top_category]
      ,[sub_category]
      ,[naics_code]
      ,[latitude]
      ,[longitude]
      ,[street_address]
      ,[city]
      ,[region]
      ,[postal_code]
      ,[iso_country_code]
      ,[phone_number]
      ,[open_hours]
      ,[category_tags]
  FROM [ws].[staging].[safegraph_core_places]
  WHERE naics_code LIKE '722%' and postal_code BETWEEN '91901' and '92199';
  """

sql_conn3 = pyodbc.connect('''DRIVER={ODBC Driver 13 for SQL Server};
                           SERVER=SQL2014A8;
                           DATABASE=census;
                           Trusted_Connection=yes''')

hh_naics_result = pd.read_sql(hh_naics_query, sql_conn3)

InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user \'SANDAGNET\\spate\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot open database "census" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user \'SANDAGNET\\spate\'. (18456); [28000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot open database "census" requested by the login. The login failed. (4060)')

In [42]:
hh_naics_res = hh_naics_result.copy()
hh_naics_res.head(2)

,safegraph_place_id,parent_safegraph_place_id,location_name,safegraph_brand_ids,brands,top_category,sub_category,naics_code,latitude,longitude,street_address,city,region,postal_code,iso_country_code,phone_number,open_hours,category_tags
0,sg:376a4b5e4bec47c5accf1c878cc01995,,The Grounds Bean Bar,,,Restaurants and Other Eating Places,Snack and Nonalcoholic Beverage Bars,722515,32.788544,-117.237816,1571 La Playa Ave,San Diego,CA,92109,US,+18582307188,"{ ""Mon"": [[""6:30"", ""19:00""]], ""Tue"": [[""6:30"",...","Coffee Shop,Brunch"
1,sg:32c63989e31f47d6a5765340990f6b15,,Starbucks,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,Restaurants and Other Eating Places,Snack and Nonalcoholic Beverage Bars,722515,32.795200,-116.962837,124 W Main St Ste 100,El Cajon,CA,92020,US,+16194447415,"{ ""Mon"": [[""5:00"", ""21:00""]], ""Tue"": [[""5:00"",...","Snacks,Counter Service,Dessert,Tea House,Coffe..."

In [46]:
# join the naics code table with the street address
foot_traffic_w_naics = pd.merge(hh_naics_res, hh_res, on = "street_address")
print(foot_traffic_w_naics.columns)

# get the count of restaurants by grouping the table by postal_code
foot_traffic_w_naics.groupby('postal_code_y').count()

Index(['safegraph_place_id_x', 'parent_safegraph_place_id', 'location_name_x',
       'safegraph_brand_ids_x', 'brands_x', 'top_category', 'sub_category',
       'naics_code', 'latitude', 'longitude', 'street_address', 'city_x',
       'region_x', 'postal_code_x', 'iso_country_code_x', 'phone_number',
       'open_hours', 'category_tags', 'id', 'safegraph_place_id_y',
       'location_name_y', 'city_y', 'region_y', 'postal_code_y',
       'iso_country_code_y', 'safegraph_brand_ids_y', 'brands_y',
       'date_range_start', 'date_range_end', 'raw_visit_counts',
       'raw_visitor_counts', 'visits_by_day', 'visits_by_each_hour', 'poi_cbg',
       'visitor_country_of_origin', 'distance_from_home', 'median_dwell',
       'bucketed_dwell_times', 'related_same_day_brand',
       'related_same_week_brand', 'device_type'],
      dtype='object')

,safegraph_place_id_x,parent_safegraph_place_id,location_name_x,safegraph_brand_ids_x,brands_x,top_category,sub_category,naics_code,latitude,longitude,...,visits_by_day,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type
postal_code_y,,,,,,,,,,,,,,,,,,,,,
91901,9167,9167,9167,9167,9167,9167,9167,9167,9167,9167,...,9167,9167,9167,9167,9167,9167,9167,9167,9167,9167
91902,5052,5052,5052,5052,5052,5052,5052,5052,5052,5052,...,5052,5052,5052,5052,5052,5052,5052,5052,5052,5052
91905,178,178,178,178,178,178,178,178,178,178,...,178,178,178,178,178,178,178,178,178,178
91906,270,270,270,270,270,270,270,270,270,270,...,270,270,270,270,270,270,270,270,270,270
91910,24643,24643,24643,24643,24643,24643,24643,24643,24643,24643,...,24643,24643,24643,24643,24643,24643,24643,24643,24643,24643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92155,239,239,239,239,239,239,239,239,239,239,...,239,239,239,239,239,239,239,239,239,239
92161,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089,...,2089,2089,2089,2089,2089,2089,2089,2089,2089,2089
92173,20737,20737,20737,20737,20737,20737,20737,20737,20737,20737,...,20737,20737,20737,20737,20737,20737,20737,20737,20737,20737
92182,7150,7150,7150,7150,7150,7150,7150,7150,7150,7150,...,7150,7150,7150,7150,7150,7150,7150,7150,7150,7150
92199,180,180,180,180,180,180,180,180,180,180,...,180,180,180,180,180,180,180,180,180,180

In [99]:
def top_5_businesses(df):
    """This function gathers the top 5 businesses based on number of locations in a certain zip code"""
    df = df.copy() # create a copy of the dataframe so as not to change the original one
    top_5_businesses = {}
    for i in df['postal_code'].unique():
        df_filtered = df[df['postal_code'] == i]
        df_unique_locations_grouped = df_filtered.groupby('safegraph_place_id', as_index = False).count()[['safegraph_place_id','id']]
        merged_df = pd.merge(df, df_unique_locations_grouped, on = 'safegraph_place_id')
        merged_df = merged_df.sort_values(by='id_y', ascending=False)
        merged_df = merged_df[:5]
        display(merged_df)
        stores = list(merged_df['location_name'])
        count = list(merged_df['id_y'])
        for k in range(len(stores)):
            if i not in top_5_businesses.keys():
                top_5_businesses[i] = [stores[k], count[k]]
            else:
                top_5_businesses[i].append([stores[k], count[k]])
    return top_5_businesses
  
jan_week_visits = hh_res[hh_res['date_range_end'] == datetime.date(2020, 1, 27)]
top_5_businesses(jan_week_visits)

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,92321,sg:226952cb1137474a99da85bed5d49f25,Bella Mia Exclusive Events,333 H St Ste 5000,Chula Vista,CA,91910,US,,,...,"[0,0,0,0,0,0,1,0,0,1,2,0,0,0,0,1,0,3,3,0,1,0,0...",060730127002,"{""US"":43}",7126,80.0,"{""<5"":2,""5-20"":11,""21-60"":15,""61-240"":25,"">240...","{""Nike"":17,""AMC Entertainment"":17,""Simon mall""...","{""Walmart"":21,""Jack in the Box"":16,""Subway"":13...","{""android"":26,""ios"":19}",1
669,212735686,sg:44c84d25770f45568c1784ce7101092b,El Comal,262 Third Ave,Chula Vista,CA,91910,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0...",060730123021,"{""US"":43}",8918,61.5,"{""<5"":0,""5-20"":7,""21-60"":19,""61-240"":18,"">240""...","{""Starbucks"":31,""Baskin Robbins"":25,""Goodwill ...","{""Westfield"":28,""Starbucks"":26,""Costco Wholesa...","{""android"":22,""ios"":25}",1
641,201393042,sg:1033d2d195a740f98d08e9a5bf655fee,7-Eleven,285 Broadway,Chula Vista,CA,91910,US,SG_BRAND_2e2448f12fc87fe452e9166153797a7f,7-Eleven,...,"[1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730124023,"{""US"":25,""MX"":4}",8969,11.0,"{""<5"":2,""5-20"":23,""21-60"":3,""61-240"":0,"">240"":1}","{""Peter Piper Pizza"":33,""Ross Stores"":33,""Walm...","{""Jack in the Box"":35,""McDonald's"":32,""ARCO"":3...","{""android"":22,""ios"":8}",1
642,203604888,sg:32e200015b0148a79c7040bc2e8bceed,National Glass Experts,639 Broadway,Chula Vista,CA,91910,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730126002,{},0,261.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
643,203742586,sg:949324e812d14b6db698142ca51ced48,Wings N' Things,481 Broadway Ste A,Chula Vista,CA,91910,US,SG_BRAND_788975e85812be769bfbf49d3756465f,Wings N' Things,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,2,0,0,1,0,0,0...",060730127001,"{""US"":28}",4450,21.0,"{""<5"":0,""5-20"":15,""21-60"":15,""61-240"":1,"">240"":0}","{""Sears Home Services"":50,""GameStop"":20,""Starb...","{""Walmart"":22,""7-Eleven"":21,""Shell Oil"":19,""Fo...","{""android"":14,""ios"":14}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,76240,sg:9c2fe808b6024a41bbdb5f1c88d1a9e4,Rancho Santa Fe Pharmacy,6056 El Tordo Ste 1188,Rancho Santa Fe,CA,92067,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0...",060730171064,"{""US"":17}",11935,64.0,"{""<5"":0,""5-20"":9,""21-60"":2,""61-240"":6,"">240"":6}","{""BevMo"":17}","{""Starbucks"":20,""Westfield"":19,""Specialty's Ca...","{""android"":6,""ios"":13}",1
41,150673816,sg:dd2f7d67d22f4a9996018cc4c092d800,Merrill Lynch,6002 El Tordo,Rancho Santa Fe,CA,92067,US,SG_BRAND_44f5944cc1e9f835,Merrill Lynch,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730171064,"{""US"":5}",0,422.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":3}",{},{},"{""android"":0,""ios"":4}",1
59,211318449,sg:63a721831ad74ae7a21b6631fc2c76a2,Caffe Positano,16079 San Dieguito Rd,Rancho Santa Fe,CA,92067,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170291,{},0,22.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
58,208112321,sg:397b6c1868d64f299f82148299b77a22,Del Mar Country Club,6001 Clubhouse Dr,Rancho Santa Fe,CA,92067,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170291,{},0,29.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
57,203637179,sg:c0a2b0248e384f5cafcf7c1ec7377981,Mille Fleurs,6009 Paseo Delicias,Rancho Santa Fe,CA,92067,US,,,...,"[0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,3,1,1,0,0,0,0...",060730171064,"{""US"":93}",9612,40.0,"{""<5"":4,""5-20"":33,""21-60"":34,""61-240"":32,"">240...","{""Starbucks"":23,""Tribute Portfolio"":8,""Valero ...","{""Starbucks"":26,""Westfield"":12,""Costco Wholesa...","{""android"":25,""ios"":70}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,92751,sg:254ce619fdba462998e1b048a94b3657,Navy Gateway Inns & Suites,1500 Rogers Rd,Coronado,CA,92135,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,2,1,0,0,0,1...",060730113001,"{""US"":17}",14930,143.0,"{""<5"":3,""5-20"":12,""21-60"":5,""61-240"":14,"">240""...","{""In-N-Out Burger"":25,""Burlington"":17}","{""Navy Exchange"":19,""Dunkin'"":17,""In-N-Out Bur...","{""android"":8,""ios"":8}",1
10,192713783,sg:9bf45b3537a844a480524607d34c7e96,Auntie Anne's,Food Court Bldg. 2017,San Diego,CA,92135,US,SG_BRAND_ce748140d1750c3620f9e803e4af0170,Auntie Anne's,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730113001,"{""US"":4}",0,182.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
17,285984175,sg:6f45299614114b658a941b9d245b3320,Subway,Nasni Bldg #244 North Island Nas,San Diego,CA,92135,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,4,1,0,2,2,0,0...",060730113001,"{""US"":67}",16249,18.0,"{""<5"":2,""5-20"":57,""21-60"":19,""61-240"":11,"">240...","{""Menchie's"":9,""Check 'n Go"":7,""United States ...","{""Dunkin'"":12,""7-Eleven"":9,""Vons"":9,""Costco Wh...","{""android"":28,""ios"":37}",1
16,284199462,sg:3e59e92d4b664bca8e8bbcfd9cfd72a9,Subway,Nasni Bld. #322 North Island Nas,San Diego,CA,92135,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[0,0,0,0,0,0,2,1,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0...",060730113001,"{""US"":37}",14591,36.0,"{""<5"":2,""5-20"":34,""21-60"":22,""61-240"":28,"">240...","{""Dunkin'"":12,""Homewood Suites by Hilton"":7,""C...","{""Navy Exchange"":16,""Dunkin'"":10,""Smart & Fina...","{""android"":18,""ios"":22}",1
15,254474177,sg:8887cfa85b6e48fcb61debc3be39addf,Pizza Parlor,MC Cain Blvd,Coronado,CA,92135,US,,,...,"[1,0,0,0,0,0,1,0,0,1,1,0,3,0,1,0,1,3,1,1,0,0,0...",060730113001,"{""US"":86}",14882,47.5,"{""<5"":2,""5-20"":45,""21-60"":47,""61-240"":55,"">240...","{""Jack in the Box"":10,""Walmart"":9,""76"":8,""Burg...","{""Subway"":16,""Dunkin'"":15,""Navy Exchange"":13,""...","{""android"":28,""ios"":60}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,552250,sg:192e48f6f3374af59d32b4086e857241,CrossFit,841 1/2 Orange Ave,Coronado,CA,92118,US,SG_BRAND_ae6abf1aa02c01cfe560b9315db66b07,CrossFit,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730109002,"{""US"":4}",0,58.5,"{""<5"":0,""5-20"":1,""21-60"":3,""61-240"":4,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
210,207819563,sg:078f0f7e34f847188dcc76339fdd60e8,Rotary Park,1050 Orange Ave,Coronado,CA,92118,US,,,...,"[0,0,0,0,0,0,0,1,0,1,0,0,2,0,1,0,1,0,1,0,0,0,0...",060730218001,"{""US"":52,""BR"":4}",8538,22.5,"{""<5"":2,""5-20"":20,""21-60"":30,""61-240"":12,"">240...","{""Brigatine Seafood and Oyster Bar"":17,""Homewo...","{""Panera Bread"":21,""Simon mall"":19,""Starbucks""...","{""android"":12,""ios"":44}",1
217,211203129,sg:8e52e9efa18e4086b5fead380802afb8,Avenue Liquor And Wine Store,878 Orange Ave,Coronado,CA,92118,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,2,0,0,0,0,0...",060730108001,"{""US"":35,""MX"":4}",1310,9.0,"{""<5"":2,""5-20"":32,""21-60"":7,""61-240"":1,"">240"":0}","{""Build A Bear Workshop"":12,""Smart & Final"":12...","{""Vons"":25,""Westfield"":22,""Rite Aid"":14,""Paner...","{""android"":17,""ios"":21}",1
216,208889643,sg:1147d240b0f14b68949c5cfb952378be,Cutler Field,Cutler Field,San Diego,CA,92118,US,,,...,"[0,0,0,0,0,0,0,1,2,0,1,2,0,0,2,2,5,0,0,0,0,0,0...",060730111002,"{""US"":268}",14222,57.0,"{""<5"":9,""5-20"":172,""21-60"":149,""61-240"":221,"">...","{""Ramada"":13,""Chevron"":7}","{""Starbucks"":16,""Westfield"":13,""Simon mall"":13...","{""android"":66,""ios"":205}",1
215,210660619,sg:de72d5b34a6a4ad0b17601f88ebbccb9,Coronado Pathways Charter,555 D Ave,Coronado,CA,92118,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730111001,{},0,20.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,552238,sg:18d889af2ab442228a4d66a07d4042ee,Timberland,4211 Camino de la Plz Ste 132,San Diego,CA,92173,US,SG_BRAND_1ea02eb629898ff9c708f92ae2ff719d,Timberland,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730100094,"{""MX"":7,""US"":4}",14479,21.0,"{""<5"":0,""5-20"":5,""21-60"":5,""61-240"":1,"">240"":0}","{""Vans"":100,""Nike"":100,""Simon mall"":99,""Westfi...","{""Simon mall"":99,""Costco Wholesale Corp."":52,""...","{""android"":5,""ios"":6}",1
230,202356299,sg:0556b3ed9f87408080849678000ac1fb,Best Western,815 W San Ysidro Blvd,San Diego,CA,92173,US,SG_BRAND_afc74daf1bb2ac39,Best Western,...,"[0,0,0,0,0,0,1,0,2,0,0,0,0,0,1,1,3,2,1,2,0,5,1...",060730100122,"{""US"":37,""MX"":4}",6050,209.5,"{""<5"":3,""5-20"":18,""21-60"":16,""61-240"":20,"">240...","{""Coco's Bakery Restaurants"":24,""ARCO"":20,""Ros...","{""Coco's Bakery Restaurants"":18,""7-Eleven"":17,...","{""android"":33,""ios"":20}",1
238,208769580,sg:47dfc90c23be44e9a171933be4bd7dea,Ghirardelli Chocolate Outlet & Ice Cream Shop,4459 Camino de la Plz Ste 460,San Diego,CA,92173,US,,,...,"[0,0,0,0,0,0,0,0,0,0,2,2,0,1,0,1,2,1,0,0,0,1,0...",060730100094,"{""US"":53,""MX"":14}",9595,19.0,"{""<5"":4,""5-20"":40,""21-60"":26,""61-240"":9,"">240"":4}","{""Simon mall"":22,""Carl's Jr."":18,""Old Navy"":15...","{""Simon mall"":64,""Starbucks"":22,""Nike"":16,""Ros...","{""android"":42,""ios"":24}",1
237,207769166,sg:d5f35ba8331a4fca91f60fe3493b1886,Boba N More,4061 Camino de la Plz Ste K102,San Diego,CA,92173,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,2,1,1,1,0,2,0,0,1,0,0...",060730100091,"{""US"":21,""MX"":15,""TR"":4}",13256,21.0,"{""<5"":2,""5-20"":17,""21-60"":20,""61-240"":2,"">240"":0}","{""7-Eleven"":100,""Simon mall"":99,""DixieLine"":25...","{""Simon mall"":99,""Starbucks"":23,""Nike"":19,""McD...","{""android"":19,""ios"":14}",1
236,207074079,sg:9d2b9445a5dd4104a95323561dde320b,JC Power Audio Shop,464 W Calle Primera Ste 800,San Ysidro,CA,92173,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,1,0,2,0,0,0,0,0...",060730100093,"{""US"":23,""MX"":10}",14089,22.0,"{""<5"":1,""5-20"":15,""21-60"":14,""61-240"":3,"">240"":0}","{""Love's Travel Stops and Country Stores"":28,""...","{""Walmart"":47,""ARCO"":21,""Ross Stores"":20,""Simo...","{""android"":25,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,126668,sg:f792188b6a8a499b9173a2cbb165c3b6,SpeeDee Oil Change & Auto Service,7207 University Ave,La Mesa,CA,91942,US,SG_BRAND_94b79668c2f8c48c87809a5e205cbbdf,SpeeDee Oil Change & Auto Service,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730145001,{},0,75.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
626,211456224,sg:0bf3497666a447aa8ebaacb41df31252,Fix Auto Worldwide,7473 El Cajon Blvd,La Mesa,CA,91942,US,SG_BRAND_91f780542205658734272a26f182d806,Fix Auto Worldwide,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730147001,{},0,10.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
600,203643372,sg:776d00d9f7cf47f1b25e346728f9387b,El Cerrito Veterinary Hospital,6911 University Ave,La Mesa,CA,91942,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730145003,{},0,221.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
601,206003513,sg:31d2ce41df504fba8d2e48a042ff00cc,Dream Dinners,5208 Jackson Dr Ste 116,La Mesa,CA,91942,US,SG_BRAND_69d1bb34387e4270,Dream Dinners,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730149021,"{""US"":4}",0,158.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
602,205025789,sg:008f16b84f234e66affa49da3872a411,Leo Hamel K 8 Academy,5300 Jackson Dr Ste A,La Mesa,CA,91942,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730148033,"{""US"":6}",8054,11.0,"{""<5"":1,""5-20"":4,""21-60"":0,""61-240"":1,"">240"":1}","{""Jersey Mike's"":100}","{""Macy's"":33,""In-N-Out Burger"":33,""Al and Ed's...","{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,406159,sg:349cf298ff78439aa78743594d631a86,T-Mobile,1865 S Centre City Pkwy,Escondido,CA,92025,US,SG_BRAND_4b82356db1a8f4a2db26dd5b7e30abba,T-Mobile,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730204032,{},0,351.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
513,144623142,sg:9d91d50dd1ba4ed9a3cd2016ac1fe674,Boot Barn,1106 W Valley Pkwy,Escondido,CA,92025,US,SG_BRAND_07e8ec336a446041019b1f98c594d1e5,Boot Barn,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,3,2,0,1,0,0,0,0...",060730203072,"{""US"":30}",11584,43.0,"{""<5"":1,""5-20"":7,""21-60"":15,""61-240"":12,"">240"":4}","{""Chuck E. Cheese's"":33,""The Home Depot"":16}","{""Target"":26,""In-N-Out Burger"":19,""McDonald's""...","{""android"":21,""ios"":10}",1
675,191466980,sg:0ffd974dfea94a6ab98afb54361a2ef0,Church of St Timothy,2960 Canyon Rd,Escondido,CA,92025,US,,,...,"[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0...",060730207061,"{""US"":33}",6033,51.0,"{""<5"":0,""5-20"":10,""21-60"":14,""61-240"":20,"">240...","{""Staples"":50,""Chick-fil-A"":48,""DaVita"":17,""On...","{""Starbucks"":22,""Costco Wholesale Corp."":22,""T...","{""android"":12,""ios"":17}",1
676,190164368,sg:195b86c5b6704abca501cc87387719be,Manee Thai Massage and Spa,1035 E Grand Ave Ste 102,Escondido,CA,92025,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0...",060730206021,"{""US"":8}",1782,80.5,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":4,"">240"":1}","{""Jersey Mike's"":100,""99 Cents Only Stores"":50...","{""In-N-Out Burger"":37,""Walmart"":37,""Sherwin-Wi...","{""android"":9,""ios"":0}",1
677,191467893,sg:168bd8a7324a4c7dba109e0b0d39d1f9,Bodywork By Barbara,1848 S Escondido Blvd,Escondido,CA,92025,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730207072,{},0,154.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,131270,sg:b38cbab27c5d4314abe8029964497547,Sally Beauty Supply,1830 Marron Rd Ste 127,Carlsbad,CA,92008,US,SG_BRAND_57bdb072ef4ee4c0fcd12ab460b8466f,Sally Beauty Supply,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0...",060730178014,"{""US"":22}",6319,14.0,"{""<5"":0,""5-20"":14,""21-60"":7,""61-240"":1,"">240"":0}","{""lululemon athletica"":50,""Wendy's"":49,""Dollar...","{""Target"":44,""Starbucks"":43,""Vons"":28,""Costco ...","{""android"":4,""ios"":11}",1
595,209242206,sg:45aa281a4bfb48e1a5f17e215004db94,Ooh La La,2969 State St,Carlsbad,CA,92008,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0...",060730179002,"{""US"":5}",7196,20.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":1,"">240"":0}","{""Rubio's Restaurants"":50,""Simon mall"":49}","{""Simon mall"":39,""Burger Lounge"":20,""Holiday I...","{""android"":0,""ios"":4}",1
584,205601832,sg:8f0ca5b3b5fa4a34bd4a4c961d17b1f0,Knights' Smokehouse BBQ,1 Legoland Dr,Carlsbad,CA,92008,US,,,...,"[0,0,0,0,0,0,0,0,0,0,6,7,9,10,9,3,6,1,0,0,0,0,...",060730221001,"{""US"":170,""CA"":4,""BR"":4,""MX"":4}",93916,20.0,"{""<5"":1,""5-20"":114,""21-60"":82,""61-240"":19,"">24...","{""LEGOLAND"":100,""King's Fish House"":6,""Domino'...","{""LEGOLAND"":100,""Starbucks"":19,""Chevron"":13,""M...","{""android"":110,""ios"":75}",1
585,204877748,sg:5fb53527dcf14510ada5400428937b8c,Pedego Electric Bikes Carlsbad,2978 Carlsbad Blvd Ste 130,Carlsbad,CA,92008,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,3,1,1,0,1,0,0,0,0,0...",060730180001,"{""US"":53}",12087,23.0,"{""<5"":3,""5-20"":26,""21-60"":22,""61-240"":11,"">240...","{""Swami's Cafe"":12,""Providence Health & Servic...","{""Starbucks"":23,""Boys & Girls Clubs of America...","{""android"":23,""ios"":29}",1
586,207167124,sg:01bf9aed0c774df1a1c6925ed126d20c,Deconstructed,5814 Van Allen Way,Carlsbad,CA,92008,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0...",060730221001,"{""US"":12}",10431,31.0,"{""<5"":0,""5-20"":6,""21-60"":6,""61-240"":1,"">240"":0}","{""In-N-Out Burger"":100,""Starbucks"":31,""Columbi...","{""Starbucks"":26,""Boys & Girls Clubs of America...","{""android"":4,""ios"":7}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,76225,sg:9bcd8c8a5c4549a29209f5ac00220d99,San Diego Gun Graphics,4855 Ruffner St Ste D2,San Diego,CA,92111,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730085111,"{""US"":6}",25190,31.5,"{""<5"":0,""5-20"":1,""21-60"":4,""61-240"":1,"">240"":0}","{""Marshalls"":100,""KFC"":33}","{""24 Hour Fitness"":33,""ARCO"":33,""Rite Aid"":33,...","{""android"":4,""ios"":4}",1
716,205604601,sg:0b56ed9a3e6d42159418cf94f8f22d4b,CrossFit,7440 Ronson Rd,San Diego,CA,92111,US,SG_BRAND_ae6abf1aa02c01cfe560b9315db66b07,CrossFit,...,"[0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0...",060730085111,"{""US"":11}",23589,62.5,"{""<5"":0,""5-20"":5,""21-60"":7,""61-240"":16,"">240"":0}","{""Burger Lounge"":25,""Food 4 Less"":25,""In-N-Out...","{""7-Eleven"":25,""Costco Wholesale Corp."":25,""St...","{""android"":6,""ios"":8}",1
702,200066555,sg:ddb9283386c945f79a993ab570b90ecf,Chopstix,4633 Convoy St Ste 101,San Diego,CA,92111,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,1,1,3,0,1,0,1,0,0,1,0...",060730085111,"{""US"":60}",16737,32.5,"{""<5"":0,""5-20"":22,""21-60"":27,""61-240"":10,"">240...","{""Club Pilates"":50,""Costco Wholesale Corp."":28...","{""Costco Wholesale Corp."":22,""Westfield"":20,""S...","{""android"":28,""ios"":33}",1
703,202129109,sg:af6629cd2dd4437a8e4fc01624930c3b,KARAMI Ramen,3860 Convoy St Ste 118,San Diego,CA,92111,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730085111,"{""US"":11}",16719,43.0,"{""<5"":0,""5-20"":2,""21-60"":5,""61-240"":1,"">240"":1}","{""Subway"":49}","{""Food 4 Less"":22,""Vons"":22,""Costco Wholesale ...","{""android"":4,""ios"":4}",1
704,201292963,sg:e37d86fdf9fe4b1cb4f457fa7f50083a,Ab Auto Upholstery,7852 Convoy Ct,San Diego,CA,92111,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730085111,{},0,9.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,862641,sg:f17a4242b4f74396a0ee451cbb6907d8,Rana Mansour DPM,343 E Lexington Ave Ste 101,El Cajon,CA,92020,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730158022,"{""US"":8}",204,102.0,"{""<5"":1,""5-20"":3,""21-60"":1,""61-240"":1,"">240"":4}",{},"{""Chevron"":27,""Hibachi-San"":14,""Bosch Service""...","{""android"":4,""ios"":4}",1
597,194785485,sg:329c1bbb00af4c1caf4756fef8ac64cc,Caldemeyer Cortland S DDS,150 W Madison Ave,El Cajon,CA,92020,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730162022,"{""US"":7}",8137,27.0,"{""<5"":2,""5-20"":1,""21-60"":2,""61-240"":2,"">240"":0}",{},"{""Westfield"":28,""Kaiser Permanente"":28,""Target...","{""android"":4,""ios"":5}",1
586,190742626,sg:4d0c764edf8c44298ccf143c6a92fc8c,BMW of El Cajon,720 El Cajon Blvd,El Cajon,CA,92020,US,SG_BRAND_71913f59e458e026d6609cdb5a7cc53d,BMW,...,"[0,0,1,0,1,1,0,1,2,0,2,2,2,2,1,0,3,2,0,0,0,0,0...",060730160001,"{""US"":74,""MX"":4}",9494,22.0,"{""<5"":5,""5-20"":47,""21-60"":33,""61-240"":26,"">240...","{""Subway"":14,""Starbucks"":11,""Petco"":10,""McDona...","{""Chevron"":16,""Starbucks"":15,""Carl's Jr."":15,""...","{""android"":36,""ios"":51}",1
587,192132465,sg:1565acf2b39a4eb3b9f85e2ecf878717,Neighborhood Healthcare El Cajon,855 E Madison Ave,El Cajon,CA,92020,US,,,...,"[0,1,0,0,0,0,1,3,2,2,3,2,2,3,0,0,4,0,1,0,0,0,0...",060730163012,"{""US"":70,""KW"":4,""MX"":4}",2818,61.5,"{""<5"":0,""5-20"":22,""21-60"":46,""61-240"":50,"">240...","{""Build A Bear Workshop"":11,""Sprint"":6}","{""Starbucks"":16,""7-Eleven"":16,""Target"":15,""Wal...","{""android"":38,""ios"":35}",1
588,193259767,sg:f3c2c776c7ec45729529adb115ef2b4f,Wild Orchid Florist,904 E Washington Ave,El Cajon,CA,92020,US,,,...,"[0,0,0,0,0,1,0,0,1,1,0,1,3,4,3,0,4,1,0,0,1,0,0...",060730157031,"{""US"":81}",3876,22.0,"{""<5"":5,""5-20"":49,""21-60"":41,""61-240"":23,"">240...","{""Chevron"":14,""Walmart"":7,""Ralph Lauren"":7,""Ra...","{""Walmart"":17,""Starbucks"":14,""Jack in the Box""...","{""android"":37,""ios"":47}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,878480,sg:ec1de0ea7bb447788021add542039a22,Pardee Legal Research Center,5998 Alcala Park School of Law,San Diego,CA,92110,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,2,0,0,0,0,0,0...",060730091062,"{""US"":32}",10935,81.5,"{""<5"":0,""5-20"":14,""21-60"":15,""61-240"":45,"">240...",{},"{""Westfield"":19,""Simon mall"":14,""Bloomingdale'...","{""android"":20,""ios"":25}",1
623,218229486,sg:2bf56a04c5494293989076e75ff98ce1,Copley Library,5998 Alcala Park University of San Diego,San Diego,CA,92110,US,,,...,"[0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0...",060730091062,"{""US"":13}",10273,74.5,"{""<5"":0,""5-20"":5,""21-60"":3,""61-240"":5,"">240"":5}","{""BJ's Restaurants"":25,""Mobil"":25}","{""24 Hour Fitness"":23,""Target"":20,""Starbucks"":...","{""android"":4,""ios"":8}",1
597,207071823,sg:9734b85be0b046a38078287b044c3f48,San Diego Rent A Car,1858 San Diego Ave,San Diego,CA,92110,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730065003,{},0,833.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
598,207818439,sg:fe1562942e1b4d11b7b88ebe8dae60c6,Burger King,3747 Rosecrans St,San Diego,CA,92110,US,SG_BRAND_60d8d6d29e2c4b14f4ea1983baefd36e,Burger King,...,"[0,0,0,0,0,0,0,1,0,1,0,0,5,5,1,2,2,1,0,0,0,0,1...",060730065001,"{""US"":101}",17288,12.0,"{""<5"":3,""5-20"":69,""21-60"":33,""61-240"":8,"">240"":4}","{""CVS"":11,""Target"":11,""Shell Oil"":9,""In-N-Out ...","{""7-Eleven"":26,""ARCO"":26,""Starbucks"":24,""McDon...","{""android"":62,""ios"":38}",1
599,208119336,sg:2995b9961d9841d9aa84201b874d37fa,Geppetto's,2754 Calhoun St,San Diego,CA,92110,US,,,...,"[1,0,0,0,0,0,0,0,0,0,1,2,3,5,0,1,2,1,2,0,0,0,0...",060730065002,"{""US"":109,""MX"":4}",103577,22.0,"{""<5"":2,""5-20"":50,""21-60"":48,""61-240"":12,"">240...","{""Westfield"":20,""The Salvation Army"":20,""Valer...","{""Starbucks"":17,""Westfield"":11,""Simon mall"":11...","{""android"":62,""ios"":49}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,92757,sg:25a2fc6668014147a84bf928f61586f5,IMAX,770 Dennery Rd,San Diego,CA,92154,US,SG_BRAND_32c968bb1e341ec64fd75b776fdcc269,IMAX,...,"[0,0,0,0,0,0,1,1,3,0,8,10,26,7,6,11,25,8,18,15...",060730100142,"{""US"":435,""MX"":10}",5598,115.5,"{""<5"":3,""5-20"":67,""21-60"":65,""61-240"":398,"">24...","{""Westfield"":8,""Taco Bell"":8,""Jack in the Box""...","{""Starbucks"":20,""Walmart"":18,""ARCO"":16,""Jack i...","{""android"":217,""ios"":226}",1
404,193243888,sg:0482e0a838c54e71bf5390fd9a718c2f,Blaze International,7560 Bristow Ct Ste A,San Diego,CA,92154,US,,,...,"[0,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730100151,"{""US"":17,""MX"":8}",136316,31.0,"{""<5"":1,""5-20"":8,""21-60"":18,""61-240"":5,"">240"":0}","{""Pilot Flying J"":25,""Janie and Jack"":17,""Resi...","{""76"":12,""ARCO"":12,""Subway"":9,""Mor Furniture f...","{""android"":15,""ios"":11}",1
426,202773552,sg:c114ae3888e14a6e81221d318dad485e,USA Gasoline,1890 Saturn Blvd,San Diego,CA,92154,US,,,...,"[0,1,0,0,0,1,0,0,1,1,0,2,3,2,1,0,5,1,0,2,2,0,0...",060730101031,"{""US"":134,""MX"":23}",4693,10.0,"{""<5"":18,""5-20"":110,""21-60"":33,""61-240"":10,"">2...","{""Walmart"":12,""McDonald's"":8,""Jersey Mike's"":7...","{""Walmart"":16,""Jack in the Box"":15,""ARCO"":14,""...","{""android"":83,""ios"":81}",1
427,203747158,sg:80ce23e27dec4eb9be2a10c27125f1f7,Nieblas Flower's,2985 Coronado Ave,San Diego,CA,92154,US,,,...,"[0,0,0,0,0,0,0,2,0,0,1,0,2,0,0,1,2,0,1,1,0,0,0...",060730101061,"{""US"":63,""MX"":6}",2604,20.0,"{""<5"":2,""5-20"":42,""21-60"":29,""61-240"":7,"">240"":3}","{""99 Cents Only Stores"":12,""McDonald's"":9,""T.J...","{""Jack in the Box"":19,""Walmart"":17,""Costco Who...","{""android"":24,""ios"":44}",1
428,203642418,sg:71b978b23ea84ac6bbd973c1a3a4f2b3,Express Auto Auction,8407 Airway Rd,San Diego,CA,92154,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730100151,"{""US"":4,""MX"":4}",71710,63.0,"{""<5"":1,""5-20"":1,""21-60"":1,""61-240"":2,"">240"":2}",{},"{""Love's Travel Stops and Country Stores"":39,""...","{""android"":0,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,92352,sg:265cf85477f443b486c8fb671ac921c9,Jensen's Foods,955 Catalina Blvd,San Diego,CA,92106,US,SG_BRAND_752a3c58a1ca29,Jensen's Foods,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0...",060730071002,"{""US"":9}",21136,9.0,"{""<5"":0,""5-20"":9,""21-60"":1,""61-240"":3,"">240"":0}","{""AutoZone"":50,""Taco Bell"":49,""Chipotle Mexica...","{""The Coffee Bean & Tea Leaf"":27,""Club Pilates...","{""android"":4,""ios"":6}",1
264,202793586,sg:3af9ec26dae7442888792499ce4bced9,San Diego Sailing Academy,1551 Shelter Island Dr,San Diego,CA,92106,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730071003,"{""US"":12}",12270,16.0,"{""<5"":1,""5-20"":11,""21-60"":2,""61-240"":2,"">240"":4}","{""Motel 6"":100,""Trader Joe's"":14}","{""Wienerschnitzel"":14,""The Habit Burger Grill""...","{""android"":7,""ios"":6}",1
274,208224438,sg:8716b71e479849f0a87f54eda93d6e2f,Aquarius Yacht Services,4918 N Harbor Dr,San Diego,CA,92106,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0...",060730214001,{},0,316.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
273,208661718,sg:7f6f5ddf1ef14b57ae1b9014dd980b12,Strolling for Fitness,Ntc Park Liberty Station Park,San Diego,CA,92106,US,,,...,"[0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0...",060730214001,"{""US"":17}",25474,26.0,"{""<5"":0,""5-20"":7,""21-60"":9,""61-240"":1,"">240"":0}","{""7-Eleven"":100,""Courtyard by Marriott"":50,""Ch...","{""Starbucks"":30,""In-N-Out Burger"":29,""Target"":...","{""android"":6,""ios"":9}",1
272,206832228,sg:c4e90c007e7d46478ad10e1da2bb1e6b,The WestBean Coffee Roasters,2820 Historic Decatur Rd Liberty Public Market,San Diego,CA,92106,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0...",060730214001,"{""US"":23}",24505,46.0,"{""<5"":0,""5-20"":2,""21-60"":11,""61-240"":5,"">240"":1}","{""California Pizza Kitchen"":12}","{""Westfield"":31,""Starbucks"":16,""Chevron"":14,""C...","{""android"":14,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,862591,sg:ef6bd986ef5d442b80e7e11533a497c0,Howard's Refinishing & Upholstery,512 W California Ave,Vista,CA,92083,US,,,...,"[0,0,0,0,1,2,1,1,1,0,1,1,0,1,1,1,1,1,0,0,0,1,0...",060730195012,"{""US"":37}",5151,42.0,"{""<5"":2,""5-20"":31,""21-60"":17,""61-240"":22,"">240...","{""Starbucks"":18,""Vons"":17,""Crunch"":17,""Public ...","{""Target"":14,""99 Cents Only Stores"":13,""Starbu...","{""android"":27,""ios"":14}",1
324,192826893,sg:71efe347dff34ed3a108864f19dff1d9,Olive Avenue RV Resort,713 Olive Ave,Vista,CA,92083,US,,,...,"[1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0...",060730194032,"{""US"":9}",2856,434.0,"{""<5"":0,""5-20"":6,""21-60"":4,""61-240"":1,"">240"":20}","{""Applebee's"":25,""Walmart"":19}","{""Subway"":21,""Camping World"":17,""ARCO"":16,""Uni...","{""android"":7,""ios"":5}",1
354,214252106,sg:0276a14d4f0940ae85114090e83e8d99,Oriental Medical Arts,544 W Vista Way,Vista,CA,92083,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730197022,"{""US"":5}",8489,50.0,"{""<5"":1,""5-20"":2,""21-60"":6,""61-240"":3,"">240"":0}","{""7-Eleven"":50,""CVS"":49}","{""Denny's"":49,""Chevron"":48,""Coco's Bakery Rest...","{""android"":4,""ios"":4}",1
353,214548791,sg:1f420cf31d114587ad149bc68bb56f08,Spicer's Shaggy Dog,1929 W Vista Way Ste G,Vista,CA,92083,US,,,...,"[0,0,0,0,0,0,0,0,2,2,0,0,0,1,2,3,2,3,0,0,0,0,0...",060730185192,"{""US"":61}",7362,22.0,"{""<5"":2,""5-20"":39,""21-60"":22,""61-240"":11,"">240...","{""El Pollo Loco"":15,""76"":15,""Michaels Stores"":...","{""Starbucks"":22,""Costco Wholesale Corp."":11,""A...","{""android"":34,""ios"":22}",1
352,214840272,sg:c5bb5303af5d4ecb9139fc14df34c3e1,Vista Inn,745 W Vista Way,Vista,CA,92083,US,,,...,"[0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0...",060730194062,"{""US"":20}",7181,196.5,"{""<5"":2,""5-20"":14,""21-60"":6,""61-240"":8,"">240"":24}","{""CVS"":12,""Walmart"":10}","{""ARCO"":23,""Chevron"":18,""Denny's"":15,""Jack in ...","{""android"":21,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,881492,sg:f2467e2e88ed4a2d837d26cf4cb26562,Economy Upholstery,3679 Main St,Chula Vista,CA,91911,US,,,...,"[0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,2,0,0,0,0,0,0...",060730133082,"{""US"":22,""MX"":4}",4347,31.5,"{""<5"":2,""5-20"":13,""21-60"":6,""61-240"":8,"">240"":5}","{""AutoZone"":33,""7-Eleven"":33,""Burger King"":16}","{""Chevron"":26,""ARCO"":18,""Costco Wholesale Corp...","{""android"":15,""ios"":4}",1
593,205603523,sg:015893341c0843e09b4574ba3ca96680,McDonald's,1288 Broadway,Chula Vista,CA,91911,US,SG_BRAND_5179b21fc1d50950b99b4eecaa48c614,McDonald's,...,"[0,0,0,0,0,0,0,0,3,2,1,1,2,1,2,2,4,2,0,1,2,2,0...",060730131032,"{""US"":139,""MX"":21}",4182,9.0,"{""<5"":9,""5-20"":133,""21-60"":29,""61-240"":9,"">240...","{""7-Eleven"":14,""Ross Stores"":9,""99 Cents Only ...","{""Walmart"":24,""Jack in the Box"":20,""Starbucks""...","{""android"":105,""ios"":58}",1
582,202771235,sg:bb6c99324a1f4d3795c6626c002ce00e,Great Happiness Chinese Fast Food II,1445 Third Ave Ste C,Chula Vista,CA,91911,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0...",060730132033,"{""US"":5}",98,811.5,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":1,"">240"":10}","{""Chevron Extra Mile"":50}","{""Costco Wholesale Corp."":58,""Chevron Extra Mi...","{""android"":0,""ios"":0}",1
583,202068954,sg:3103bd314d274dcf9096c4d2395dc12f,Stockers Motorcycle,803 Anita St,Chula Vista,CA,91911,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0...",060730132051,"{""US"":4}",19896,50.5,"{""<5"":0,""5-20"":5,""21-60"":10,""61-240"":12,"">240"":1}","{""Builders FirstSource"":50,""O'Reilly Auto Part...","{""CrossFit"":28,""The Home Depot"":26,""Shell Oil""...","{""android"":5,""ios"":0}",1
584,201954671,sg:c2cab89501ce4ec089ffa7650d618840,Harborside State Preschool,681 Naples St,Chula Vista,CA,91911,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730131032,"{""US"":25,""MX"":4}",3962,21.0,"{""<5"":2,""5-20"":19,""21-60"":15,""61-240"":6,"">240"":2}","{""Fuddruckers"":15,""Costco Wholesale Corp."":15,...","{""Walmart"":30,""Ross Stores"":29,""Costco Wholesa...","{""android"":16,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,542045,sg:463d357882ee4f519fba4cdcef27005a,Geppetto's,2670 Via de la Valle Ste 210,Del Mar,CA,92014,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0...",060730173061,"{""US"":10}",10296,24.0,"{""<5"":0,""5-20"":5,""21-60"":2,""61-240"":3,"">240"":1}","{""CVS"":99,""YMCA"":25}","{""Target"":33,""Westfield"":27,""Starbucks"":22,""Pa...","{""android"":4,""ios"":4}",1
183,209151039,sg:4a548a22182f4529981a128c816bbc94,Cafe Del Mar,720 Camino del Mar,Del Mar,CA,92014,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0...",060730172003,"{""US"":7}",1437992,102.0,"{""<5"":0,""5-20"":2,""21-60"":3,""61-240"":4,"">240"":6}","{""Best Western"":100,""The Flame Broiler"":50}","{""Best Western"":43,""Pinkberry"":14,""Unleashed b...","{""android"":4,""ios"":4}",1
169,195761847,sg:7c775a7e88b042418f8f33fdfe322549,Trattoria Ponte Vecchio,2334 Carmel Valley Rd Ste A,Del Mar,CA,92014,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0...",060730083241,"{""US"":16}",7536,72.0,"{""<5"":1,""5-20"":2,""21-60"":5,""61-240"":11,"">240"":1}","{""Z Gallerie"":50,""Discount Tire"":50,""Shell Oil...","{""Starbucks"":36,""Westfield"":29,""Simon mall"":17...","{""android"":5,""ios"":10}",1
170,198466099,sg:b6704aad7e93413fb4440a94a99653bd,Del Mar Antique Show & Sale,2260 Jimmy Durante Blvd,Del Mar,CA,92014,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730172002,"{""US"":25,""MX"":4}",35981,10.0,"{""<5"":4,""5-20"":15,""21-60"":3,""61-240"":3,"">240"":6}","{""Aramark Uniform & Career Apparel"":20,""Hampto...","{""Starbucks"":23,""7-Eleven"":19,""Jack in the Box...","{""android"":13,""ios"":11}",1
171,199604640,sg:d2f00008023649108ae5335fdf218243,Carmel Valley Market Wine & Spirits,2302 Carmel Valley Rd,Del Mar,CA,92014,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083241,"{""US"":6}",15155,7.0,"{""<5"":1,""5-20"":8,""21-60"":1,""61-240"":0,"">240"":1}","{""Jamba"":33,""Domino's Pizza"":25}","{""Souplantation"":18,""Northgate GonzÃ¡lez Marke...","{""android"":7,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,884395,sg:d50511ab8f9448c5bdc1a41c0ff8bcf1,Tri City PET CT,902 Sycamore Ave Ste 120,Vista,CA,92081,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0...",060730200172,"{""US"":17}",6315,92.0,"{""<5"":1,""5-20"":8,""21-60"":3,""61-240"":11,"">240"":6}","{""ARCO"":16}","{""Starbucks"":20,""Quest Diagnostics"":19,""CARQUE...","{""android"":12,""ios"":4}",1
331,196478718,sg:6a6312bcb94e40c8ba7419ffe1bc6ff1,Access Children's Dental Group,1944 Via Ctr,Vista,CA,92081,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730198051,"{""US"":4}",0,17.5,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
344,201950131,sg:4dee482b2ccf4642b30cce4dc8e39d85,Grand Slam Pizza,1910 Shadowridge Dr Ste 101,Vista,CA,92081,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0...",060730198061,"{""US"":16}",4444,52.5,"{""<5"":1,""5-20"":3,""21-60"":6,""61-240"":8,"">240"":2}","{""United Pacific"":50,""Party City"":50,""CVS"":24,...","{""EoS Fitness"":27,""CVS"":18,""Starbucks"":15,""Alb...","{""android"":8,""ios"":7}",1
343,202126772,sg:a64003c461dd4405abf44f2f84af8fc4,Niko's Steak Burgers And Greek Food,2440 S Melrose Dr,Vista,CA,92081,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0...",060730198063,"{""US"":28}",10666,31.0,"{""<5"":1,""5-20"":9,""21-60"":14,""61-240"":2,"">240"":5}","{""Circle K"":50,""Big 5 Sporting Goods"":25,""Phil...","{""Starbucks"":30,""Crunch"":11,""ARCO"":11,""Jack in...","{""android"":19,""ios"":4}",1
342,203446857,sg:5ae8536836bb40daa65657d10770029f,Diamond Body Fitness,2128 Thibodo Ct,Vista,CA,92081,US,,,...,"[0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0...",060730199042,"{""US"":12}",6924,63.5,"{""<5"":1,""5-20"":2,""21-60"":7,""61-240"":12,"">240"":0}","{""CVS"":16,""Walmart"":14}","{""Chevron"":25,""Walmart"":20,""Jack in the Box"":1...","{""android"":8,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,544532,sg:3bb10cfd158e48309cfd17076750f6de,Norco Trailers,8751 Old Castle Rd Ste B,Escondido,CA,92026,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0...",060730191051,"{""US"":21}",14602,9.5,"{""<5"":3,""5-20"":18,""21-60"":3,""61-240"":2,"">240"":0}","{""Tractor Supply Co."":50,""IMAX"":25,""ARCO"":25,""...","{""ARCO"":20,""Costco Wholesale Corp."":18,""Starbu...","{""android"":13,""ios"":8}",1
185,218725801,sg:870d745bb1ce4fc2b3d51e6f82067c12,Ross Stores,334 W El Norte Pkwy,Escondido,CA,92026,US,SG_BRAND_3a1ab671c974b3489458052270d1a69d,Ross Stores,...,"[0,0,0,0,0,0,0,0,0,2,0,0,3,4,2,2,0,1,1,0,0,1,0...",060730203052,"{""US"":149,""MX"":4}",3476,22.0,"{""<5"":3,""5-20"":72,""21-60"":80,""61-240"":14,"">240...","{""ARCO"":13,""Walmart"":13,""Big Lots Stores"":12,""...","{""Starbucks"":27,""Walmart"":18,""99 Cents Only St...","{""android"":84,""ios"":68}",1
171,203745020,sg:9f62c5341af441efb855eab2026cadc8,El Pollo Loco,350 W El Norte Pkwy,Escondido,CA,92026,US,SG_BRAND_721f5ab43639a6dc48805d22d4844f7c,El Pollo Loco,...,"[0,0,0,0,0,0,0,1,0,0,0,0,2,0,2,0,3,1,2,0,1,0,2...",060730203052,"{""US"":85}",4041,10.0,"{""<5"":10,""5-20"":54,""21-60"":20,""61-240"":8,"">240...","{""Starbucks"":12,""Planet Fitness"":10,""Rodeway I...","{""Walmart"":18,""Starbucks"":17,""Ross Stores"":15,...","{""android"":56,""ios"":30}",1
172,204066596,sg:804bede6afd64b0fb985e16ab230f51a,HearUSA,994 W El Norte Pkwy,Escondido,CA,92026,US,SG_BRAND_ced7f7a81b6240249578e83ca76d1e1b,HearUSA,...,"[0,0,0,0,0,0,1,2,0,2,0,1,0,0,0,0,1,1,1,0,1,0,0...",060730203051,"{""US"":47}",2263,21.0,"{""<5"":3,""5-20"":38,""21-60"":22,""61-240"":14,"">240...","{""T.J. Maxx"":33,""76"":25,""Starbucks"":23,""Childr...","{""Vons"":22,""Costco Wholesale Corp."":15,""Target...","{""android"":30,""ios"":16}",1
173,206443229,sg:7c48c3549c914c8d81b5c5d626b23241,Meadows Deli Market,27980 Oak Ranch Rd,Escondido,CA,92026,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,2,0,0,0,0,0...",060730191052,"{""US"":23}",2326,11.0,"{""<5"":2,""5-20"":20,""21-60"":3,""61-240"":5,"">240"":6}","{""Kaiser Permanente"":33,""Walmart"":27,""Target"":...","{""ARCO"":25,""Starbucks"":24,""Jack in the Box"":16...","{""android"":17,""ios"":8}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,878331,sg:e6cf78975c5a4a9cac94c6eec92c6df0,Guitar Lesson Live,609 S Vulcan Ave,Encinitas,CA,92024,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0...",060730175011,"{""US"":19}",19415,29.0,"{""<5"":1,""5-20"":10,""21-60"":9,""61-240"":9,"">240"":0}","{""La Quinta Inns & Suites"":20,""Costco Wholesal...","{""7-Eleven"":19,""Chevron"":18,""Target"":16,""Costc...","{""android"":11,""ios"":6}",1
723,206552706,sg:5000da228da8463f940bf7988274db6f,Encinitas Surfboards,107 N Coast Highway 101,Encinitas,CA,92024,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0...",060730177021,"{""US"":9}",15770,20.0,"{""<5"":1,""5-20"":5,""21-60"":5,""61-240"":0,"">240"":0}","{""Starbucks"":98,""United States Postal Service ...","{""Target"":51,""Starbucks"":50,""Trader Joe's"":27,...","{""android"":4,""ios"":4}",1
729,209372343,sg:2a7f3e4616fc4cf7a4040543f4c7aca5,Freewater School of Supernatural Discipleship,510 S El Camino Real,Encinitas,CA,92024,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730174043,"{""US"":5}",10539,113.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":4,"">240"":0}",{},"{""McDonald's"":42,""Panera Bread"":32,""JW Tumbles...","{""android"":0,""ios"":4}",1
728,209336684,sg:984b72188bff426a9aa7c8440929f754,Sugaring By The Sea,524 2nd St,Encinitas,CA,92024,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730175012,"{""US"":4}",0,14.5,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
727,209230085,sg:c68cedadf7d948a6ab69603b999f9a27,Oak Crest Park,1219 Encinitas Blvd,Encinitas,CA,92024,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,1,1,2,0,2,0...",060730174033,"{""US"":57}",3892,11.0,"{""<5"":3,""5-20"":43,""21-60"":11,""61-240"":9,"">240"":3}","{""JW Tumbles"":33,""See's Candies"":17,""Best West...","{""JW Tumbles"":32,""Starbucks"":23,""Costco Wholes...","{""android"":20,""ios"":35}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,553431,sg:1ec84efe7fa446339b448bd142ca3416,Lonjean Cheveux Studio,9239 Campo Rd Ste A,Spring Valley,CA,91977,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730137011,"{""US"":4}",0,42.5,"{""<5"":0,""5-20"":1,""21-60"":3,""61-240"":1,"">240"":1}","{""Chili's Grill & Bar"":100,""Lexus"":50}","{""Lexus"":20,""dd's DISCOUNTS"":20,""Rodeway Inn"":...","{""android"":0,""ios"":0}",1
295,205311405,sg:9f2d2c7dade74c17945b49f002720170,A1 Smoke Shop,10022 Campo Rd,Spring Valley,CA,91977,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0...",060730136012,"{""US"":30}",5919,23.0,"{""<5"":0,""5-20"":20,""21-60"":16,""61-240"":5,"">240"":5}","{""Things Remembered"":33,""Shell Oil"":24,""7-Elev...","{""Starbucks"":17,""7-Eleven"":13,""Costco Wholesal...","{""android"":23,""ios"":16}",1
293,204429134,sg:ad788d4275684fd68b7d049b441d592f,Best Buy Autos,4001 Citradora Dr,Spring Valley,CA,91977,US,,,...,"[0,0,0,0,0,0,0,0,0,1,2,0,0,1,0,0,1,0,0,0,0,0,0...",060730137012,"{""US"":17}",6209,5.0,"{""<5"":2,""5-20"":18,""21-60"":1,""61-240"":0,"">240"":0}","{""DixieLine"":50,""ARCO"":50,""Costco Wholesale Co...","{""Starbucks"":37,""Costco Wholesale Corp."":24,""W...","{""android"":14,""ios"":4}",1
292,203968667,sg:038d33ae6583404cbfa6e04dfa9bc27d,CubeSmart,9180 Jamacha Rd,Spring Valley,CA,91977,US,SG_BRAND_3609f80e8ab3db987d9be5010a726c20,CubeSmart,...,"[0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1...",060730139071,"{""US"":19}",5331,27.0,"{""<5"":1,""5-20"":11,""21-60"":5,""61-240"":4,"">240"":6}","{""Food 4 Less"":25,""AutoZone"":12,""7-Eleven"":12}","{""Shell Oil"":20,""Jack in the Box"":14,""7-Eleven...","{""android"":12,""ios"":8}",1
291,201760906,sg:7fa2e6b0f32445e2894a7295cea9ba56,Little Caesars,9770 Campo Rd,Spring Valley,CA,91977,US,SG_BRAND_3654ed70612445d52bf3b6f6546d1f23,Little Caesars,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0...",060730136014,"{""US"":33}",3689,11.0,"{""<5"":4,""5-20"":23,""21-60"":6,""61-240"":4,"">240"":0}","{""Shell Oil"":49,""Walmart"":44,""Panda Express"":2...","{""Costco Wholesale Corp."":24,""Albertsons"":20,""...","{""android"":16,""ios"":15}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1051044,sg:5132315d9f554c4ab180e2c5831203cd,Allstate Insurance,9845 Erma Rd Ste 212,San Diego,CA,92131,US,SG_BRAND_5a9e6695c8055aeb6c210e6bfb45d6b5,Allstate Insurance,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730170431,"{""US"":4}",0,30.0,"{""<5"":0,""5-20"":4,""21-60"":3,""61-240"":2,"">240"":2}","{""ARCO"":100,""Carl's Jr."":50,""Domino's Pizza"":50}","{""Jack in the Box"":39,""Goodwill Industries"":39...","{""android"":4,""ios"":0}",1
203,198505910,sg:7d8f703ffb9444c69e8b68b0f23edb53,Saint Gregory The Great Catholic Church,11451 Blue Cypress Dr,San Diego,CA,92131,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0...",060730170441,"{""US"":115}",2505,64.5,"{""<5"":1,""5-20"":21,""21-60"":45,""61-240"":77,"">240...","{""Kohl's"":13,""CKO Kickboxing"":7,""ARCO"":6,""CVS"":6}","{""Costco Wholesale Corp."":17,""Starbucks"":12,""W...","{""android"":43,""ios"":72}",1
210,201950014,sg:4a6f284ffb96414eb4d70d84c1c8da7b,The Place Catering,10785 Pomerado Rd,San Diego,CA,92131,US,,,...,"[0,0,0,0,0,1,1,0,1,1,0,1,0,1,1,0,2,0,0,0,0,0,1...",060730095041,"{""US"":41}",12830,41.5,"{""<5"":0,""5-20"":29,""21-60"":40,""61-240"":30,"">240...","{""99 Cents Only Stores"":33,""Kaiser Permanente""...","{""Chevron"":19,""Westfield"":16,""Shell Oil"":13,""C...","{""android"":22,""ios"":17}",1
209,203216883,sg:3136dab25fc44e66aae02b7bfe88ee6b,C2 Education,9872 Hibert St,San Diego,CA,92131,US,SG_BRAND_150767ecb601d243e0fbc3b423847370,C2 Education,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170226,{},0,210.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
208,202129063,sg:add37ffa553f47839840a736f4da7fa9,Renaissance Village Academy,9988 Hibert St Ste 301,San Diego,CA,92131,US,,,...,"[0,0,0,0,0,0,1,0,1,2,0,1,0,0,3,0,4,0,0,0,0,0,0...",060730170226,"{""US"":19}",4502,100.0,"{""<5"":0,""5-20"":8,""21-60"":19,""61-240"":34,"">240""...","{""The Home Depot"":32,""F45 Training"":10,""Lincol...","{""Vons"":28,""Costco Wholesale Corp."":22,""The Ho...","{""android"":16,""ios"":9}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,699204,sg:c956e38070d2414a812a173ca5e2b1c4,Church of God Escondido,1863 Harmony Grove Rd,Escondido,CA,92029,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203071,"{""US"":6}",14051,12.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":0,"">240"":0}","{""Long John Silver's"":100}","{""Super 8"":40,""76"":40,""Jack in the Box"":39,""7-...","{""android"":4,""ios"":0}",1
264,187936176,sg:96138372acea4d0c825250c4c8b2229c,The Gift Shops at PPH,2185 Citracado Pkwy,Escondido,CA,92029,US,,,...,"[0,2,0,0,2,7,18,19,10,9,18,9,16,15,12,4,45,8,1...",060730203072,"{""US"":610}",16823,146.5,"{""<5"":17,""5-20"":153,""21-60"":233,""61-240"":510,""...","{""In-N-Out Burger"":5}","{""Starbucks"":14,""Costco Wholesale Corp."":11,""A...","{""android"":318,""ios"":316}",1
288,202067127,sg:994c4f19979942eca5ae5b464504e1a6,The Men's Wearhouse,1276b Auto Park Way #165 Escondido,Escondido,CA,92029,US,SG_BRAND_c8183f6cce7bf3cc6815bdee54fdf21e,The Men's Wearhouse,...,"[0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,1,0,1,0,0,0,0,0...",060730205001,"{""US"":24}",5324,13.0,"{""<5"":0,""5-20"":19,""21-60"":6,""61-240"":0,"">240"":0}","{""Target"":49,""Long John Silver's"":25,""NAPA Aut...","{""Target"":32,""Chevron"":18,""Starbucks"":15,""T.J....","{""android"":11,""ios"":14}",1
287,200386266,sg:ba8b0391166447a7b925076f1d84f8e7,Del Dios Preserve,9860 Del Dios Hwy,Escondido,CA,92029,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203071,{},0,9.0,"{""<5"":1,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
286,201518544,sg:8f1c4eaaa2674b038ad5754e70f08929,SOS Entertainment,1040 S Andreasen Dr,Escondido,CA,92029,US,,,...,"[0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203072,"{""US"":10}",42671,52.5,"{""<5"":1,""5-20"":5,""21-60"":1,""61-240"":3,"">240"":4}","{""Pilot Flying J"":33,""Volkswagen"":25,""24 Hour ...","{""Love's Travel Stops and Country Stores"":19,""...","{""android"":8,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,699152,sg:c0c3df6eab384aed9de24e79eda9cefc,Vista Buggy Bath,1759 E Vista Way,Vista,CA,92084,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730192072,"{""US"":7}",2694,48.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":2,"">240"":0}","{""O'Reilly Auto Parts"":100}","{""Walmart"":27,""Jerome's Furniture"":20,""Northga...","{""android"":6,""ios"":0}",1
330,196465564,sg:31da3ec46cfa4e719b962ef89508a847,Kents Bromeliad,220 Osborne St,Vista,CA,92084,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0...",060730193031,"{""US"":4}",3264,72.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":3,"">240"":0}",{},"{""7-Eleven"":59,""Food 4 Less"":40,""ARCO"":40,""Che...","{""android"":4,""ios"":0}",1
343,207568093,sg:4711e78c5d1c4d2b9869c14ecc593876,Bolanos Earth Works,1777 Knapp Dr,Vista,CA,92084,US,,,...,"[1,0,0,0,0,0,1,0,2,0,1,1,0,1,0,0,4,0,0,0,0,0,0...",060730192051,"{""US"":19}",1902,114.0,"{""<5"":0,""5-20"":8,""21-60"":9,""61-240"":15,"">240"":19}","{""Starbucks"":8}","{""El Pollo Loco"":12,""Boys & Girls Clubs of Ame...","{""android"":14,""ios"":7}",1
342,206275078,sg:318b4b62c36c480f8335dc06896a8702,Children's Paradise School Age,990 Vale Terrace Dr,Vista,CA,92084,US,,,...,"[0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0...",060730196011,"{""US"":6}",4996,237.5,"{""<5"":1,""5-20"":0,""21-60"":0,""61-240"":11,"">240"":10}",{},"{""76"":33,""Costco Wholesale Corp."":31,""Starbuck...","{""android"":7,""ios"":0}",1
341,204589434,sg:56ab4eba7c1849c4bb17259f75a3db04,Corky's Refinishing & Antique,2512 S Santa Fe Ave,Vista,CA,92084,US,,,...,"[1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730199032,"{""US"":8}",6344,17.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":2,"">240"":1}","{""Visiting Angels"":50}","{""Boys & Girls Clubs of America"":28,""The Home ...","{""android"":5,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1377304,sg:3f1683e0f1a745db8046ad9d2d83bf70,Financial 21 Community Credit Union,1069 Graves Ave,El Cajon,CA,92021,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730165042,"{""US"":4}",0,26.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":1,"">240"":0}","{""The Home Depot"":99,""California Bank Trust"":33}","{""Boomers! Parks"":40,""Black Angus Steakhouse"":...","{""android"":4,""ios"":4}",1
461,204774650,sg:0e4cdf05616246d7be71f533f8d27a28,Black Angus Steakhouse,1000 Graves Ave,El Cajon,CA,92021,US,SG_BRAND_1b0fd8bddf878868fabfd19d4014fc32,Black Angus Steakhouse,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,1,0,1,0,0,0,0...",060730165042,"{""US"":98}",7237,62.0,"{""<5"":1,""5-20"":27,""21-60"":38,""61-240"":58,"">240...","{""Freshii"":20,""Denny's"":20,""GameStop"":20,""Resi...","{""Starbucks"":25,""Jack in the Box"":20,""7-Eleven...","{""android"":57,""ios"":45}",1
453,203450016,sg:64e05f3a33624b3da7d5bbf702925f90,Ready Set Grow Infant,728 Pepper Dr,El Cajon,CA,92021,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730167011,"{""US"":8}",4079,11.5,"{""<5"":0,""5-20"":11,""21-60"":1,""61-240"":0,"">240"":0}","{""Goodwill Industries"":25,""Dollar Tree"":16}","{""99 Cents Only Stores"":50,""Costco Wholesale C...","{""android"":5,""ios"":4}",1
454,201663115,sg:2c870b9dbddc446da36167a5bd41cda5,Stereo Depot,1149 Broadway,El Cajon,CA,92021,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0...",060730163021,"{""US"":16}",5561,23.0,"{""<5"":2,""5-20"":11,""21-60"":6,""61-240"":5,"">240"":3}","{""HomeGoods"":25,""DixieLine"":20,""Chick-fil-A"":18}","{""Shell Oil"":24,""Starbucks"":23,""Albertsons"":16...","{""android"":10,""ios"":9}",1
455,202414582,sg:e7ea624ebe794465b67f5d67507338dc,China 1968,500 Broadway,El Cajon,CA,92021,US,,,...,"[0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,1,0,0,0,1...",060730165042,"{""US"":23}",1638,35.5,"{""<5"":0,""5-20"":11,""21-60"":5,""61-240"":6,"">240"":2}","{""Whole Foods Market"":33,""Hallmark Cards"":33,""...","{""Food 4 Less"":21,""Walmart"":20,""Chevron"":19,""A...","{""android"":16,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,879268,sg:ecc9ab920d5f4a7ea9ca954820b05462,Angkorian Pikestaff,734 Park Blvd,San Diego,CA,92101,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730052001,"{""US"":26}",13801,90.5,"{""<5"":0,""5-20"":12,""21-60"":3,""61-240"":25,"">240"":6}","{""Five Guys"":100,""Wells Fargo"":20,""Dollar Tree...","{""Grocery Outlet"":23,""Starbucks"":18,""Westfield...","{""android"":16,""ios"":8}",1
1028,198128908,sg:5a5a58b8e92a4c968518e26d1065abb0,SpringHill Suites by Marriott,900 Bayfront Ct,San Diego,CA,92101,US,SG_BRAND_26cd93ab847fa2cd941ad9e3325cd188,SpringHill Suites by Marriott,...,"[1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,3,0,1,0,0,1...",060730054002,"{""US"":43}",734876,733.5,"{""<5"":2,""5-20"":3,""21-60"":5,""61-240"":16,"">240"":64}","{""Jerry's Subs & Pizza"":14,""Burger Lounge"":14,...","{""Residence Inn by Marriott"":44,""Starbucks"":35...","{""android"":20,""ios"":22}",1
1050,204039516,sg:e99ddbfbee2c447ca2fd726f58d33931,Brooklyn Dogs,1200 3rd Ave,San Diego,CA,92101,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0...",060730053003,"{""US"":188,""MX"":4}",17116,55.5,"{""<5"":14,""5-20"":116,""21-60"":76,""61-240"":129,"">...","{""McDonald's"":5}","{""Costco Wholesale Corp."":14,""Target"":14,""West...","{""android"":129,""ios"":64}",1
1049,202774568,sg:ca226828d78746aab02467f44b5c595e,Bar One,1532 India St,San Diego,CA,92101,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730058001,"{""US"":41}",15477,32.0,"{""<5"":3,""5-20"":15,""21-60"":9,""61-240"":20,"">240"":0}","{""Valero Energy"":25,""Homewood Suites by Hilton...","{""Starbucks"":13,""Westfield"":11,""ARCO"":11,""Jack...","{""android"":29,""ios"":14}",1
1048,203216891,sg:315bdd23f2294e769d81cb9441ffec98,Carte Hotel,401 W Ash St,San Diego,CA,92101,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,2,1,5,0,0...",060730054002,"{""US"":32}",210415,526.5,"{""<5"":0,""5-20"":4,""21-60"":9,""61-240"":6,"">240"":29}","{""Curio Collection"":40,""Shell Oil"":19,""Dunkin'...","{""Curio Collection"":49,""Best Western"":13,""Chev...","{""android"":21,""ios"":16}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,336478,sg:9c257bbeb0554e0b9a47a06c69c67a2f,Sambazon Acai Cafe Cardiff,2031 San Elijo Ave,Cardiff by the Sea,CA,92007,US,,,...,"[0,0,0,0,0,0,0,0,0,1,2,1,4,1,1,1,2,1,2,1,0,0,0...",060730174013,"{""US"":84}",9267,22.0,"{""<5"":3,""5-20"":40,""21-60"":38,""61-240"":16,"">240...","{""Target"":12,""Starbucks"":11,""Vons"":11,""Michael...","{""Starbucks"":30,""Vons"":14,""Target"":13,""Costco ...","{""android"":22,""ios"":64}",1
1,2134371,sg:7c637328b57f47e5ade2a6a202741d60,Body Blu,224 Birmingham Dr Ste 1C,Cardiff by the Sea,CA,92007,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730174013,{},0,596.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":3}",{},{},"{""android"":0,""ios"":0}",1
76,232283297,sg:f395ead52625461686aad19c4a2966f1,Encinitas Elks Lodge 2243,1393 Windsor Rd,Cardiff by the Sea,CA,92007,US,,,...,"[0,0,0,0,0,0,0,2,0,0,1,1,0,0,1,0,1,1,2,0,0,0,0...",060730174042,"{""US"":29}",3222,85.5,"{""<5"":1,""5-20"":6,""21-60"":12,""61-240"":26,"">240""...","{""Walmart"":19,""Trader Joe's"":14,""Studio Barr"":...","{""Starbucks"":23,""Costco Wholesale Corp."":23,""B...","{""android"":14,""ios"":17}",1
75,227788201,sg:c1f6651e81e6473f832f2c66dfe84267,Children's Atelier Center,1508 Windsor Rd,Cardiff by the Sea,CA,92007,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730174041,"{""US"":29}",1719,37.5,"{""<5"":1,""5-20"":16,""21-60"":8,""61-240"":11,"">240"":6}","{""LA Fitness"":14,""Pure Barre"":11,""Trader Joe's...","{""Vons"":22,""Sprouts Farmers Market"":16,""Starbu...","{""android"":7,""ios"":23}",1
74,227529733,sg:dabce56305e84e488b39f4c750f2d172,F45 Training Cardiff,2121 Newcastle Ave Ste 101,Cardiff by the Sea,CA,92007,US,,,...,"[0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730174013,"{""US"":6}",22170,20.0,"{""<5"":2,""5-20"":3,""21-60"":0,""61-240"":3,"">240"":1}","{""The Vitamin Shoppe"":100,""Orangetheory Fitnes...","{""In-N-Out Burger"":50,""Starbucks"":33,""YMCA"":24...","{""android"":4,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,336715,sg:a02e678497eb4f0da1cbde02898e1d93,AAHARN National City,801 National City Blvd Ste 105,National City,CA,91950,US,,,...,"[0,0,0,0,0,0,0,0,0,2,1,0,3,0,0,1,3,1,1,0,0,1,0...",060730117004,"{""US"":76}",7725,17.0,"{""<5"":6,""5-20"":53,""21-60"":18,""61-240"":12,"">240...","{""7-Eleven"":10,""Jack in the Box"":10,""Ramada"":8...","{""7-Eleven"":13,""Walmart"":12,""Starbucks"":12,""Ra...","{""android"":68,""ios"":13}",1
547,199151170,sg:0ef5cbbc9ede437baf5cff5d701b4400,SAF Collision Center Inc,420 W 12th St,National City,CA,91950,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730219002,{},0,35.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
537,197723478,sg:af708f66b0ab49c080bdce795eb43df9,Walmart,1200 Highland Ave,National City,CA,91950,US,SG_BRAND_04a8ca7bf49e7ecb4a32451676e929f0,Walmart,...,"[2,1,0,0,1,2,1,4,12,8,17,13,19,19,25,20,24,24,...",060730117003,"{""US"":1241,""MX"":48,""PH"":4}",3827,21.0,"{""<5"":40,""5-20"":714,""21-60"":687,""61-240"":130,""...",{},"{""Westfield"":14,""Jack in the Box"":14,""ARCO"":13...","{""android"":873,""ios"":440}",1
538,196444408,sg:a66ba81009e248a59224401f015f2fa3,GET FIXED Nails and Spa,1615 E Plaza Blvd Ste 103,National City,CA,91950,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730220002,{},0,111.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
539,198734574,sg:7f4a48f8c70c4510a0f2c161401a6552,Tacotorro Taco Shop,640 Highland Ave Ste A,National City,CA,91950,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730118011,"{""US"":5}",3416,14.0,"{""<5"":0,""5-20"":4,""21-60"":3,""61-240"":0,"">240"":0}","{""Chevron Extra Mile"":50}","{""IHOP"":42,""Walmart"":29,""Northgate GonzÃ¡lez M...","{""android"":5,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,543162,sg:3317f987bc0a47ed9ae5d857dde33e96,Spotts Liquor,4195 Fairmount Ave,San Diego,CA,92105,US,,,...,"[0,0,0,0,0,0,0,0,2,1,0,1,2,1,0,1,4,0,0,0,0,1,0...",060730023022,"{""US"":34,""MX"":4}",6662,52.0,"{""<5"":3,""5-20"":16,""21-60"":27,""61-240"":22,"">240...","{""Simon mall"":9,""Costco Wholesale Corp."":7,""CV...","{""7-Eleven"":17,""Costco Wholesale Corp."":17,""99...","{""android"":30,""ios"":10}",1
340,219705876,sg:361b516852304cc7a613c855772f9cd0,Ban Lao Cuisine,4126 University Ave,San Diego,CA,92105,US,,,...,"[0,0,0,0,0,0,1,0,1,0,1,1,0,0,4,0,1,0,0,2,0,0,1...",060730022023,"{""US"":80}",3673,38.0,"{""<5"":4,""5-20"":36,""21-60"":33,""61-240"":15,"">240...","{""Starbucks"":16,""AutoZone"":6,""Dunkin'"":6,""7-El...","{""Starbucks"":16,""Costco Wholesale Corp."":14,""W...","{""android"":54,""ios"":34}",1
338,216979241,sg:fb9603305ac54b109ddeff6ac1f5b1e1,Beach Club Grammar School,2840 39th St Apt 13,San Diego,CA,92105,US,,,...,"[0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0...",060730025011,"{""US"":14}",4177,74.5,"{""<5"":0,""5-20"":8,""21-60"":5,""61-240"":3,"">240"":10}","{""Westfield"":33,""Food 4 Less"":17,""Vons"":17,""99...","{""ARCO"":21,""7-Eleven"":13,""Chevron"":13,""The Hom...","{""android"":11,""ios"":4}",1
337,217614985,sg:0a6bce4dbf8d4befa1696580b9972ee2,R Diaz Trucking,4121 Myrtle Ave,San Diego,CA,92105,US,,,...,"[1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730025013,"{""US"":11}",13989,125.0,"{""<5"":0,""5-20"":4,""21-60"":6,""61-240"":7,"">240"":8}","{""GameStop"":25,""Walgreens"":24,""Shell Oil"":24}","{""Westfield"":19,""7-Eleven"":17,""Subway"":15,""Cha...","{""android"":6,""ios"":6}",1
336,214839265,sg:be4fd173d17345ad84f951fe64f68c3a,Union Bank,1666 Euclid Ave,San Diego,CA,92105,US,SG_BRAND_d635492fdc36f4412e130c3a4fe23a7a,Union Bank,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730034014,{},0,7.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,720001,sg:5f53c7567ab54417bae7be1ef83f7464,Bee &amp Tea,2939 Alta View Dr Ste I,San Diego,CA,92139,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,2,0,0,0,0,0...",060730032093,"{""US"":45}",2583,22.0,"{""<5"":1,""5-20"":20,""21-60"":12,""61-240"":11,"">240...","{""Jack in the Box"":28,""Pure Barre"":25,""Hobby L...","{""McDonald's"":24,""Ralphs"":18,""Jack in the Box""...","{""android"":23,""ios"":19}",1
67,230483208,sg:3d316d73c86f40f093873e6a3ad02c81,United States Postal Service (USPS),2356 Reo Dr,San Diego,CA,92139,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730032021,"{""US"":4}",0,14.5,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
65,221574577,sg:a3ebdf92451e4be8b517e05de229738e,McDonald's,6925 Paradise Valley Rd,San Diego,CA,92139,US,SG_BRAND_5179b21fc1d50950b99b4eecaa48c614,McDonald's,...,"[0,0,2,0,0,0,1,0,0,0,0,2,2,1,0,2,3,2,1,2,0,0,0...",060730032091,"{""US"":142}",1702,10.0,"{""<5"":5,""5-20"":118,""21-60"":22,""61-240"":20,"">24...","{""Jack in the Box"":9,""ARCO"":6,""Olive Garden"":6...","{""Westfield"":23,""Starbucks"":21,""Jack in the Bo...","{""android"":71,""ios"":77}",1
64,220133128,sg:e1c4c89568524702ae4b3c5933a6a373,Fade Factory Barbershop,2360 Reo Dr,San Diego,CA,92139,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730032021,"{""US"":4}",0,112.5,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":4,"">240"":2}",{},{},"{""android"":6,""ios"":0}",1
63,219308614,sg:830bff80a8754ff0a525fe809becbb98,Opalec Board and Care,5638 Plumas St,San Diego,CA,92139,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730032011,{},0,723.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,133749,sg:c2fa82a2ec0f4a2f8be3b6e1048482cc,The Heights Charter,2710 Alpine Blvd Ste E,Alpine,CA,91901,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0...",060730212053,"{""US"":35}",15785,156.0,"{""<5"":0,""5-20"":13,""21-60"":9,""61-240"":17,"">240""...","{""Pizza Hut"":100,""Shell Oil"":24,""Starbucks"":23...","{""Pizza Hut"":99,""Costco Wholesale Corp."":21,""J...","{""android"":14,""ios"":20}",1
97,162363655,sg:c575b4cf26a343edbce680c866213a64,Harris Financial And Insurance Service,1446 Alpine Grove Ln,Alpine,CA,91901,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730212052,"{""US"":5}",12508,11.0,"{""<5"":2,""5-20"":2,""21-60"":0,""61-240"":2,"">240"":1}",{},"{""McDonald's"":59,""Costco Wholesale Corp."":48,""...","{""android"":0,""ios"":4}",1
123,194094747,sg:6637549bba5d4bb8bf808785a52c0771,Viejas Fire Department,19860 Viejas Grade Rd,Alpine,CA,91901,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,2...",060730212021,"{""US"":11}",749,100.5,"{""<5"":0,""5-20"":7,""21-60"":8,""61-240"":23,"">240"":14}","{""HearUSA"":50,""CrossFit"":14}","{""McDonald's"":16,""Wetzel's Pretzels"":15,""Fit4M...","{""android"":5,""ios"":9}",1
124,194320669,sg:0e90f228aaa342cfb9d6aa8038531da7,Fred's Old Fashioned Burgers,2754 Alpine Blvd Ste H,Alpine,CA,91901,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0...",060730212053,"{""US"":26}",3359,18.0,"{""<5"":0,""5-20"":16,""21-60"":7,""61-240"":3,"">240"":1}","{""Ross Stores"":24,""Dollar Tree"":16}","{""Starbucks"":22,""McDonald's"":16,""Albertsons"":1...","{""android"":16,""ios"":8}",1
125,194068125,sg:41381dd830df41bd9cc644561d7de48e,Tommy Hilfiger,Viejas Outlet Center 5003 Willows Road Suite 120,Alpine,CA,91901,US,SG_BRAND_1428e3360a85e36f654fcd0166e3e607,Tommy Hilfiger,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0...",060730212021,"{""US"":9}",36741,30.0,"{""<5"":0,""5-20"":5,""21-60"":3,""61-240"":2,"">240"":1}",{},"{""Walmart"":37,""Starbucks"":25,""Vans"":20,""Wetzel...","{""android"":4,""ios"":5}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1860386,sg:999b5d81232042618826798e818b59cf,Red Ocotillo,721 Avenida Sureste,Borrego Springs,CA,92004,US,,,...,"[0,0,0,0,0,0,1,0,0,1,1,2,2,2,0,0,0,2,0,0,0,0,0...",060730210004,"{""US"":31}",85905,46.0,"{""<5"":1,""5-20"":17,""21-60"":24,""61-240"":17,"">240...","{""HomeGoods"":17,""Westfield"":14,""ampm"":8,""ARCO"":8}","{""ARCO"":14,""United States Postal Service (USPS...","{""android"":16,""ios"":20}",1
49,171983656,sg:eb4fec8b97b04db7a8d89796364f744e,J&T Tire Pros,896 Palm Canyon Dr,Borrego Springs,CA,92004,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0...",060730210002,"{""US"":4}",0,7.0,"{""<5"":1,""5-20"":1,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
56,197290109,sg:a05983d35bbe4c42896b018b12dc88e8,Oxford Preparatory Academy,2281 Diegueno Rd,Borrego Springs,CA,92004,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730210002,"{""US"":18}",36188,116.0,"{""<5"":0,""5-20"":4,""21-60"":15,""61-240"":31,"">240"":7}","{""Boys & Girls Clubs of America"":14,""ARCO"":11,...","{""Costco Wholesale Corp."":20,""Boys & Girls Clu...","{""android"":4,""ios"":10}",1
55,189027803,sg:000ce943308d4664a693e7ff1aaaac86,Frugal Coyote Boutique & Resale Shop,590 Palm Canyon Dr Ste 105 7 106,Borrego Springs,CA,92004,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,2,1,0,1,0,0,0,1,0,0,0...",060730210002,"{""US"":66}",62245,22.0,"{""<5"":4,""5-20"":39,""21-60"":27,""61-240"":20,"">240...","{""ARCO"":12,""Chevron"":8,""ampm"":6,""CVS"":5,""Unite...","{""United States Postal Service (USPS)"":13,""Cos...","{""android"":38,""ios"":22}",1
54,191058814,sg:57745d7abf5849a79fef2cf97ec50987,Borrego Springs Sculptures,Borrego Springs Rd,Borrego Springs,CA,92004,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730210002,"{""US"":13}",91691,7.0,"{""<5"":1,""5-20"":9,""21-60"":3,""61-240"":1,"">240"":1}",{},"{""Circle K"":20,""Starbucks"":17,""Vons"":14,""WinCo...","{""android"":10,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,881637,sg:f6f3c1dd6458439a8c28c491a4a76a5a,Tuesday Morning,1772 Garnet Ave,San Diego,CA,92109,US,SG_BRAND_399141eb2c47ee5b45c6102be34b9073,Tuesday Morning,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730079032,"{""US"":5}",3230,20.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":1,"">240"":1}","{""Vons"":50,""99 Cents Only Stores"":50,""Michaels...","{""99 Cents Only Stores"":28,""Big Lots Stores"":2...","{""android"":0,""ios"":4}",1
674,229489006,sg:283dc2cd40d74ac2b55a9e5dcdfd8d88,Mission Boulevard Dental Group,4707 Mission Blvd,San Diego,CA,92109,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730079051,"{""US"":4}",0,57.5,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":2,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
592,201370807,sg:cfa5942ad22d4e8a8b2dc5b4f97e319e,ASL Remodeling,715 Santa Barbara Pl,San Diego,CA,92109,US,,,...,"[0,0,0,0,0,0,0,0,3,3,0,0,0,0,1,2,1,1,4,1,2,0,0...",060730076002,"{""US"":43}",26518,92.0,"{""<5"":0,""5-20"":23,""21-60"":17,""61-240"":19,"">240...","{""Denny's"":15,""uBreakiFix"":12,""United Pacific""...","{""Starbucks"":16,""Target"":14,""Vons"":13,""Costco ...","{""android"":17,""ios"":27}",1
593,202502579,sg:dbb92d06fe974c48b60c21ad8663f431,Koffee Kat,1344 Garnet Ave,San Diego,CA,92109,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0...",060730079033,"{""US"":4}",0,62.0,"{""<5"":2,""5-20"":0,""21-60"":4,""61-240"":2,"">240"":5}",{},{},"{""android"":0,""ios"":0}",1
594,202424260,sg:1b4a04d553114ccdb7fe57e160ccfb22,Beach Treats,3105 Ocean Front Walk,San Diego,CA,92109,US,,,...,"[0,0,0,0,0,0,1,0,0,1,0,0,3,1,1,0,1,1,2,0,0,1,0...",060730076002,"{""US"":85}",39881,41.0,"{""<5"":3,""5-20"":24,""21-60"":35,""61-240"":30,"">240...","{""Wings N' Things"":10,""Jamba"":10,""CVS"":9,""Chic...","{""Starbucks"":24,""7-Eleven"":16,""In-N-Out Burger...","{""android"":41,""ios"":48}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1861517,sg:a5a7dcfed023455c8f85b9f5f5878c73,UpTop Moving &amp Storage,420 N Twin Oaks Valley Rd,San Marcos,CA,92069,US,,,...,"[0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0...",060730200212,"{""US"":21}",2606,20.0,"{""<5"":0,""5-20"":14,""21-60"":2,""61-240"":5,"">240"":5}","{""The Old Spaghetti Factory"":33,""United States...","{""United States Postal Service (USPS)"":27,""Che...","{""android"":13,""ios"":7}",1
367,196893894,sg:2442ed97733d4e7a9a247abe78196867,Kent's Bromeliad,2064 Marilyn Ln,San Marcos,CA,92069,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0...",060730203044,"{""US"":5}",0,154.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":11,"">240"":5}",{},{},"{""android"":0,""ios"":0}",1
361,194093631,sg:5a9cde33343b4be587464c8b7213e9d4,Project Athlete,370 Mulberry Dr Ste C,San Marcos,CA,92069,US,,,...,"[0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0...",060730200231,"{""US"":34}",8067,32.0,"{""<5"":4,""5-20"":22,""21-60"":21,""61-240"":19,"">240...","{""T.J. Maxx"":24,""Big Lots Stores"":20,""Pizza Hu...","{""McDonald's"":17,""Starbucks"":17,""Shell Oil"":16...","{""android"":18,""ios"":19}",1
362,194648919,sg:e6c83b0dc7ea432590d492a34a49271c,Mark Cafagna Cafagna Chiropractic,100 N Rancho Santa Fe Rd Ste 129,San Marcos,CA,92069,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730200182,,0,8.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
363,197313119,sg:df5a341fb6c84a89a91864671dc831ab,Sunbelt Rentals,615 E Mission Rd,San Marcos,CA,92069,US,SG_BRAND_e041f2b64a1e73aa7c891441509f3655,Sunbelt Rentals,...,"[0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0...",060730200231,{},0,12.0,"{""<5"":2,""5-20"":4,""21-60"":2,""61-240"":2,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1024175,sg:516703d95d2c4106a258b539db9a6475,Staples,1880 Camino de la Reina,San Diego,CA,92108,US,SG_BRAND_a4d18fc84a927940d1294e253001ce3d,Staples,...,"[0,0,0,0,0,0,0,1,0,0,0,3,5,1,2,1,0,1,1,0,0,0,0...",060730093042,"{""US"":82}",7733,20.0,"{""<5"":0,""5-20"":55,""21-60"":34,""61-240"":4,"">240"":4}","{""Westfield"":31,""Simon mall"":19,""Costco Wholes...","{""Westfield"":41,""Target"":20,""Starbucks"":19,""Co...","{""android"":50,""ios"":38}",1
549,196207752,sg:700222669d8a4c62a7a9ecc2da8b25c8,SAS San Antonio Shoemakers,8440 Rio San Diego Dr,San Diego,CA,92108,US,SG_BRAND_283961e6f8b40ca97ae164161197126c,SAS San Antonio Shoemakers,...,"[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0...",060730093043,"{""US"":7}",6140,13.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":2,"">240"":0}","{""Lazy Dog Restaurant & Bar"":50,""Starbucks"":31}","{""Vons"":37,""Westfield"":37,""Navy Exchange"":25,""...","{""android"":4,""ios"":4}",1
539,194355650,sg:892ebc2470984fa69d02825840bcaea7,Stella Moving & Delivery,7575 Mission Valley Rd,San Diego,CA,92108,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730087022,"{""US"":7}",20918,119.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":7,"">240"":4}","{""7-Eleven"":50}","{""7-Eleven"":36,""Costco Wholesale Corp."":35,""Fo...","{""android"":4,""ios"":5}",1
540,193933516,sg:d0ef1e7ba1b742d68c55f3fe6db56b23,Gehegan & Associates,5423 Caminito Borde,San Diego,CA,92108,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0...",060730020012,"{""US"":8}",23900,41.0,"{""<5"":0,""5-20"":4,""21-60"":4,""61-240"":1,"">240"":2}","{""McDonald's"":47,""Big 5 Sporting Goods"":33,""Ba...","{""ARCO"":37,""The Flame Broiler"":25,""Corner Bake...","{""android"":4,""ios"":7}",1
541,195511255,sg:d8319835ea8941e383a8fd2036948aac,John C Johnston DC,8885 Rio San Diego Dr Ste 345,San Diego,CA,92108,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0...",060730093042,"{""US"":5}",10609,102.5,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":5,"">240"":2}",{},"{""Royal Bank"":17,""EagleRider"":17,""Northgate Go...","{""android"":9,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,664937,sg:cece981633f2435882f85118fbe69cbe,Iowa Street,400 W Elder St,Fallbrook,CA,92028,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730189041,"{""US"":14}",2670,13.0,"{""<5"":1,""5-20"":21,""21-60"":7,""61-240"":6,"">240"":0}","{""Starbucks"":98,""T.J. Maxx"":49,""Anytime Fitnes...","{""Anytime Fitness"":39,""CVS"":24,""Starbucks"":22,...","{""android"":12,""ios"":0}",1
357,205276413,sg:7e90032b8975404b9b4e15734e7b354b,Fallbrook Towne Center,1113 S Mission Rd,Fallbrook,CA,92028,US,,,...,"[0,0,1,0,0,0,5,7,9,11,10,27,15,13,14,16,22,12,...",060730189051,"{""US"":902}",5076,14.0,"{""<5"":78,""5-20"":853,""21-60"":324,""61-240"":137,""...","{""Starbucks"":35,""Albertsons"":22,""Carl's Jr."":1...","{""Starbucks"":37,""Albertsons"":26,""Carl's Jr."":1...","{""android"":519,""ios"":398}",1
355,204472090,sg:25878c0096a8468fb2f4f6197d669634,Straight Nutrition,210 S Vine St Ste 200,Fallbrook,CA,92028,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730189042,{},0,35.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
354,206103936,sg:f36de3e714c3400b8e88544fdb22c100,Phyllis Encouragement Factor,142 Bluebird Park Rd,Fallbrook,CA,92028,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730189033,"{""US"":4}",1513,76.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":3,"">240"":2}",{},"{""ARCO"":33,""Anytime Fitness"":33,""Denny's"":33,""...","{""android"":4,""ios"":0}",1
353,203771615,sg:ddf1b97d3c014acc8c3317c36f56369f,Aydee's Garnacheria,110 E Mission Rd,Fallbrook,CA,92028,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0...",060730189033,"{""US"":20}",1959,20.0,"{""<5"":0,""5-20"":12,""21-60"":7,""61-240"":1,"">240"":3}","{""Starbucks"":31,""Ross Stores"":24,""Yoga Six"":17}","{""Northgate GonzÃ¡lez Markets"":19,""Albertsons""...","{""android"":12,""ios"":7}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1365468,sg:f05b777de0894998ad5a9e9b2c29def6,Undisputed Autowerks,10965 Hartley Rd Ste V,Santee,CA,92071,US,,,...,"[0,0,0,0,0,0,0,1,2,1,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730166071,"{""US"":13}",12900,31.0,"{""<5"":2,""5-20"":11,""21-60"":3,""61-240"":4,"">240"":7}","{""Builders FirstSource"":20,""CrossFit"":20,""7-El...","{""CrossFit"":18,""Walmart"":18,""7-Eleven"":17,""Dix...","{""android"":8,""ios"":7}",1
398,203189128,sg:8c53ab204e7d4b27af7f1c1b59f38e90,Brinegar Chiropractic,8760 Cuyamaca St Ste 203,Santee,CA,92071,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730166161,"{""US"":5}",5090,160.5,"{""<5"":0,""5-20"":0,""21-60"":3,""61-240"":6,"">240"":3}",{},"{""The Home Depot"":31,""Chick-fil-A"":30,""Union B...","{""android"":4,""ios"":4}",1
400,205172864,sg:c7dd2d5bd01547f3b90d2221423b82aa,CPR of San Diego,9406 Pennywood Rd,Santee,CA,92071,US,,,...,"[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0...",060730166123,"{""US"":4}",118,109.0,"{""<5"":0,""5-20"":4,""21-60"":2,""61-240"":5,"">240"":6}","{""Chuze Fitness"":50,""Sprouts Farmers Market"":25}","{""Sprouts Farmers Market"":33,""Brigatine Seafoo...","{""android"":4,""ios"":7}",1
401,205951483,sg:91ebf4f29c134749a545b24a7a3dd023,Lakes Market & Deli,9292 Carlton Hills Blvd,Santee,CA,92071,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0...",060730166061,"{""US"":25}",7052,13.0,"{""<5"":0,""5-20"":20,""21-60"":8,""61-240"":4,"">240"":3}","{""F45 Training"":33,""Denny's"":33,""Jack in the B...","{""7-Eleven"":32,""Food 4 Less"":22,""Vons"":22,""ARC...","{""android"":18,""ios"":6}",1
402,203964288,sg:005a630aa13b445da729d4893631b7e8,The Lean Bean,9161 Mission Gorge Rd,Santee,CA,92071,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730166161,"{""US"":17}",5985,9.0,"{""<5"":0,""5-20"":12,""21-60"":2,""61-240"":2,"">240"":0}","{""BlueLine Rental"":50}","{""Starbucks"":26,""7-Eleven"":17,""Subway"":15,""Sma...","{""android"":9,""ios"":7}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1084837,sg:79af59ac0cc84cc79dda31cb1f28222c,United Pacific,3252 University Ave,San Diego,CA,92104,US,SG_BRAND_25ac38f4c45a0186b72a542922ce11ca,United Pacific,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730016004,"{""US"":9}",3379,52.5,"{""<5"":0,""5-20"":7,""21-60"":4,""61-240"":2,"">240"":5}","{""Einstein Brothers"":100,""Smart & Final"":50}","{""76"":50,""Westfield"":16,""ARCO"":16,""Jack in the...","{""android"":7,""ios"":4}",1
289,156315452,sg:fbb65b0e81a24e4c9f079ba767208fca,North Park Family Health Center,3544 30th St,San Diego,CA,92104,US,,,...,"[0,0,0,0,0,0,0,1,3,0,0,0,0,2,0,0,3,0,0,0,0,0,0...",060730014002,"{""US"":36}",7996,80.0,"{""<5"":0,""5-20"":9,""21-60"":13,""61-240"":21,"">240""...","{""Mrs. Fields Gifts"":29,""Denny's"":14,""Smart & ...","{""Vons"":17,""Westfield"":16,""Target"":16,""Simon m...","{""android"":23,""ios"":11}",1
381,210862605,sg:b4d718bbc90f43fc8e27959c6dfbe2eb,Caffe Calabria,3933 30th St,San Diego,CA,92104,US,,,...,"[0,0,0,0,0,1,0,0,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730013002,"{""US"":50,""MX"":4}",8617,72.0,"{""<5"":2,""5-20"":8,""21-60"":20,""61-240"":28,"">240"":7}","{""Walmart"":19,""REI"":6,""Smart & Final"":6,""ARCO"":6}","{""Vons"":9,""Costco Wholesale Corp."":7,""Ross Sto...","{""android"":28,""ios"":28}",1
382,209553808,sg:cdfe7c9768a84c8181fd6ec37158323b,H L Beauty,3387 El Cajon Blvd,San Diego,CA,92104,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730016002,{},0,26.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
383,210571519,sg:97f3253370334a1a8d9539af9deab5b6,King Music,3327 28th St,San Diego,CA,92104,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0...",060730043001,"{""US"":19}",7350,25.5,"{""<5"":1,""5-20"":10,""21-60"":6,""61-240"":5,"">240"":6}","{""CrossFit"":25}","{""Sprouts Farmers Market"":19,""Ralphs"":14,""The ...","{""android"":11,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,126671,sg:f79ca2f438b846bd916a7aa5bce2cc3e,Ftd,8181 Mission Gorge Rd,San Diego,CA,92120,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0...",060730097042,"{""US"":36}",9191,37.0,"{""<5"":5,""5-20"":18,""21-60"":8,""61-240"":17,"">240"":3}","{""Denny's"":33,""Starbucks"":31,""Trader Joe's"":29...","{""Costco Wholesale Corp."":22,""Starbucks"":22,""J...","{""android"":27,""ios"":12}",1
291,202774497,sg:c795b7f81e934e228903cdf95dbfacfa,San Diego Combat Academy,6008 Mission Gorge Rd,San Diego,CA,92120,US,,,...,"[1,0,0,0,0,0,0,0,0,1,0,0,2,0,1,0,0,0,0,0,0,0,0...",060730096044,"{""US"":13}",16083,29.0,"{""<5"":0,""5-20"":12,""21-60"":8,""61-240"":6,"">240"":3}","{""The Home Depot"":49,""GUESS"":25,""Hilton Garden...","{""Jack in the Box"":43,""7-Eleven"":30,""Costco Wh...","{""android"":17,""ios"":4}",1
289,197837527,sg:6dc6df339a7b4efaa3405b6e4c3d4cad,Davison Distributions,6850 Mission Gorge Rd,San Diego,CA,92120,US,,,...,"[0,0,1,0,0,1,2,2,0,1,2,2,0,0,2,1,3,1,0,1,0,4,1...",060730095091,"{""US"":80}",5904,51.5,"{""<5"":2,""5-20"":52,""21-60"":38,""61-240"":32,"">240...","{""A-1 Self Storage"":7,""ARCO"":6,""Chuze Fitness""...","{""Vons"":10,""Chevron"":9,""Starbucks"":8,""Westfiel...","{""android"":48,""ios"":51}",1
288,198860674,sg:a9bf850675344013ae30278058b31177,Spine Institute of San Diego,6719 Alvarado Rd Ste 308,San Diego,CA,92120,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730029053,{},0,527.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
287,198826607,sg:adbd7002d7be4119958e103f02d89cec,Goodwill Bookstore,6378 Del Cerro Blvd,San Diego,CA,92120,US,,,...,"[0,1,0,0,0,0,0,1,0,0,2,1,3,2,3,0,1,3,1,0,0,0,0...",060730097062,"{""US"":108}",3737,23.0,"{""<5"":2,""5-20"":53,""21-60"":41,""61-240"":22,"">240...","{""Restaurant Depot"":7,""Einstein Brothers"":7,""G...","{""Starbucks"":21,""Costco Wholesale Corp."":17,""C...","{""android"":47,""ios"":54}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,131539,sg:b9a44c57f1a6464baf51c0fdb8f129ee,Hilton Head Park,Hilton Head Park,San Diego,CA,92019,US,,,...,"[0,0,0,0,0,0,0,0,0,2,3,2,1,2,3,1,5,1,1,2,2,2,0...",060730136044,"{""US"":125}",5804,56.0,"{""<5"":2,""5-20"":62,""21-60"":69,""61-240"":80,"">240...","{""Starbucks"":7,""Target"":7,""Food 4 Less"":6}","{""Starbucks"":15,""Jack in the Box"":10,""Chevron""...","{""android"":64,""ios"":69}",1
177,161530653,sg:527db4599f554a44a50ee212d9da19ae,Healthy Pet Pantry,778 Jamacha Rd,El Cajon,CA,92019,US,,,...,"[0,0,0,0,0,0,0,0,0,2,1,1,0,2,1,0,0,3,0,0,0,0,0...",060730154044,"{""US"":97}",2373,17.5,"{""<5"":6,""5-20"":66,""21-60"":32,""61-240"":16,"">240...","{""HermÃ¨s"":10,""Bosch Service"":8,""Crunch"":8,""Ci...","{""Walmart"":17,""Costco Wholesale Corp."":15,""ARC...","{""android"":60,""ios"":43}",1
241,210189094,sg:939696fa70bf4129b68d3f7f80566a09,Monette Tree Service,974 Harbison Canyon Rd,El Cajon,CA,92019,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730155021,{},0,13.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":7,""ios"":0}",1
240,210591923,sg:027ca48b17b34128ac215737672ec369,CA Clothing,2504 Jamacha Stea,El Cajon,CA,92019,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0...",060730136064,"{""US"":36}",7797,15.5,"{""<5"":1,""5-20"":20,""21-60"":12,""61-240"":1,"">240"":0}","{""Denny's"":33,""Starbucks"":31,""Panda Express"":2...","{""Starbucks"":36,""Costco Wholesale Corp."":19,""T...","{""android"":16,""ios"":16}",1
239,209781792,sg:55166428c1f145e0a9850cdbdc8aab98,Shell Oil,785 Jamacha Rd,El Cajon,CA,92019,US,SG_BRAND_2591c98b70119fe624898b1e424b5e91,Shell Oil,...,"[0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,0,2,2,0,0,0...",060730156012,"{""US"":53}",2440,6.0,"{""<5"":4,""5-20"":50,""21-60"":2,""61-240"":3,"">240"":0}","{""Honda"":25,""Costco Wholesale Corp."":19,""Mor F...","{""Starbucks"":22,""7-Eleven"":19,""Target"":16,""Cos...","{""android"":27,""ios"":30}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,545581,sg:40c274cbbaf64eb09bf24e4f6a152fb4,KinderCare,11290 Paseo Montanoso,San Diego,CA,92127,US,SG_BRAND_bb687a854c6bcb1,KinderCare,...,"[0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0...",060730170321,"{""US"":9}",3794,22.0,"{""<5"":0,""5-20"":11,""21-60"":3,""61-240"":4,"">240"":6}","{""Staybridge Suites"":50,""Costco Wholesale Corp...","{""Staybridge Suites"":20,""California Pizza Kitc...","{""android"":4,""ios"":5}",1
242,202477559,sg:b2cd00f36318445f9656dd32c0a88698,San Diego Liberal Arts Academy,11255 Redbud Ct,San Diego,CA,92127,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170322,"{""US"":11}",7263,40.0,"{""<5"":0,""5-20"":7,""21-60"":4,""61-240"":2,"">240"":6}",{},"{""Macaroni Grill"":17,""Stater Bros. Markets"":17...","{""android"":8,""ios"":4}",1
251,217434323,sg:48b60360c6364270b937264b492788f3,Team Koch,16611 Dove Canyon Rd,San Diego,CA,92127,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170321,{},0,395.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":4}",1
250,214821364,sg:3fd349ca29a04493b5e61d995fc5e4db,Spreckels Park,Spreckels Park,San Diego,CA,92127,US,,,...,"[0,0,0,0,0,0,0,1,2,1,2,2,4,6,3,3,7,1,0,1,0,0,0...",060730108001,"{""US"":319,""MX"":4}",8211,38.0,"{""<5"":13,""5-20"":188,""21-60"":229,""61-240"":161,""...",{},"{""Panera Bread"":12,""Vons"":12,""Starbucks"":12,""W...","{""android"":113,""ios"":212}",1
249,214697518,sg:e4eaf36d1b864d8faa6a101ccde5c66f,Just Run,17135 Camino del Sur Ste 115,San Diego,CA,92127,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0...",060730170301,"{""US"":26}",3960,9.5,"{""<5"":0,""5-20"":23,""21-60"":4,""61-240"":1,"">240"":0}","{""Stater Bros. Markets"":12,""Domino's Pizza"":12}","{""Target"":32,""McDonald's"":17,""Starbucks"":17,""C...","{""android"":4,""ios"":24}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1845393,sg:ace0be4606f84e329bbd403b05d0576f,Lean and Green Cafe,9868 Scranton Rd Ste 180,San Diego,CA,92121,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,3,1,0,0,0,2,0,0,0,0,0,0...",060730083461,"{""US"":70}",14503,148.0,"{""<5"":0,""5-20"":28,""21-60"":27,""61-240"":52,"">240...","{""Rubio's Restaurants"":25,""Costco Wholesale Co...","{""Costco Wholesale Corp."":14,""Westfield"":13,""V...","{""android"":49,""ios"":22}",1
627,203771705,sg:e15dff571a494bdfba1d3c3e1c93286d,Weebikeshop,8590 Production Ave Ste B,San Diego,CA,92121,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083501,"{""MX"":4}",0,105.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
615,201665485,sg:7a35715359f345e6a5230cd8ff15af03,MRI Scan Group,7580 Trade St,San Diego,CA,92121,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083501,{},0,296.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
616,202746784,sg:5bb566a6570843e2b7c5313372da2154,National Motors,5820 Miramar Rd,San Diego,CA,92121,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730083501,"{""US"":7}",11602,72.0,"{""<5"":0,""5-20"":6,""21-60"":2,""61-240"":9,"">240"":0}","{""Westfield"":100,""Leslie's Swimming Pool Suppl...","{""ARCO"":57,""Starbucks"":52,""Westfield"":43,""Jack...","{""android"":0,""ios"":4}",1
617,202774538,sg:c911a6e0510042979a18a9553e42a05d,Manna Auto Center,7645 Carroll Rd Ste 7,San Diego,CA,92121,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083501,{},0,449.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1846232,sg:af8c94d3e4724068b2f1c389b879e234,San Diego VA Medical Center,3350 La Jolla Village Dr,San Diego,CA,92161,US,,,...,"[0,0,0,0,1,1,5,6,0,3,6,2,2,5,0,2,3,0,4,1,1,0,0...",060730083051,"{""US"":370}",24067,80.0,"{""<5"":11,""5-20"":104,""21-60"":133,""61-240"":194,""...","{""The Home Depot"":9}","{""Costco Wholesale Corp."":10,""Starbucks"":9,""We...","{""android"":264,""ios"":128}",1
1,5543466,sg:6e8f6d627e174bae9f791ed9d9bb447f,San Diego VA Hospital Cafeteria,3350 La Jolla Village Dr Fl 1 San Diego Va Med...,San Diego,CA,92161,US,,,...,"[0,0,0,0,0,2,2,1,0,3,1,0,1,0,1,4,1,1,4,0,1,2,0...",060730083051,"{""US"":197}",28027,18.0,"{""<5"":26,""5-20"":172,""21-60"":75,""61-240"":59,"">2...",{},"{""Starbucks"":11,""Westfield"":8,""Costco Wholesal...","{""android"":152,""ios"":92}",1
2,36583201,sg:6b7e8ca9ebbe4e58bca847260a27289d,Veterans Medical Research Foundation,3350 La Jolla Village Dr Bldg 13,San Diego,CA,92161,US,,,...,"[0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0...",060730083051,"{""US"":49}",26674,88.0,"{""<5"":5,""5-20"":21,""21-60"":23,""61-240"":37,"">240...","{""7-Eleven"":7}","{""Westfield"":15,""The Home Depot"":11,""Ross Stor...","{""android"":27,""ios"":26}",1
3,179208517,sg:43e12f13c4434440a4c54e526ff85cd1,Palm Desert Resuscitation Education San Diego,9500 Gilman Dr,San Diego,CA,92161,US,,,...,"[0,0,0,1,0,0,0,0,1,1,2,0,3,3,1,1,4,1,1,0,0,1,0...",060730083051,"{""US"":520,""TR"":4}",2152,40.0,"{""<5"":12,""5-20"":248,""21-60"":290,""61-240"":254,""...","{""Five Guys"":5,""76"":5,""In-N-Out Burger"":5}","{""Westfield"":16,""Starbucks"":13,""Vons"":6,""In-N-...","{""android"":220,""ios"":302}",1
4,221771950,sg:a2adbbe33064411f8f9e8b57fff91998,Academic Integrity Office,301 University Ctr,San Diego,CA,92161,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0...",060730083051,"{""US"":82}",1525,50.0,"{""<5"":2,""5-20"":30,""21-60"":41,""61-240"":36,"">240...","{""Starbucks"":31,""Westfield"":8}","{""Westfield"":12,""Vons"":9,""Starbucks"":5}","{""android"":42,""ios"":46}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1846333,sg:b2f4db808e8a4f4db072d762713be501,Taqueria,711 University Ave,San Diego,CA,92103,US,,,...,"[1,0,2,0,0,0,1,0,1,0,2,0,3,2,0,1,3,1,0,2,0,1,0...",060730003003,"{""US"":109}",15219,20.0,"{""<5"":9,""5-20"":69,""21-60"":39,""61-240"":23,"">240...","{""Whole Foods Market"":12,""McDonald's"":11,""Star...","{""Starbucks"":19,""Westfield"":18,""Whole Foods Ma...","{""android"":63,""ios"":49}",1
594,202774447,sg:c53326ff3ac546219b0a8e755b7816e8,La Vecindad,3827 5th Ave,San Diego,CA,92103,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0...",060730003002,"{""US"":29}",24737,44.0,"{""<5"":2,""5-20"":7,""21-60"":12,""61-240"":15,"">240"":3}","{""Super 8"":50,""76"":50,""Simon mall"":49,""Pilot F...","{""Westfield"":21,""Starbucks"":17,""Simon mall"":15...","{""android"":22,""ios"":17}",1
583,198427392,sg:f893fe3f58eb4fe29aad2fe94f0dc89f,Micho'z Fresh Lebanese Grill,1459 University Ave,San Diego,CA,92103,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730007002,"{""US"":4}",5909,55.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":1,"">240"":2}",{},"{""The Salvation Army"":33,""GoWireless"":17,""Pari...","{""android"":4,""ios"":4}",1
584,198023213,sg:34770b93403b4abfbbe42b943b04aaad,Body Align Massage,1281 University Ave Ste C,San Diego,CA,92103,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730007001,"{""US"":7}",16856,32.0,"{""<5"":0,""5-20"":1,""21-60"":5,""61-240"":1,"">240"":0}","{""Jamba"":100,""Ramada"":50,""Church's Chicken"":50...","{""Starbucks"":38,""Sprouts Farmers Market"":28,""W...","{""android"":7,""ios"":0}",1
585,199293945,sg:35c0d14f77e84b769ed5b1089485410e,Hookabana Lounge,4215 Park Blvd,San Diego,CA,92103,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730009006,"{""US"":7}",3710,10.0,"{""<5"":0,""5-20"":5,""21-60"":2,""61-240"":1,"">240"":1}",{},"{""Vons"":22,""Westfield"":22,""Walmart"":20,""A-1 Se...","{""android"":9,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,335653,sg:9394c73507444675ac93e25ba7ef4c9d,Famous Footwear,Otay Ranch Town Center 2015 Birch Road,Chula Vista,CA,91915,US,SG_BRAND_b9d5a5d63e4c2cbbd81051ab8ccd109f,Famous Footwear,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0...",060730133141,"{""US"":6}",4553,180.0,"{""<5"":0,""5-20"":3,""21-60"":2,""61-240"":5,"">240"":3}","{""9Round"":100,""Barnes and Noble"":100}","{""See's Candies"":33,""McDonald's"":26,""Barons Ma...","{""android"":4,""ios"":4}",1
144,189479336,sg:255e76221ab446c3ab2b21895e48e6b3,Goodwill Industries,2220 Otay Lakes Rd Ste 501,Chula Vista,CA,91915,US,SG_BRAND_4ca6f6678c8c72c48310ae8b261c9b6e,Goodwill Industries,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0...",060730133111,"{""US"":14}",4392,10.0,"{""<5"":1,""5-20"":11,""21-60"":0,""61-240"":0,"">240"":0}","{""YMCA"":100,""Starbucks"":98}","{""Walmart"":28,""Ralphs"":25,""7-Eleven"":24,""Chevr...","{""android"":6,""ios"":4}",1
146,192129711,sg:58072caac30942cc9864ff6fa6a919a7,Jersey Mike's,2315 Otay Lakes Rd Ste 304,Chula Vista,CA,91915,US,SG_BRAND_2e5e0487913bda7532010357c3b014d8,Jersey Mike's,...,"[0,0,0,0,0,1,1,0,1,0,2,0,1,0,0,0,1,1,0,0,0,0,0...",060730134192,"{""US"":72}",4690,34.0,"{""<5"":2,""5-20"":28,""21-60"":29,""61-240"":18,"">240...","{""Westfield"":20,""GNC (General Nutrition Center...","{""Walmart"":23,""Costco Wholesale Corp."":22,""Wes...","{""android"":38,""ios"":31}",1
147,192084424,sg:270fbd3140c74a57a70f42d746620065,Subway,2015 Birch Rd Spc Otay,Chula Vista,CA,91915,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,2,3,2,2,1,0,0...",060730133141,"{""US"":108,""MX"":4}",3424,40.0,"{""<5"":3,""5-20"":32,""21-60"":59,""61-240"":21,"">240...","{""The Kebab Shop"":13,""Blaze Pizza"":11,""Baskin ...","{""Costco Wholesale Corp."":23,""Walmart"":20,""Che...","{""android"":52,""ios"":58}",1
148,193501662,sg:9ada00839e494d6994f6f169235a4816,Professional Tax Service,2348 Porch Swing St,Chula Vista,CA,91915,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,0,1,0,1,0...",060730133141,"{""US"":17}",633,118.5,"{""<5"":0,""5-20"":14,""21-60"":16,""61-240"":27,"">240...","{""Walmart"":27,""Carl's Jr."":14,""Benihana"":12,""R...","{""Walmart"":17,""WestCoast Hooters"":10,""Westfiel...","{""android"":15,""ios"":7}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1339087,sg:69ac07f4474245ec9523477ee81c7f74,Hawthorne Elementary,4750 Lehrer Dr,San Diego,CA,92117,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,3,0,1,0,0,1,0...",060730085054,"{""US"":34}",4404,109.5,"{""<5"":1,""5-20"":23,""21-60"":22,""61-240"":29,"">240...","{""El Pollo Loco"":14,""Starbucks"":12,""Ralphs"":8,...","{""Starbucks"":25,""Westfield"":16,""Target"":10,""Si...","{""android"":15,""ios"":21}",1
324,187474472,sg:1e6f9591ee3d40f3af58fc5462ebc658,Rose Canyon Animal Hospital,4295 Jutland Dr,San Diego,CA,92117,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0...",060730085031,"{""US"":6}",9568,17.0,"{""<5"":0,""5-20"":7,""21-60"":6,""61-240"":0,"">240"":0}",{},"{""ARCO"":22,""IL Fornaio"":11,""Yoga Six"":11,""Blac...","{""android"":4,""ios"":0}",1
354,208519627,sg:96a44420f26744c48d36c66675b74754,Taco Bell,4290 Clairemont Mesa Blvd,San Diego,CA,92117,US,SG_BRAND_748ba381dd81bb8de615319837ffa350,Taco Bell,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0...",060730085025,"{""US"":23}",3762,11.0,"{""<5"":1,""5-20"":20,""21-60"":3,""61-240"":0,"">240"":0}","{""Croutons"":33,""KFC"":33,""Subway"":27,""99 Cents ...","{""Starbucks"":33,""Westfield"":25,""Subway"":21,""Co...","{""android"":14,""ios"":9}",1
353,207246952,sg:6af7377b72dd4085ba17603fc31c534d,Clairemont Village,3007 Clairemont Dr,San Diego,CA,92117,US,,,...,"[0,0,0,1,1,1,0,5,8,9,16,17,10,11,13,4,22,23,11...",060730091022,"{""US"":657}",4425,23.0,"{""<5"":25,""5-20"":474,""21-60"":255,""61-240"":251,""...","{""Starbucks"":13,""Baskin Robbins"":6,""Carl's Jr....","{""Starbucks"":30,""Westfield"":11,""Yoga Six"":11,""...","{""android"":363,""ios"":315}",1
352,206848741,sg:ba5c4677c2d04c25bebc3962f61a70ed,Easy Fast Cheap Online Traffic School,4901 Morena Blvd # 214 C,San Diego,CA,92117,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0...",060730085012,"{""US"":10}",5153,274.0,"{""<5"":0,""5-20"":4,""21-60"":2,""61-240"":4,"">240"":12}",{},"{""Costco Wholesale Corp."":25,""Subway"":24,""Club...","{""android"":5,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1365629,sg:f5c43c697586428cb328d1eeb613ee7b,Rolling Hills Elementary School Preschool,15255 Penasquitos Dr,San Diego,CA,92129,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170343,"{""US"":33}",4002,18.0,"{""<5"":1,""5-20"":31,""21-60"":5,""61-240"":15,"">240"":2}","{""McDonald's"":47,""Panda Express"":7,""Goodwill I...","{""Costco Wholesale Corp."":26,""In-N-Out Burger""...","{""android"":19,""ios"":17}",1
182,210366705,sg:115120ab808e41a19f5b41aedc3880aa,Jack in the Box,14371 Penasquitos Dr,San Diego,CA,92129,US,SG_BRAND_4941482324b30ad4733c1566b12af9c6,Jack in the Box,...,"[0,0,1,0,0,0,0,0,0,0,1,2,2,3,2,0,0,1,0,0,0,0,0...",060730170181,"{""US"":61,""MX"":4}",5803,12.0,"{""<5"":4,""5-20"":47,""21-60"":11,""61-240"":8,"">240""...","{""Islands Restaurants"":14,""Circle K"":14,""Chevr...","{""Starbucks"":20,""ARCO"":19,""7-Eleven"":16,""McDon...","{""android"":42,""ios"":23}",1
188,216615912,sg:dc198c09699444c8af5d0395af8e3af3,Four Seasons Flowers,13289 Black Mountain Rd Ste 5,San Diego,CA,92129,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730170361,"{""US"":5}",2488,7.0,"{""<5"":0,""5-20"":6,""21-60"":0,""61-240"":0,"">240"":1}",{},"{""Starbucks"":52,""Club Pilates"":28,""Domino's Pi...","{""android"":4,""ios"":4}",1
187,216079839,sg:703e5832f1a64dc48205ae1d1440fb61,CVS,9225 Twin Trails Dr,San Diego,CA,92129,US,SG_BRAND_72f1a850d966375fa159121c7c8b09a1,CVS,...,"[0,0,0,0,0,0,0,0,4,6,1,3,4,2,2,3,3,2,2,1,1,0,0...",060730170361,"{""US"":170}",1958,11.0,"{""<5"":11,""5-20"":130,""21-60"":41,""61-240"":12,"">2...","{""Simon mall"":14,""Residence Inn by Marriott"":9...","{""Costco Wholesale Corp."":25,""Starbucks"":21,""S...","{""android"":85,""ios"":82}",1
186,216202952,sg:7734df96390b4ed3b172fe6682bb21f6,Evans Tire & Service Centers,14365 Penasquitos Dr,San Diego,CA,92129,US,,,...,"[0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,2,0,0,0,0,0,0...",060730170181,"{""US"":10}",6568,111.0,"{""<5"":1,""5-20"":6,""21-60"":6,""61-240"":9,"">240"":9}",{},"{""Jack in the Box"":30,""The Home Depot"":21,""Sta...","{""android"":11,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1376418,sg:321baf5093424cf7b43c358bd06d1857,Rolando Best Appliance Services,6244 El Cajon Blvd,San Diego,CA,92115,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0...",060730029022,"{""US"":15}",2280,17.0,"{""<5"":1,""5-20"":7,""21-60"":4,""61-240"":3,"">240"":0}","{""Cheba Hut"":50,""Rubio's Restaurants"":33,""H&M ...","{""Ralphs"":27,""ARCO"":26,""Westfield"":20,""McDonal...","{""android"":6,""ios"":8}",1
412,195765591,sg:4f0ed6088d4f41e794511c17c59bd082,Duet Coffee,6526 El Cajon Blvd,San Diego,CA,92115,US,,,...,"[0,0,0,0,0,0,0,1,0,1,1,2,1,0,1,0,1,0,0,0,0,0,0...",060730029043,"{""US"":30}",10423,65.0,"{""<5"":1,""5-20"":8,""21-60"":14,""61-240"":17,"">240"":8}","{""Dollar Tree"":12}","{""Costco Wholesale Corp."":13,""7-Eleven"":11,""Tr...","{""android"":19,""ios"":11}",1
405,194495568,sg:d851bba2ef6e4a55bb492d0b389fe3eb,La Mesa TV Supply,7026 El Cajon Blvd,San Diego,CA,92115,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730029052,{},0,10.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
406,192890234,sg:0bcf860105ce4926a024208c84a116ca,Farmers Insurance Group,4792 El Cajon Blvd,San Diego,CA,92115,US,SG_BRAND_ee53498a2846250eb753e44e4042a679,Farmers Insurance Group,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730023011,{},0,372.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
407,193529760,sg:10d77ba172b2436fa6b4bb74d2e7e6ff,Sala Thai,6161 El Cajon Blvd Ste A,San Diego,CA,92115,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,2,0,1,1,0,0,1,0,0,0,1...",060730029022,"{""US"":60}",3102,19.5,"{""<5"":4,""5-20"":33,""21-60"":20,""61-240"":6,"">240"":3}","{""Target"":19,""Kaiser Permanente"":14,""Valero En...","{""Vons"":21,""Target"":16,""Ralphs"":15,""ARCO"":13,""...","{""android"":40,""ios"":20}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1856253,sg:9eebab4a79be47d7b5f0e89539247ad3,Dollar Tree,1853 Main St Ste J,Ramona,CA,92065,US,SG_BRAND_6b1e006c89aa3f8b054a05fa90581501,Dollar Tree,...,"[0,0,0,0,0,0,0,0,0,1,2,2,4,2,1,0,2,0,1,0,0,0,0...",060730208052,"{""US"":106}",3050,11.0,"{""<5"":8,""5-20"":86,""21-60"":19,""61-240"":3,"">240"":2}","{""Circle K"":16,""Kmart"":13,""AMC Entertainment"":...","{""Starbucks"":20,""Albertsons"":17,""Stater Bros. ...","{""android"":76,""ios"":31}",1
249,190172216,sg:c087227232284786bf2b59bbaa8f46a6,Charlie's Garage,402 14th St,Ramona,CA,92065,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730208062,"{""US"":12}",2672,20.0,"{""<5"":0,""5-20"":7,""21-60"":3,""61-240"":2,"">240"":1}","{""Big 5 Sporting Goods"":50,""United States Post...","{""ARCO"":33,""United States Postal Service (USPS...","{""android"":7,""ios"":0}",1
258,194652788,sg:853d857fb8094f99847c4978dc6ea5bc,MDS Diesel Service,453 Main St,Ramona,CA,92065,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730208093,"{""US"":4}",0,73.5,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
257,194387032,sg:c75b5959b9d3453f9370b6b384435d48,B Street Express Car Wash,1017 B St,Ramona,CA,92065,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730208061,{},0,11.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":3,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
256,192526069,sg:dea9288ddca2465d8f91940099b12612,R Town Strength & Wellness,2330 Main St Suites B & C,Ramona,CA,92065,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0...",060730208052,"{""US"":25}",6773,29.5,"{""<5"":2,""5-20"":8,""21-60"":13,""61-240"":7,"">240"":0}","{""Macy's"":25,""CVS"":10,""Target"":10}","{""Starbucks"":25,""Goodwill Industries"":17,""Wend...","{""android"":7,""ios"":19}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,791010,sg:7b64ffdb2f3c41b6857bd6d6ad8d9755,USP Incorporated,1818 Ord Way,Oceanside,CA,92056,US,,,...,"[0,0,0,0,0,0,2,1,2,0,0,0,0,0,0,0,3,1,0,0,0,0,0...",060730194033,"{""US"":14}",8713,141.0,"{""<5"":0,""5-20"":8,""21-60"":12,""61-240"":18,"">240""...",{},"{""Nick's Restaurants"":7,""Dry Goods"":7,""Ruby's ...","{""android"":7,""ios"":5}",1
327,193259849,sg:f6a31d35f81240b3a36804d7323b4aca,The Crimson Cake,3830 Oceanic Dr Ste 411,Oceanside,CA,92056,US,,,...,"[0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730185131,"{""US"":7}",14248,329.0,"{""<5"":1,""5-20"":1,""21-60"":2,""61-240"":1,"">240"":6}",{},"{""McDonald's"":42,""G&M"":17,""L&L Hawaiian Barbec...","{""android"":4,""ios"":4}",1
340,207069540,sg:911fc52beb934d6cb6869bffb5aeb6e6,Starbucks,3702 Plaza Dr # A,Oceanside,CA,92056,US,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,...,"[0,0,0,1,0,0,0,1,1,2,0,4,0,1,4,2,3,1,1,0,0,0,0...",060730198051,"{""US"":132}",4731,10.0,"{""<5"":9,""5-20"":100,""21-60"":25,""61-240"":29,"">24...","{""Target"":14,""Buffalo Wild Wings"":7,""The Home ...","{""Target"":14,""Jack in the Box"":13,""Walmart"":12...","{""android"":58,""ios"":77}",1
339,207068870,sg:2907e78078774c598376f2bfb1ff4168,Kohl's,3410 Marron Rd,Oceanside,CA,92056,US,SG_BRAND_64a77880c7f7c1d3133d10e574c97a8b,Kohl's,...,"[0,0,0,0,0,0,1,0,1,2,2,3,3,7,4,2,3,3,2,1,2,0,0...",060730198033,"{""US"":258}",5466,22.0,"{""<5"":3,""5-20"":123,""21-60"":116,""61-240"":36,"">2...","{""Walmart"":10,""Chick-fil-A"":9,""Starbucks"":6}","{""Starbucks"":19,""Walmart"":18,""Costco Wholesale...","{""android"":128,""ios"":131}",1
338,207038692,sg:650deb3713a4455e9cae1254d6d734f9,Enchanted Elephant Healing,3813 Kelton Dr,Oceanside,CA,92056,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730185161,"{""US"":4}",4176,61.5,"{""<5"":1,""5-20"":1,""21-60"":3,""61-240"":2,"">240"":3}","{""The Home Depot"":32}","{""GameStop"":32,""The Home Depot"":31,""Sears Outl...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1366588,sg:fccb181dc68c4c1ab547f6677d5b56c5,Starbucks,3202 Governor Dr Ste 110,San Diego,CA,92122,US,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,...,"[1,0,0,0,0,0,0,0,2,2,0,0,2,1,1,2,3,2,0,1,0,0,1...",060730083072,"{""US"":101}",2187,10.0,"{""<5"":7,""5-20"":71,""21-60"":26,""61-240"":13,"">240...","{""YMCA"":23,""BJ's Restaurants"":22,""Madewell"":11...","{""Westfield"":32,""Tuesday Morning"":16,""Primos"":...","{""android"":45,""ios"":55}",1
293,203607525,sg:40bd6eb01daf489992c9400173f815f8,Lacoste,4301 La Jolla Village Dr Ste 2015,San Diego,CA,92122,US,SG_BRAND_3f4bcbc1f84f23a51d938bfa86efad94,Lacoste,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083402,"{""US"":6}",0,19.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
304,209105240,sg:638b47a36f9e4f0e8bf1a9f99e5653e9,Oxford auto outlet,7655 Palmilla Dr Apt 4101,San Diego,CA,92122,US,,,...,"[0,0,1,0,0,0,0,1,0,1,1,0,0,0,0,2,4,1,1,3,1,3,1...",060730083633,"{""US"":48}",458,146.0,"{""<5"":1,""5-20"":22,""21-60"":31,""61-240"":38,"">240...","{""Target"":11,""Starbucks"":9,""Philz Coffee"":6,""T...","{""Starbucks"":17,""Westfield"":9,""Vons"":7,""McDona...","{""android"":21,""ios"":28}",1
303,208660645,sg:7591563d47fa4adbabec74681ece7d21,LEGO,4545 La Jolla Village Dr,San Diego,CA,92122,US,SG_BRAND_045ab0f2a6744cab9df05f98d3b0d0af,LEGO,...,"[0,0,0,0,0,0,0,0,0,0,0,2,2,3,1,5,3,1,0,3,1,0,0...",060730083402,"{""US"":85}",10452,21.0,"{""<5"":2,""5-20"":40,""21-60"":39,""61-240"":8,"">240"":0}","{""Westfield"":100,""Marshalls"":25,""Macy's"":17,""W...","{""Westfield"":100,""Starbucks"":20,""Macy's"":13,""V...","{""android"":37,""ios"":50}",1
302,208950210,sg:d8c5f754c5834ca99d96ef9fc0d72d52,SAS Towing,8465 Regents Rd Apt 112,San Diego,CA,92122,US,,,...,"[2,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,4,1,1,0,0,0,0...",060730083431,"{""US"":53,""MX"":4}",2575,129.0,"{""<5"":3,""5-20"":28,""21-60"":17,""61-240"":21,"">240...","{""Macy's"":7,""Vons"":7,""24 Hour Fitness"":7,""F45 ...","{""Westfield"":25,""Vons"":12,""Chevron"":11,""Starbu...","{""android"":28,""ios"":27}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,318201,sg:059ac23abf384f0e8c7941d40156b6a1,Bela Development,1101 Ocean Front St,San Diego,CA,92107,US,,,...,"[0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0...",060730073011,"{""US"":14}",9113,27.5,"{""<5"":0,""5-20"":6,""21-60"":4,""61-240"":0,"">240"":6}",{},"{""Sprouts Farmers Market"":23,""7-Eleven"":22,""So...","{""android"":9,""ios"":4}",1
230,210499962,sg:7fd2c5aab54c47d4920c1fdfdc689d55,AutoZone,1950 Cable St,San Diego,CA,92107,US,SG_BRAND_87681bc51c663efbbf7272e0f1262e9b,AutoZone,...,"[0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,2,0,0,0,0,0,0...",060730075023,"{""US"":19}",2201,11.0,"{""<5"":1,""5-20"":12,""21-60"":8,""61-240"":2,"">240"":0}","{""Days Inn"":20,""Sonic"":19,""The Home Depot"":19}","{""Starbucks"":27,""Jack in the Box"":20,""The Home...","{""android"":10,""ios"":7}",1
228,209034360,sg:faac206530264ee2ad33009484a34c94,San Diego Fire Rescue Department Station 15,4711 Voltaire St,San Diego,CA,92107,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730075012,"{""US"":4}",0,67.0,"{""<5"":0,""5-20"":0,""21-60"":4,""61-240"":3,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
227,209781827,sg:561f432dbb3d493c910592331c1eb6ce,The Black,5017 Newport Ave,San Diego,CA,92107,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,2,0,1,0,0,0,1,0,0,0,0...",060730075022,"{""US"":42,""MX"":4}",27461,21.5,"{""<5"":0,""5-20"":23,""21-60"":24,""61-240"":0,"">240"":3}","{""Del Taco"":20,""Shell Oil"":19,""Eureka!"":17,""IH...","{""Westfield"":19,""Target"":16,""Starbucks"":14,""Co...","{""android"":25,""ios"":19}",1
226,208520635,sg:9fdebb82badd4b8f8ac318c0d1105d31,Poma's Italian Deli,1846 Bacon St,San Diego,CA,92107,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,2,3,0,1,0,0,1,0,0,1,0,0...",060730073012,"{""US"":48}",15460,10.0,"{""<5"":2,""5-20"":31,""21-60"":13,""61-240"":7,"">240"":2}","{""Ralphs"":25,""Westfield"":25,""Wendy's"":24,""Doll...","{""Starbucks"":22,""Westfield"":17,""Ralphs"":15,""Ja...","{""android"":14,""ios"":28}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1158977,sg:16e8d3cbbc824fedb5e0f6544eaca079,MJ's Yogurt Time and Deli,1550 E H St Ste J,Chula Vista,CA,91913,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730134162,"{""US"":16}",6892,13.0,"{""<5"":1,""5-20"":12,""21-60"":3,""61-240"":2,"">240"":0}","{""Jamba"":100,""McDonald's"":97,""Holiday Inn Expr...","{""Taco Bell"":27,""McDonald's"":22,""Starbucks"":19...","{""android"":8,""ios"":10}",1
96,182338531,sg:87ced3b35dac4ae4acd1cc9f73340774,D K Che',1392 E Palomar St,Chula Vista,CA,91913,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1...",060730133102,"{""US"":13,""MX"":4}",2297,181.5,"{""<5"":1,""5-20"":6,""21-60"":2,""61-240"":3,"">240"":8}","{""The Coffee Bean & Tea Leaf"":33,""CVS"":16}","{""Starbucks"":28,""Curves"":20,""Westfield"":20,""Ja...","{""android"":5,""ios"":9}",1
90,173072914,sg:e3e4fb49e61e42c8ae1f0d4ad68dc449,7-Eleven,913 Otay Lakes Rd,Chula Vista,CA,91913,US,SG_BRAND_2e2448f12fc87fe452e9166153797a7f,7-Eleven,...,"[0,0,0,0,0,2,0,0,0,1,1,2,0,0,0,0,1,0,0,0,0,0,0...",060730134162,"{""US"":40,""MX"":4}",3253,6.5,"{""<5"":3,""5-20"":35,""21-60"":8,""61-240"":1,"">240"":1}","{""Victoria's Secret"":50,""Starbucks"":27,""Rite A...","{""Starbucks"":26,""ARCO"":25,""Walmart"":25,""Jack i...","{""android"":28,""ios"":10}",1
91,173360291,sg:cfd3ca907a7340f287a5bb656096c805,Phase 4 Computer Repair,943 Otay Lakes Rd Ste C,Chula Vista,CA,91913,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730134162,"{""US"":11}",2443,35.0,"{""<5"":0,""5-20"":4,""21-60"":5,""61-240"":1,"">240"":4}","{""99 Cents Only Stores"":33,""Michaels Stores"":3...","{""Costco Wholesale Corp."":42,""Simon mall"":32,""...","{""android"":5,""ios"":6}",1
92,175444955,sg:6150b8a7e89644f5bf15a0dd1f3fde44,Chula Vista Heritage Skatepark,1381 E Palomar St,Chula Vista,CA,91913,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730133101,{},0,28.5,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,974655,sg:34826fa6abc64b3fbfab92ed173084c9,Pomerado Manor,16031 Pomerado Rd,Poway,CA,92064,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170061,"{""US"":5}",11283,122.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":3,"">240"":3}",{},"{""Costco Wholesale Corp."":38,""The Home Depot"":...","{""android"":4,""ios"":0}",1
484,185868623,sg:9d2de76b0acc4bb3867ed964b864c4c6,Tio Leo's Cantina,12205 Scripps Poway Pkwy Ste E101,Poway,CA,92064,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170451,"{""US"":48}",6691,46.5,"{""<5"":1,""5-20"":5,""21-60"":28,""61-240"":16,"">240"":0}","{""Unleashed by Petco"":11,""DaVita"":11,""Orangeth...","{""Starbucks"":33,""Courtyard by Marriott"":16,""Co...","{""android"":29,""ios"":17}",1
510,200111422,sg:a55a7dec47194cf78dec65516b0920c8,Starbucks,14823 Pomerado Rd,Poway,CA,92064,US,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,1,0,0,0,0,0...",060730170401,"{""US"":34}",6252,10.0,"{""<5"":1,""5-20"":25,""21-60"":10,""61-240"":2,"">240"":1}","{""Shell Oil"":39,""Pizza Studio"":20,""Albertsons""...","{""Target"":19,""Costco Wholesale Corp."":17,""Cour...","{""android"":21,""ios"":15}",1
511,201225328,sg:2ed446d674544f71b1aaaca2b34c1669,Polo Lessons San Diego,14336 Tierra Bonita Rd,Poway,CA,92064,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170091,"{""US"":4}",0,45.0,"{""<5"":0,""5-20"":8,""21-60"":4,""61-240"":5,"">240"":2}",{},{},"{""android"":4,""ios"":0}",1
512,202298049,sg:4a8c9542967746e1a8986712bd391494,Poway Vision Care,13035 Pomerado Rd Ste C,Poway,CA,92064,US,,,...,"[0,0,0,0,0,0,0,0,1,2,2,0,1,2,0,1,1,0,0,0,0,0,0...",060730170403,"{""US"":21}",8546,47.0,"{""<5"":0,""5-20"":4,""21-60"":11,""61-240"":7,"">240"":1}","{""7-Eleven"":33}","{""Starbucks"":19,""Target"":16,""Costco Wholesale ...","{""android"":9,""ios"":12}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1134858,sg:b6fc6c802c664190807c034c02387e46,La Fachada,20 25th St,San Diego,CA,92102,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730048003,"{""US"":19}",7971,50.0,"{""<5"":1,""5-20"":6,""21-60"":12,""61-240"":5,"">240"":9}","{""Chevron"":19,""Orange Julius"":17,""Subway"":15,""...","{""ARCO"":22,""Shell Oil"":10,""Walmart"":9,""Northga...","{""android"":17,""ios"":5}",1
273,207137933,sg:15927335cecb4994a361d1a3f5a63181,Foundation Building Materials (FBM),4567 Federal Blvd,San Diego,CA,92102,US,SG_BRAND_956a1e0bbb3deda859969a4d1e04125f,Foundation Building Materials (FBM),...,"[0,0,0,1,0,0,4,1,2,0,0,1,1,0,0,0,0,0,0,0,0,0,0...",060730034012,"{""US"":13}",15940,17.0,"{""<5"":3,""5-20"":16,""21-60"":6,""61-240"":0,"">240"":5}","{""Rite Aid"":50,""7-Eleven"":50,""Albertsons"":28,""...","{""Jack in the Box"":33,""7-Eleven"":32,""Food 4 Le...","{""android"":12,""ios"":4}",1
283,211892022,sg:298adcb8fe2f45e6b48ab875ae2c44d6,Center For Employment Training San Diego,Center For Employment Training Escondido,Escondido,CA,92102,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730034033,"{""US"":7}",5031,191.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":6,"">240"":6}","{""DAISO"":50}","{""99 Cents Only Stores"":22,""Burger King"":20,""G...","{""android"":7,""ios"":4}",1
282,212419427,sg:498903c4fb5a408fbbb03bac2d487ccc,FIX Salon,1232 30th St,San Diego,CA,92102,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0...",060730041001,"{""US"":5}",10252,46.5,"{""<5"":0,""5-20"":1,""21-60"":6,""61-240"":3,"">240"":2}",{},"{""Chevron Extra Mile"":29,""24 Hour Fitness"":28,...","{""android"":4,""ios"":0}",1
281,212179342,sg:1d951c64084740caa47bc6caac0a92b8,Iglesia Presbiteriana Hispana,2692 B St,San Diego,CA,92102,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,2,2,0,1,0...",060730045011,"{""US"":19}",2610,42.0,"{""<5"":0,""5-20"":10,""21-60"":10,""61-240"":7,"">240"":7}","{""Select Medical"":25,""Costco Wholesale Corp."":...","{""Costco Wholesale Corp."":16,""Shell Oil"":10,""W...","{""android"":10,""ios"":10}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1744190,sg:52effec4194949f78ca47d8fcb87da18,Krispy Kreme Doughnuts,11050 Rancho Carmel Dr,San Diego,CA,92128,US,SG_BRAND_c00d0bf3a8d7b6744a18e2554adf5921,Krispy Kreme Doughnuts,...,"[0,0,0,0,0,1,1,0,1,3,0,0,1,1,0,2,1,0,0,1,1,1,0...",060730170561,"{""US"":124}",11483,9.0,"{""<5"":13,""5-20"":93,""21-60"":19,""61-240"":8,"">240...","{""CVS"":11,""Rubio's Restaurants"":7,""Discount Ti...","{""Starbucks"":22,""Costco Wholesale Corp."":19,""I...","{""android"":57,""ios"":68}",1
335,196969537,sg:2b08cfd6964d408bb8e405c76466cb89,Sun Orthodontics Melanie H Duong DMD MS,16766 Bernardo Center Dr,San Diego,CA,92128,US,,,...,"[0,0,0,0,0,0,0,0,2,1,1,0,0,0,1,0,0,1,0,0,0,0,0...",060730170141,"{""US"":24}",6232,41.0,"{""<5"":0,""5-20"":11,""21-60"":11,""61-240"":9,"">240"":6}","{""Staples"":17,""Shell Oil"":15,""Panda Express"":1...","{""Courtyard by Marriott"":15,""Starbucks"":14,""Sh...","{""android"":5,""ios"":18}",1
348,204935338,sg:b3b159b5c7c84067aae7d995538d182b,Starbucks,12469 Rancho Bernardo Road Rancho Bernardo Vil...,San Diego,CA,92128,US,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0...",060730170141,"{""US"":26}",13785,17.5,"{""<5"":3,""5-20"":11,""21-60"":8,""61-240"":4,"">240"":0}","{""Shell Oil"":32}","{""Costco Wholesale Corp."":25,""Albertsons"":23,""...","{""android"":26,""ios"":0}",1
347,205599386,sg:8326eeee305245f2ab1d05642080c553,The Baked Bear,11640 Carmel Mountain Rd Ste 120,San Diego,CA,92128,US,SG_BRAND_f712fed0e54d3879,The Baked Bear,...,"[0,0,0,0,0,0,0,0,0,6,4,1,2,9,2,0,9,1,5,3,0,0,0...",060730170561,"{""US"":204}",6474,133.0,"{""<5"":1,""5-20"":20,""21-60"":20,""61-240"":174,"">24...","{""In-N-Out Burger"":8,""Dick's Sporting Goods"":7...","{""Starbucks"":17,""Costco Wholesale Corp."":13,""C...","{""android"":44,""ios"":159}",1
346,204286446,sg:66d9ee5eea794feb80c08b3443b22d4f,iGifts And Cards,12463 Rancho Bernardo Rd Ste 286,San Diego,CA,92128,US,,,...,"[0,0,1,0,0,0,0,2,0,3,0,3,1,1,1,1,2,4,1,0,1,0,0...",060730170141,"{""US"":174,""MX"":4}",3819,20.0,"{""<5"":12,""5-20"":90,""21-60"":53,""61-240"":32,"">24...","{""Courtyard by Marriott"":9,""Starbucks"":8,""Jack...","{""Starbucks"":29,""Costco Wholesale Corp."":20,""T...","{""android"":77,""ios"":95}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1679447,sg:d60c9b1467b548ed9df95eb5e8b43c90,Elixir Espresso & Wine Bar,7863 Girard Ave Ste 105,La Jolla,CA,92037,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730082003,"{""US"":8}",3792,68.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":3,"">240"":0}",{},"{""Westfield"":40,""Costco Wholesale Corp."":38,""P...","{""android"":0,""ios"":4}",1
556,201958798,sg:d034b3ae351249afb2fd8d8130e4be38,All About Animals,5622 La Jolla Blvd,La Jolla,CA,92037,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730081021,{},0,5.5,"{""<5"":1,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
546,200682004,sg:1760988a6e914105b59a91cfb1b58270,La Jolla Village Square,8657 Villa La Jolla Dr,La Jolla,CA,92037,US,,,...,"[0,0,0,1,4,2,4,4,9,21,31,35,52,50,47,28,58,37,...",060730083621,"{""US"":1901,""MX"":20,""BR"":4}",9292,23.0,"{""<5"":66,""5-20"":1165,""21-60"":992,""61-240"":609,...","{""Starbucks"":25,""Yoga Six"":13,""Club Pilates"":1...","{""Starbucks"":35,""Westfield"":22,""Yoga Six"":16,""...","{""android"":917,""ios"":1039}",1
547,198469403,sg:c56c81c893e64e10a1ef9d91222e7516,J Mclaughlin,7880 Girard Ave,La Jolla,CA,92037,US,SG_BRAND_57e54c7e8c306011,J Mclaughlin,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730082001,{},0,11.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
548,200662390,sg:2efe578d58ae4e6ab0b6a7ea1412740f,The Promiscuous Fork,6984 La Jolla Blvd,La Jolla,CA,92037,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0...",060730081013,"{""US"":6}",617524,39.0,"{""<5"":0,""5-20"":3,""21-60"":4,""61-240"":2,"">240"":2}","{""CVS"":66}","{""Jason's Deli"":28,""OfficeMax"":28,""Fairfield I...","{""android"":5,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1744244,sg:54a36f4d08b0432dab9c5d1d61a4fd84,Coastal Ink and Toner,3655 Adams Ave,San Diego,CA,92116,US,,,...,"[1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,1,0,0,0...",060730018001,"{""US"":50}",1285,13.0,"{""<5"":3,""5-20"":36,""21-60"":17,""61-240"":3,"">240"":2}","{""Chili's Grill & Bar"":17,""Rite Aid"":13,""Seaso...","{""Vons"":27,""Starbucks"":22,""Chevron"":21,""7-Elev...","{""android"":36,""ios"":14}",1
229,211607593,sg:c41dab4d194a4d90a54995dd00e1a819,Pop Pie Co,4404 Park Blvd Ste A,San Diego,CA,92116,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,2,0,0,0,2,0,0...",060730005003,"{""US"":40}",12326,30.0,"{""<5"":0,""5-20"":18,""21-60"":18,""61-240"":9,"">240""...","{""Curio Collection"":17,""Westfield"":14,""Weight ...","{""Westfield"":22,""Costco Wholesale Corp."":20,""S...","{""android"":21,""ios"":20}",1
227,210923369,sg:3c5b4bc243704c8bbcee5b8976235db7,Bench Home,4153 Adams Ave,San Diego,CA,92116,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0...",060730021001,"{""US"":9}",3667,24.0,"{""<5"":0,""5-20"":4,""21-60"":5,""61-240"":4,"">240"":0}",{},"{""Chevron"":36,""MGM Resorts"":25,""Starbucks"":20,...","{""android"":4,""ios"":4}",1
226,210034676,sg:33f0d7de670f4a6793e1f929052b7d16,Normal Heights Barbershop,4684 Mansfield St,San Diego,CA,92116,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730018003,"{""US"":4}",0,22.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
225,210188180,sg:8b725aca30494e258f2a656846ed0bae,Hayk & Bel Sport Club,4473 30th St,San Diego,CA,92116,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,2...",060730012002,"{""US"":14,""SO"":4}",8494,36.5,"{""<5"":0,""5-20"":9,""21-60"":5,""61-240"":2,"">240"":8}","{""Lincoln"":50,""WestCoast Hooters"":20,""85 Degre...","{""ARCO"":26,""7-Eleven"":25,""Target"":23,""Subway"":...","{""android"":10,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1748443,sg:8569f6378cac4edd9051c001e74861d2,First Fishery Development Services,9484 Chesapeake Dr,San Diego,CA,92123,US,,,...,"[0,0,0,0,0,0,0,1,3,1,0,1,1,0,0,0,0,0,1,0,0,0,0...",060730085111,"{""US"":21}",15793,46.5,"{""<5"":1,""5-20"":11,""21-60"":9,""61-240"":11,"">240"":6}","{""The Original Pancake House"":14,""Kaiser Perma...","{""The Home Depot"":24,""Carl's Jr."":17,""Jack in ...","{""android"":14,""ios"":11}",1
459,196770275,sg:3a5fa4da9ca847ecaa6ae0d97df0392b,Larson Sharpening,2008 Goshawk St,San Diego,CA,92123,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0...",060730087022,"{""US"":7}",9720,425.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":2,"">240"":14}","{""Golden Corral"":25}","{""ARCO"":33,""Goodwill Industries"":21,""Red O Res...","{""android"":4,""ios"":4}",1
451,194243124,sg:3b4f8ffed1174ed9976ec0cc43657ab9,San Diego Superior Court Traffic Division,8950 Clairemont Mesa Blvd,San Diego,CA,92123,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0...",060730085111,"{""US"":82}",16662,44.5,"{""<5"":0,""5-20"":36,""21-60"":46,""61-240"":38,"">240...","{""Hampton"":40,""Starbucks"":31,""The Home Depot"":...","{""Starbucks"":19,""Costco Wholesale Corp."":15,""S...","{""android"":56,""ios"":27}",1
452,193685307,sg:a699ec7e234845c48084c8977962deec,Learn To Fly San Diego,8690 Aero Dr Ste 116,San Diego,CA,92123,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730085111,"{""US"":7}",25465,19.5,"{""<5"":0,""5-20"":6,""21-60"":4,""61-240"":0,"">240"":0}","{""Residence Inn by Marriott"":50}","{""Black Angus Steakhouse"":25,""Vons"":25,""Burger...","{""android"":4,""ios"":4}",1
453,193948584,sg:c3f9edcd9b2042aabdeba5273bb5c7b7,Accel Motors,5715 Kearny Villa Rd Ste 103,San Diego,CA,92123,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,2,0,0,0,1,0,0,0...",060730085111,"{""US"":10}",28236,25.0,"{""<5"":2,""5-20"":11,""21-60"":11,""61-240"":5,"">240"":0}","{""BMW"":50,""Kia Motors"":50,""Ram"":50,""Dodge"":50,...","{""Jack in the Box"":36,""Chevron"":26,""Starbucks""...","{""android"":8,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2171651,sg:0abb57b4e33941339bb0741bdede72a6,Hallmark Communities,740 Lomas Santa Fe Dr Ste 204,Solana Beach,CA,92075,US,,,...,"[0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0...",060730173032,"{""US"":37}",22119,46.0,"{""<5"":5,""5-20"":26,""21-60"":11,""61-240"":15,"">240...","{""CarMax"":33,""Carl's Jr."":17,""Starbucks"":15,""S...","{""Starbucks"":17,""ARCO"":14,""Sprouts Farmers Mar...","{""android"":27,""ios"":11}",1
229,219309627,sg:8a6a57163f624b3295f9afee47593b06,Casa de las Orquideas,170 S Nardo Ave,Solana Beach,CA,92075,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730173043,"{""US"":4}",0,9.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":5}",1
227,218866772,sg:3753f8234a964e69883e0c1f22873362,David Alan Collection,241 S Cedros Ave,Solana Beach,CA,92075,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,5,3,0,0,0,0,0,0,0,0,0,0...",060730173043,"{""US"":27}",47764,19.0,"{""<5"":0,""5-20"":15,""21-60"":7,""61-240"":5,"">240"":0}","{""Big 5 Sporting Goods"":33,""Westin Hotels & Re...","{""Westfield"":22,""Starbucks"":17,""The Home Depot...","{""android"":7,""ios"":18}",1
226,217741230,sg:50eac692ae124538924242944f4ae861,Solana Beach Fire Department,500 Lomas Santa Fe Dr,Solana Beach,CA,92075,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730173032,"{""US"":4}",0,13.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
225,218427496,sg:8b3b321791fd4ff89cce5d64c1e94860,Verve Plastic Surgery,462 Stevens Ave Ste 206,Solana Beach,CA,92075,US,,,...,"[0,0,0,0,0,0,0,1,2,2,0,0,0,1,0,0,1,0,0,0,0,0,0...",060730173042,"{""US"":17}",17870,101.0,"{""<5"":1,""5-20"":5,""21-60"":10,""61-240"":18,"">240""...","{""The Salvation Army"":12,""LA Fitness"":11,""Cost...","{""walk disney parks and resorts"":21,""Costco Wh...","{""android"":12,""ios"":8}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1658683,sg:24d172b6bbd645d8a377b11580836075,Metroplex Shopping Center,7340 7480 Miramar Road,San Diego,CA,92126,US,,,...,"[0,0,0,0,0,2,1,0,2,1,1,0,2,0,2,2,4,0,0,0,0,0,0...",060730083501,"{""US"":112,""MX"":4}",19472,49.0,"{""<5"":3,""5-20"":45,""21-60"":47,""61-240"":53,"">240...","{""Food 4 Less"":9,""Pinkberry"":8,""Carpet One Flo...","{""Westfield"":19,""Starbucks"":18,""Costco Wholesa...","{""android"":63,""ios"":48}",1
510,205172049,sg:c54ccc164f1f4424a696c09612b75c72,Miramar H&A Auto Repair Center II,9491 Black Mountain Rd Ste B,San Diego,CA,92126,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730083602,"{""US"":4}",0,23.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":1,"">240"":0}",{},{},"{""android"":4,""ios"":8}",1
501,202934224,sg:5f45a4d1dbf24e1c8448a763a64063b9,PORSCHE SAN DIEGO,9020 Miramar Rd,San Diego,CA,92126,US,"SG_BRAND_d599eae7a636d54c1c707514b1a76d77,SG_B...","Porsche,Land Rover,Jaguar",...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,4,1,0,2,1,0,0,0,0,0...",060730083602,"{""US"":33}",20699,23.0,"{""<5"":1,""5-20"":21,""21-60"":19,""61-240"":8,"">240"":2}","{""Audi"":20,""Louisiana Fried Chicken"":10,""PetSm...","{""Audi"":17,""ARCO"":16,""Chevron"":12,""Starbucks"":...","{""android"":19,""ios"":17}",1
502,205165287,sg:def20016220242408ce8cde6786eeb4b,IHOP,8440 Mira Mesa Blvd,San Diego,CA,92126,US,SG_BRAND_2ead5f3ce811920a989327e6f5c6ef73,IHOP,...,"[0,0,0,0,0,0,0,1,0,3,0,0,0,0,0,1,0,0,2,0,0,0,0...",060730083573,"{""US"":108,""GT"":4}",2776,30.0,"{""<5"":6,""5-20"":41,""21-60"":60,""61-240"":16,"">240...","{""Marshalls"":17,""The Art of Shaving"":14,""Rubio...","{""99 Cents Only Stores"":19,""Target"":19,""Shell ...","{""android"":57,""ios"":57}",1
503,203898833,sg:1afc6c377ff547b0aa17eb461be3ea54,Ku Champions Llc Salk Elementary Preschool,7825 Flanders Dr,San Diego,CA,92126,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730083502,"{""US"":40}",3491,77.0,"{""<5"":1,""5-20"":15,""21-60"":18,""61-240"":33,"">240...","{""Jeep"":50,""Vons"":44,""Gelson's Markets"":11,""Ja...","{""Vons"":26,""Costco Wholesale Corp."":19,""Target...","{""android"":17,""ios"":23}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2196735,sg:fae721fe7b004ea4a173bd3323b96ef7,Oceanside Driveline,2435 Industry St Ste B,Oceanside,CA,92054,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0...",060730185042,"{""US"":12}",13158,107.5,"{""<5"":0,""5-20"":6,""21-60"":8,""61-240"":15,"">240"":9}","{""ARCO"":20,""7-Eleven"":20,""Costco Wholesale Cor...","{""Walmart"":24,""FedEx"":19,""ARCO"":18,""Republic S...","{""android"":12,""ios"":4}",1
578,204330485,sg:48fa9060e9d641f48f24919a43dbdf8f,Impulse Surf Products,3038 Industry St Ste 107,Oceanside,CA,92054,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730185042,{},0,10.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
554,198427268,sg:f36d455cf2ec4a8f8e8386276b94c0bd,Cameron Fitness,302 Pier View Way,Oceanside,CA,92054,US,,,...,"[0,0,0,0,0,1,0,1,1,1,4,1,0,1,3,0,0,0,0,1,0,0,0...",060730184003,"{""US"":84,""MX"":4}",22943,45.0,"{""<5"":0,""5-20"":9,""21-60"":54,""61-240"":27,"">240"":3}","{""Raising Cane's"":25,""Cohn Restaurant Group"":1...","{""Starbucks"":19,""In-N-Out Burger"":13,""Simon ma...","{""android"":38,""ios"":48}",1
555,198619396,sg:e297ce91ddda48bb9f14c7845da5937e,Harbor Freight Tools,316 N Horne St,Oceanside,CA,92054,US,SG_BRAND_d587d3baacdacd5cf966e1611a1a799d,Harbor Freight Tools,...,"[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730184003,"{""US"":4}",0,41.0,"{""<5"":0,""5-20"":0,""21-60"":2,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
556,198022939,sg:2bd84fb0be774418900ce9c52adeb0aa,Oceanside Florist,1921 S Coast Hwy,Oceanside,CA,92054,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0...",060730181004,"{""US"":5}",0,23.0,"{""<5"":0,""5-20"":0,""21-60"":3,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1754127,sg:87e6b2f4ac8845a08700f5826686cf95,Streamline Autobody,1539 La Mirada Dr,San Marcos,CA,92078,US,,,...,"[0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730200291,"{""US"":4}",0,5.5,"{""<5"":0,""5-20"":4,""21-60"":0,""61-240"":1,"">240"":1}","{""Cycle Gear"":50,""7-Eleven"":50}","{""Jerome's Furniture"":20,""MINI"":20,""Cycle Gear...","{""android"":4,""ios"":4}",1
444,189200234,sg:371e78530be84735b800b43573e9216c,Fresh MXN Food,580 S Pacific St,San Marcos,CA,92078,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0...",060730200291,"{""US"":35}",4645,14.5,"{""<5"":1,""5-20"":26,""21-60"":8,""61-240"":9,"">240"":2}","{""7-Eleven"":50,""Starbucks"":18,""dd's DISCOUNTS""...","{""7-Eleven"":18,""Starbucks"":17,""In-N-Out Burger...","{""android"":21,""ios"":14}",1
468,198567721,sg:4c411b0f304341f4b091488d2144d725,TekDeals,295 Hill Dr,San Marcos,CA,92078,US,,,...,"[0,0,0,0,1,0,1,1,0,2,0,0,0,0,0,0,3,0,0,0,0,0,0...",060730203061,"{""US"":14}",13788,220.5,"{""<5"":1,""5-20"":4,""21-60"":6,""61-240"":10,"">240"":21}","{""Texas Roadhouse"":20,""Yum Yum Donuts"":17}","{""Jack in the Box"":31,""Starbucks"":20,""Jamba"":1...","{""android"":7,""ios"":9}",1
469,201639024,sg:3f4347515a974c178d638ba563d3b60c,Center For Children & Families At Cal State Sms,453 La Moree Rd,San Marcos,CA,92078,US,,,...,"[0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203061,"{""US"":21}",6475,76.0,"{""<5"":1,""5-20"":21,""21-60"":1,""61-240"":14,"">240""...","{""Chick-fil-A"":11,""Sprouts Farmers Market"":10}","{""Starbucks"":30,""Jamba"":17,""Ralphs"":13,""Costco...","{""android"":9,""ios"":9}",1
470,201601749,sg:f1671a6d54a74cefb49c5d0f9cd00c95,Quick Charge Power,1780 La Costa Meadows Dr Ste 104,San Marcos,CA,92078,US,,,...,"[0,0,0,0,0,1,1,1,0,0,1,0,2,0,0,0,1,0,0,0,0,0,0...",060730200273,"{""US"":15}",12521,79.5,"{""<5"":1,""5-20"":5,""21-60"":13,""61-240"":12,"">240""...","{""CycleBar"":25}","{""Starbucks"":8,""Patagonia"":6,""Jerome's Furnitu...","{""android"":12,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1776295,sg:902790fc591240b6919ce7aa31340a6e,Saint Adelaide Church,1021 Sheridan Rd,Campo,CA,91906,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211003,{},0,5.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
17,137548922,sg:a966f308561c459d97dc3b62731d7ba8,El Paso Taco Shop,31464 California 94,Campo,CA,91906,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0...",060730211003,"{""US"":6}",14262,36.0,"{""<5"":0,""5-20"":2,""21-60"":4,""61-240"":0,"">240"":0}","{""Chevron"":99}","{""Sinclair Oil"":33,""United States Postal Servi...","{""android"":5,""ios"":0}",1
31,289793247,sg:649363e337a64d59975caa825bd8345e,Cameron Corners Convenient Store,31484 Highway 94,Campo,CA,91906,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0...",060730211003,"{""US"":21}",5353,8.0,"{""<5"":3,""5-20"":23,""21-60"":5,""61-240"":0,"">240"":0}","{""McDonald's"":47}","{""Sinclair Oil"":25,""7-Eleven"":15,""Albertsons"":...","{""android"":18,""ios"":6}",1
30,272379167,sg:10cb56d656094c49a310ce6fe2fd5f83,Circle K,31471 Highway 94,Campo,CA,91906,US,SG_BRAND_4cbffa4318cebdb09227afca3fe16846,Circle K,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0...",060730211003,"{""US"":9}",4425,6.0,"{""<5"":0,""5-20"":9,""21-60"":0,""61-240"":0,"">240"":0}","{""Sinclair Oil"":100}","{""Sinclair Oil"":100,""Denny's"":44,""Costco Whole...","{""android"":7,""ios"":0}",1
29,246550811,sg:464ab0da7e5142bd9ed7e1532d751318,Campo Green Store,31080 Highway 94,Campo,CA,91906,US,,,...,"[0,0,0,0,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,0,0,0,0...",060730211003,"{""US"":16}",2132,9.0,"{""<5"":2,""5-20"":17,""21-60"":7,""61-240"":3,"">240"":3}","{""Sinclair Oil"":50,""ARCO"":20,""Walmart"":10}","{""Sinclair Oil"":41,""Walmart"":22,""Chevron"":22,""...","{""android"":13,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1241149,sg:22ea42c4c5794fcb8984b67b85d4fb68,Escondido Fire Department Station 2 East Valley,421 N Midway Dr,Escondido,CA,92027,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0...",060730202072,"{""US"":4}",0,118.0,"{""<5"":0,""5-20"":3,""21-60"":1,""61-240"":4,"">240"":3}",{},{},"{""android"":0,""ios"":4}",1
205,185762653,sg:69e2ac0dc0f6443aa2610715e06d5066,Prestige Exteriors Landscaping,1224 Birch Ave,Escondido,CA,92027,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730207053,{},0,7.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
223,202586403,sg:0ddcba629fe644bab9b614d397dd920d,Vietnam Veterans of America Donation Pickup Se...,2085 E Valley Pkwy,Escondido,CA,92027,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730202092,{},0,66.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
222,201761012,sg:83b196a5b9bb4e728789a71ae48862b9,El Huarache Taco Shop,764 N Midway Dr,Escondido,CA,92027,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0...",060730202081,"{""US"":4}",0,1053.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":7}",{},{},"{""android"":0,""ios"":0}",1
221,200823810,sg:f80cbaf7a975439296ee94229378544d,Escondido Barber Shop,2445 E Valley Pkwy,Escondido,CA,92027,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730202102,{},0,4.0,"{""<5"":1,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1796529,sg:1dbb3f01a1874c8c86def159415c00fc,Big Boyz Car Audio,1415 Skyline Dr Ste A,Lemon Grove,CA,91945,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730140021,{},0,9.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
226,205777753,sg:f6270dfa0a894397bd58a20f2dccf569,Gold Coast Motors,6933 North Ave,Lemon Grove,CA,91945,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730144002,"{""US"":4}",0,18.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
224,204774814,sg:131b2e6b2cfa4c86a244512a43c3268f,Blanca's Family Day Care,8368 Palm St,Lemon Grove,CA,91945,US,,,...,"[0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,2...",060730140013,"{""US"":28}",6824,42.0,"{""<5"":2,""5-20"":20,""21-60"":11,""61-240"":11,"">240...","{""GameStop"":20,""Shell Oil"":19,""Luna Grill"":9,""...","{""ARCO"":21,""Costco Wholesale Corp."":14,""Food 4...","{""android"":23,""ios"":6}",1
223,206006914,sg:3d281341c4514336a541cabbb5a5d55f,St John Of The Cross School,8175 Lemon Grove Way,Lemon Grove,CA,91945,US,,,...,"[0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,3,1,1,0,0,0,1,0...",060730144001,"{""US"":139,""MX"":4}",4925,60.0,"{""<5"":3,""5-20"":43,""21-60"":63,""61-240"":84,"">240...","{""Starbucks"":11,""AutoZone"":6}","{""Costco Wholesale Corp."":16,""Starbucks"":13,""7...","{""android"":75,""ios"":70}",1
222,203897820,sg:13d74dc850e64eb797b244ce1e7404f0,David Labrana DC,7103 Broadway,Lemon Grove,CA,91945,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730144002,"{""US"":7}",1138,20.0,"{""<5"":0,""5-20"":5,""21-60"":4,""61-240"":0,"">240"":0}","{""Champs Sports"":100,""Jack in the Box"":100,""Th...","{""Rodeway Inn"":33,""Build A Bear Workshop"":33,""...","{""android"":8,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,3097549,sg:b8395da1bb2a4cfea2ea3ed67b5a7d19,Freeway Insurance Services,1919 Mission Ave,Oceanside,CA,92058,US,SG_BRAND_4f35805991e67d975d44d2200d8136ad,Freeway Insurance Services,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730185091,{},0,12.5,"{""<5"":0,""5-20"":3,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
207,203240343,sg:04f975eb1e044d948b647ea966836ccd,Kaad Engineering,227 Via El Centro,Oceanside,CA,92058,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730186032,"{""US"":4}",0,168.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":3,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
205,200683015,sg:1fbcee0fd0444b41b746cc8c6f3a4aea,Milano's Liquor,3846 Mission Ave Ste A2,Oceanside,CA,92058,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730186141,"{""US"":8}",4260,29.0,"{""<5"":0,""5-20"":3,""21-60"":4,""61-240"":2,"">240"":0}","{""McDonald's"":30,""Albertsons"":25}","{""Dollar Tree"":31,""Target"":30,""McDonald's"":26,...","{""android"":6,""ios"":4}",1
204,199985989,sg:465dfe5907024604acbf37d9d92f5afb,San Luis Rey Bakery & Restaurant,490 N El Camino Real,Oceanside,CA,92058,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0...",060730185073,"{""US"":23}",3586,28.5,"{""<5"":0,""5-20"":10,""21-60"":13,""61-240"":1,"">240"":0}","{""Abbey Carpet and Floor"":33,""Rubio's Restaura...","{""Vons"":17,""The Home Depot"":15,""Swami's Cafe"":...","{""android"":9,""ios"":10}",1
203,198859484,sg:99646e692a1f463f8ca118ef97d0988b,Sew O'side,3375 Mission Ave Ste F,Oceanside,CA,92058,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730185102,"{""US"":12}",6695,10.0,"{""<5"":0,""5-20"":5,""21-60"":3,""61-240"":1,"">240"":0}",{},"{""G&M"":22,""76"":22,""Jack in the Box"":22,""Dollar...","{""android"":7,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1658733,sg:290dabf64bcf49be8adf35b186d0525a,All American Septic Pumping & Services,29265 Twain Way,Valley Center,CA,92082,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730191061,"{""US"":5}",0,99.0,"{""<5"":2,""5-20"":5,""21-60"":2,""61-240"":8,"">240"":6}",{},{},"{""android"":0,""ios"":5}",1
105,212878161,sg:2f3e5b3211614555880799913466ffff,The Cafe,16300 Nyemii Pass Rd,Valley Center,CA,92082,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191063,"{""US"":9}",36325,341.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":8}","{""ARCO"":33,""Chuck E. Cheese's"":17}","{""ARCO"":33,""Ross Stores"":32,""Costco Wholesale ...","{""android"":5,""ios"":4}",1
98,194355722,sg:8b50fe843a664ec5b3c7562189e5f533,Heatshield Products,27354 Valley Center Rd,Valley Center,CA,92082,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730201031,"{""US"":4}",0,6.5,"{""<5"":1,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":4}",1
99,195323475,sg:8e44d57abe664837ac92e18bc2ebf5b9,C87 Roofing,27653 N Lake Wohlford Rd,Valley Center,CA,92082,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191071,,0,284.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
100,196467684,sg:332c6e1c35a648929428a85e6edb13a5,Greens Storage,28407 Lizard Rocks Rd,Valley Center,CA,92082,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,1,0,0,0,0,0,0...",060730191063,"{""US"":8}",7707,55.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":4,"">240"":1}",{},"{""Dior"":25,""HermÃ¨s"":25,""MGM Resorts"":25,""7-El...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1475650,sg:4624e72963bb4bafa19a55ddb02c31ef,Palomar Mountain General Store,33120 Canfield Rd,Palomar Mountain,CA,92060,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730209031,"{""US"":4}",0,28.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":1,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
1,94297742,sg:43c564b36bd14d1f8d083ad4bc3b7a7a,Fry Creek Campground,Co Hwy S6,Palomar Mountain,CA,92060,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209031,{},0,257.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
2,116994407,sg:978654c0d94946f4baf6b2ed58ac844c,Palomar Observatory,35899 Canfield Rd,Palomar Mountain,CA,92060,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730209031,"{""US"":6}",205523,16.0,"{""<5"":0,""5-20"":5,""21-60"":2,""61-240"":2,"">240"":0}",{},"{""Walmart"":20,""Ruby's Diner"":17,""The Broken Yo...","{""android"":4,""ios"":4}",1
3,129541150,sg:acb07e685ccd4a6aab51a27e90db732b,Fama Living San Diego,860 Los Vallecitos Blvd,Palomar Mountain,CA,92060,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730200292,"{""US"":4}",4082,6.0,"{""<5"":1,""5-20"":4,""21-60"":0,""61-240"":0,"">240"":0}","{""ARCO"":50}","{""McDonald's"":52,""Westfield"":40,""In-N-Out Burg...","{""android"":0,""ios"":0}",1
4,234313455,sg:a0f46fe268624b2bb020e9c57a6d3988,Mother's Kitchen,33120 Canfield Rd,Palomar Mountain,CA,92060,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209031,{},0,9.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,3104934,sg:ca03087209dc4459b3c1dd1728ef369e,Tip Top Meats & European Delicatessen,6118 Paseo del Norte,Carlsbad,CA,92011,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730178112,"{""US"":18}",11075,15.0,"{""<5"":0,""5-20"":9,""21-60"":4,""61-240"":4,"">240"":0}","{""Discount Tire"":100,""Vons"":20}","{""Costco Wholesale Corp."":45,""Starbucks"":19,""W...","{""android"":14,""ios"":4}",1
225,200097250,sg:54c5f4e6fe3148a394d1aaaceaed1567,Argyle Steakhouse,7447 Batiquitos Dr,Carlsbad,CA,92011,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730178081,{},0,482.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
223,198312698,sg:8c61cdf8b92a4546b25045b1dda43252,K1 Speed,6212 Corte del Abeto,Carlsbad,CA,92011,US,SG_BRAND_2252d4502568f466,K1 Speed,...,"[0,0,0,0,0,0,0,0,0,0,0,4,2,1,0,4,4,0,2,0,0,0,0...",060730221002,"{""US"":63}",9574,42.0,"{""<5"":1,""5-20"":16,""21-60"":27,""61-240"":31,"">240...","{""ARCO"":33,""In-N-Out Burger"":15,""El Pollo Loco...","{""In-N-Out Burger"":18,""Starbucks"":15,""Costco W...","{""android"":24,""ios"":44}",1
222,196598994,sg:b5cf0365d3d7424182ae94751edb24f5,Lift Supports Depot,2345 Camino Vida Roble,Carlsbad,CA,92011,US,,,...,"[0,0,0,0,0,0,1,0,2,1,0,1,1,0,0,1,2,0,0,0,1,0,0...",060730221002,"{""US"":5}",9615,169.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":10,"">240"":10}","{""Circle K"":100,""Target"":49,""Starbucks"":15}","{""Lowe's"":27,""The Home Depot"":26,""Park Hyatt"":...","{""android"":4,""ios"":4}",1
221,194809257,sg:c4ffbce382f249b08e791ba802a707f1,United States Postal Service (USPS),1700 Aviara Pkwy,Carlsbad,CA,92011,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,1,1,0,2,0,0,0,1,1,0,0,0,0,0,0...",060730221003,"{""US"":56}",4124,10.0,"{""<5"":3,""5-20"":52,""21-60"":9,""61-240"":4,"">240"":0}","{""24 Hour Fitness"":25,""Buca di Beppo"":20,""El P...","{""Starbucks"":21,""Vons"":21,""Costco Wholesale Co...","{""android"":26,""ios"":25}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1794405,sg:1b2d526f7e194f0bb496444ab0c0b174,A & M Mobile Auto Repair,830 Emory St,Imperial Beach,CA,91932,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730103003,{},0,82.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":4,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
170,201951148,sg:55421e877e6848719084920dd1678003,Dollar Tree,836 Palm Ave,Imperial Beach,CA,91932,US,SG_BRAND_6b1e006c89aa3f8b054a05fa90581501,Dollar Tree,...,"[0,0,1,1,0,1,0,0,1,0,2,3,2,3,0,2,4,1,0,1,0,0,1...",060730105023,"{""US"":119,""MX"":4}",2477,21.0,"{""<5"":3,""5-20"":81,""21-60"":44,""61-240"":20,"">240...","{""Jack in the Box"":13,""Food 4 Less"":9}","{""Jack in the Box"":17,""Grocery Outlet"":16,""Wal...","{""android"":77,""ios"":45}",1
144,169137274,sg:1443cd7cd7d64d1fbcbe127ab2f0a906,Corrales Tax & Insurance Services,936 Palm Ave,Imperial Beach,CA,91932,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730105023,{},0,154.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
145,170370181,sg:501d67c589cc4c58a32d6f86712e327e,13th St Market,1126 13th St,Imperial Beach,CA,91932,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730104021,"{""US"":7}",1231,8.0,"{""<5"":0,""5-20"":6,""21-60"":0,""61-240"":1,"">240"":0}","{""The Dailey Method"":100,""CVS"":49}","{""Carl's Jr."":50,""7-Eleven"":49,""HomeTown Buffe...","{""android"":4,""ios"":0}",1
146,171539212,sg:2e0ed8b43ec9408dad8433e68e8a6c4a,Imperial Beach Fire Department Station 39,865 Imperial Beach Blvd,Imperial Beach,CA,91932,US,,,...,"[2,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,2,0,0,2,1...",060730103001,"{""US"":22}",141671,39.0,"{""<5"":1,""5-20"":21,""21-60"":8,""61-240"":14,"">240""...","{""The Salvation Army"":8,""Big Lots Stores"":7}","{""Church's Chicken"":10,""7-Eleven"":6}","{""android"":5,""ios"":22}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2850484,sg:e236a5188320469588401e80ebb2be0a,Fuel Deli,9312 Mission Gorge Rd Go Gasoline Station,La Mesa,CA,91941,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730166141,"{""US"":13}",3465,6.0,"{""<5"":3,""5-20"":10,""21-60"":4,""61-240"":0,"">240"":0}","{""Honda"":100,""Epic Wings N' Things"":25,""United...","{""Starbucks"":42,""In-N-Out Burger"":29,""7-Eleven...","{""android"":7,""ios"":8}",1
105,163793060,sg:3497032cc6844148acba7d49ee780a04,IHOP,8747 Broadway,La Mesa,CA,91941,US,SG_BRAND_2ead5f3ce811920a989327e6f5c6ef73,IHOP,...,"[0,0,0,0,0,0,0,0,0,1,4,0,2,0,2,0,1,5,1,0,0,0,0...",060730138011,"{""US"":112}",5242,43.0,"{""<5"":2,""5-20"":22,""21-60"":52,""61-240"":36,"">240...","{""Bobcat"":17,""United Rentals"":17,""Westfield"":1...","{""Starbucks"":23,""ARCO"":16,""Jack in the Box"":16...","{""android"":67,""ios"":43}",1
133,202647706,sg:66f6e86a211143569e7ad0720b7fb115,Sierra Markets,3834 Massachusetts Ave,La Mesa,CA,91941,US,,,...,"[1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,1...",060730145002,"{""US"":19}",735,33.0,"{""<5"":4,""5-20"":13,""21-60"":5,""61-240"":3,"">240"":14}","{""ARCO"":33,""Dollar Tree"":24,""Rubio's Restauran...","{""ARCO"":18,""Dollar Tree"":16,""Food 4 Less"":14,""...","{""android"":16,""ios"":4}",1
134,206152942,sg:dfb042fbbad34bc4a303e64865889afd,Abc Barn Children's Place Extended Day,10842 Fury Ln,La Mesa,CA,91941,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730136052,"{""US"":5}",11619,15.0,"{""<5"":0,""5-20"":6,""21-60"":1,""61-240"":1,"">240"":0}",{},"{""DixieLine"":25,""Kaiser Permanente"":25,""Kahoot...","{""android"":6,""ios"":4}",1
135,205317774,sg:6dd55d816c3d4494b6907679beb4ead2,KinderCare,3655 Via Mercado,La Mesa,CA,91941,US,SG_BRAND_bb687a854c6bcb1,KinderCare,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,2,0,0,1,0,1...",060730136062,"{""US"":13}",3513,12.5,"{""<5"":5,""5-20"":12,""21-60"":3,""61-240"":4,"">240"":8}","{""Smart & Final"":25,""United States Postal Serv...","{""Albertsons"":21,""Shell Oil"":18,""Smart & Final...","{""android"":7,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1084969,sg:849bc5ae29244387bcf792b3750ed12d,All Rider Gear,2856 Main St,San Diego,CA,92113,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730039023,"{""US"":4}",0,20.0,"{""<5"":0,""5-20"":3,""21-60"":1,""61-240"":1,"">240"":0}","{""ampm"":50,""ARCO"":50}","{""KOA (Kampgrounds of America)"":20,""Porsche"":2...","{""android"":0,""ios"":0}",1
308,212995133,sg:9b321cdbcd404d74a2437b4870cc3c52,Six Maritime Weapons Simulator,1733 National Ave,San Diego,CA,92113,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1...",060730051002,"{""US"":15}",8700,37.0,"{""<5"":2,""5-20"":7,""21-60"":4,""61-240"":4,"">240"":4}","{""Food 4 Less"":33}","{""Starbucks"":17,""Westfield"":11,""Party City"":11...","{""android"":8,""ios"":12}",1
320,220689848,sg:bc6e1a1c6da4415bbb4a2eae639ea177,Ol' Fashioned Lumber,1815 Main St,San Diego,CA,92113,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730050001,"{""US"":4}",0,29.0,"{""<5"":0,""5-20"":3,""21-60"":4,""61-240"":0,"">240"":1}",{},"{""Subway"":36,""Bloomingdale's"":20,""SiteOne Land...","{""android"":0,""ios"":4}",1
319,220869445,sg:1248bac56ae9493bb27d258ceed7b677,Dough Nations,1985 National Ave Ste 1101,San Diego,CA,92113,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,0,1,1,2,1,3,0,0,0,0,1,0...",060730050001,"{""US"":48}",6288,35.5,"{""<5"":3,""5-20"":22,""21-60"":18,""61-240"":11,"">240...","{""Sur La Table"":17,""United States Postal Servi...","{""Starbucks"":20,""7-Eleven"":16,""Shell Oil"":10,""...","{""android"":30,""ios"":17}",1
318,220520453,sg:aa76ca0ca7bb4ab4859ff9538cb19775,Diamond Maintenance Services,4108 Gamma St,San Diego,CA,92113,US,,,...,"[0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2,0,0,1,0,0,0...",060730036021,"{""US"":15}",1193,46.0,"{""<5"":0,""5-20"":9,""21-60"":9,""61-240"":11,"">240"":4}","{""Target"":24}","{""Food 4 Less"":16,""Walmart"":13,""Target"":12,""St...","{""android"":13,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1797641,sg:2843f0f70bf14ba1a87745afc09f6ff0,B D Masonry,2121 Jewel Valley Rd,Boulevard,CA,91905,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211002,"{""US"":4}",0,12.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":1,"">240"":1}",{},{},"{""android"":0,""ios"":4}",1
1,20169837,sg:9679e09c00bd41519df34704ce4ccc38,Manzanita Diner,40080 Old Highway 80,Boulevard,CA,91905,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730211002,"{""US"":7}",6365,26.0,"{""<5"":1,""5-20"":2,""21-60"":4,""61-240"":1,"">240"":0}","{""Red Lobster"":100}","{""Starbucks"":24,""San Diego Style Sombrero Mexi...","{""android"":4,""ios"":4}",1
2,19144286,sg:62f2f94dc0fb46cfa5fe8137e1bb55a2,United States Postal Service (USPS),39550 Old Highway 80 Ste A,Boulevard,CA,91905,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211002,"{""US"":4}",0,7.0,"{""<5"":0,""5-20"":5,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":4,""ios"":4}",1
3,47182322,sg:2027cb6b2c9a49189f034ada3774f80e,Clover Flat Elementary,39639 Old Highway 80,Boulevard,CA,91905,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211002,"{""US"":7}",13191,72.0,"{""<5"":1,""5-20"":1,""21-60"":3,""61-240"":5,"">240"":1}","{""Anytime Fitness"":50}","{""Walmart"":62,""Albertsons"":50,""United States P...","{""android"":6,""ios"":4}",1
4,52698462,sg:3ed6e31cf3a24a6f87f2ab06bd8dcb4c,Wisteria Candy Cottage,39961 Old Highway 80,Boulevard,CA,91905,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211002,{},0,26.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2335121,sg:5caf771c097f4026a1576e948495773f,TC Worthy Cash & Carry,405 Tecate Rd,Tecate,CA,91980,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0...",060730211001,"{""US"":30,""MX"":21}",37447,25.0,"{""<5"":2,""5-20"":32,""21-60"":10,""61-240"":13,"">240...","{""Rodeway Inn"":8,""Sinclair Oil"":6}","{""7-Eleven"":19,""Target"":15,""ARCO"":12,""Chevron""...","{""android"":41,""ios"":14}",1
1,61158838,sg:83926de4653944fc99cd31c74626bd74,Baja Mex Video,433 Tecate Rd,Tecate,CA,91980,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730211001,"{""MX"":4}",0,7.5,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
2,109040695,sg:b560a590f8884792a6c07d224c04331e,Tecate Christian School,23945 Tecate Mission Rd,Tecate,CA,91980,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,"{""MX"":4}",2980,19.0,"{""<5"":1,""5-20"":5,""21-60"":3,""61-240"":0,"">240"":1}","{""Grocery Outlet"":33,""AutoZone"":33}","{""ARCO"":37,""7-Eleven"":36,""Pilot Flying J"":24,""...","{""android"":6,""ios"":4}",1
3,152357419,sg:c35895232ab64c15afca1cb73eb26a99,JMM Construction & Remodeling,433A Tecate Rd,San Diego,CA,91980,US,,,...,"[0,0,0,0,0,1,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,0...",060730211001,"{""US"":15,""MX"":12}",28418,9.0,"{""<5"":5,""5-20"":21,""21-60"":4,""61-240"":1,"">240"":2}","{""Jack in the Box"":33,""Ross Stores"":33,""Chevro...","{""Jack in the Box"":22,""In-N-Out Burger"":11,""Pa...","{""android"":17,""ios"":9}",1
4,169383506,sg:cbe604eacb564ba3a553a056043fbf1e,Ramco Petroleum,447 Tecate Rd,Tecate,CA,91980,US,,,...,"[0,0,0,0,0,1,1,1,1,0,0,0,2,0,0,0,0,0,0,1,0,0,0...",060730211001,"{""MX"":27,""US"":22}",5420,14.0,"{""<5"":5,""5-20"":42,""21-60"":14,""61-240"":8,"">240""...","{""Big O Tires"":33,""Circle K"":33,""Wetzel's Pret...","{""7-Eleven"":14,""Target"":12,""Walmart"":12,""ARCO""...","{""android"":35,""ios"":13}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,3273874,sg:36a04c0c3fce48f8a41fa6a7a28db477,Stevens moving & junk hauling service,7427 Gatewood Ln,San Diego,CA,92114,US,,,...,"[0,0,0,2,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,2,0,0,0...",060730031152,"{""US"":13}",110,176.5,"{""<5"":0,""5-20"":6,""21-60"":10,""61-240"":15,"">240""...","{""Macy's"":20,""Little Caesars"":20,""Souplantatio...","{""In-N-Out Burger"":14,""Denny's"":14,""AutoZone"":...","{""android"":13,""ios"":0}",1
133,184413687,sg:a72a5664c1aa46169d0dada564ecff66,Nye Elementary,981 Valencia Pkwy,San Diego,CA,92114,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0...",060730031132,"{""US"":39}",2657,26.0,"{""<5"":5,""5-20"":35,""21-60"":24,""61-240"":17,"">240...","{""Rubio's Restaurants"":33,""Cricket Wireless"":3...","{""Westfield"":17,""Jack in the Box"":17,""76"":15,""...","{""android"":30,""ios"":11}",1
135,187374389,sg:45c51f12036743b38706b4d245536749,Evangeline Roberts Institute Of Learning P S,1012 Derby St Bldg 4,San Diego,CA,92114,US,,,...,"[1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,3,0,0,0,1,0,0...",060730030012,"{""US"":24}",5473,166.5,"{""<5"":0,""5-20"":3,""21-60"":4,""61-240"":16,"">240"":17}","{""Food 4 Less"":8}","{""Starbucks"":20,""Subway"":17,""Food 4 Less"":17,""...","{""android"":16,""ios"":6}",1
136,186828500,sg:f1b9ec3f5b744098b8e4622837baac43,Morse High,6905 Skyline Dr,San Diego,CA,92114,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,4,1,1,0,0,0,1,0,0,1,0...",060730031142,"{""US"":203,""MX"":4}",2691,103.0,"{""<5"":11,""5-20"":165,""21-60"":135,""61-240"":372,""...","{""Vallarta Supermarkets"":25,""Red Robin Gourmet...","{""Westfield"":16,""McDonald's"":10,""Jack in the B...","{""android"":73,""ios"":141}",1
137,193547577,sg:7e7ce14662664b88b0b5d6cee0ec2f1e,Master Barbers,6375 Imperial Ave,San Diego,CA,92114,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,0...",060730031121,"{""US"":11}",1604,102.0,"{""<5"":1,""5-20"":4,""21-60"":8,""61-240"":11,"">240"":10}","{""Mor Furniture for Less"":33,""Little Caesars"":...","{""Food 4 Less"":45,""Westfield"":27,""Starbucks"":2...","{""android"":7,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1741862,sg:4bba3ed1757843eba997202e116b131f,BRSH FLSS Pediatric Dentistry,7189 Navajo Rd Ste A,San Diego,CA,92119,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730098014,"{""US"":4}",0,425.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
73,132848872,sg:fdbb9706c11d4860bf606f2bc5725ae0,5 Star Customs,6867 Golfcrest Dr,San Diego,CA,92119,US,,,...,"[2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,1,1,0,0...",060730098013,"{""US"":25}",4917,145.0,"{""<5"":2,""5-20"":10,""21-60"":11,""61-240"":15,"">240...","{""Costco Wholesale Corp."":24,""T.J. Maxx"":12,""R...","{""Jack in the Box"":11,""Panera Bread"":11,""Targe...","{""android"":12,""ios"":11}",1
93,182641910,sg:6b77014562fb416ab28ae8ac31f907b3,Richie Heating Air Conditioning Units Services,7424 Jackson Dr,San Diego,CA,92119,US,,,...,"[0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,1,0,0,0,0,1,0...",060730097063,"{""US"":19}",9080,85.0,"{""<5"":0,""5-20"":4,""21-60"":9,""61-240"":11,"">240"":7}","{""Costco Wholesale Corp."":24,""Kaiser Permanent...","{""Costco Wholesale Corp."":36,""Carl's Jr."":19,""...","{""android"":13,""ios"":7}",1
94,182337683,sg:850a28678d7d4fa1a3df8f72aa26535c,Grow Smart Children's Academy,6271 Jackson Dr,San Diego,CA,92119,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730098024,"{""US"":4}",0,8.5,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":1,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
95,188905986,sg:aab400f89af344b6aef8d5e00241827d,Cowles Mountain Coffee,7290 Navajo Rd,San Diego,CA,92119,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730098053,"{""US"":11}",14004,7.5,"{""<5"":1,""5-20"":13,""21-60"":1,""61-240"":0,"">240"":1}","{""Chevron"":49,""Target"":24}","{""Westfield"":20,""Jack in the Box"":19,""McDonald...","{""android"":6,""ios"":13}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2969161,sg:64939c56510a413b9e33a16440f49a1f,United States Postal Service (USPS),28858 Old Highway 80,Pine Valley,CA,91962,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209022,"{""US"":8}",1852,9.5,"{""<5"":1,""5-20"":5,""21-60"":1,""61-240"":0,"">240"":1}",{},"{""McDonald's"":50,""Kahoots Pet Products"":43,""Di...","{""android"":4,""ios"":4}",1
1,24737288,sg:b7e9528b1a664a5cb95b63b674677be2,Mountain Empire Special Education Preschool,3291 Buckman Springs Rd,Pine Valley,CA,91962,US,,,...,"[0,0,0,0,0,0,0,0,5,1,0,0,0,0,1,2,2,1,0,0,0,0,0...",060730211003,"{""US"":63,""MX"":4}",18353,270.0,"{""<5"":1,""5-20"":4,""21-60"":21,""61-240"":62,"">240""...","{""McDonald's"":97}","{""Jack in the Box"":17,""Starbucks"":13,""Walmart""...","{""android"":30,""ios"":36}",1
2,26791470,sg:6224571e6e294f5fa50a9cdfb3834f5a,Major's Diner,28870 Old Highway 80,Pine Valley,CA,91962,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,2,0,0,0,0,0,0,0,1,0,0,0...",060730209022,"{""US"":26,""MX"":5}",38283,21.0,"{""<5"":0,""5-20"":14,""21-60"":13,""61-240"":3,"">240"":1}","{""CVS"":49,""HomeGoods"":20,""Chevron"":16}","{""Walmart"":24,""Starbucks"":21,""In-N-Out Burger""...","{""android"":13,""ios"":9}",1
3,104710244,sg:2020dcc60b0e40329506b214ba994ff6,Mountain Empire High,3305 Buckman Springs Rd,Pine Valley,CA,91962,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211003,"{""US"":11}",15845,10.0,"{""<5"":1,""5-20"":11,""21-60"":3,""61-240"":0,"">240"":1}","{""Wendy's"":19}","{""Albertsons"":33,""Chevron"":32,""Walmart"":28,""Si...","{""android"":4,""ios"":4}",1
4,108243779,sg:11fd209be00d4da9a947caea450d5eae,Pine Valley Store,28820 Old Highway 80,Pine Valley,CA,91962,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0...",060730209022,"{""US"":36}",34896,9.0,"{""<5"":5,""5-20"":29,""21-60"":16,""61-240"":1,"">240"":3}","{""Speedway"":11,""Tommy Hilfiger"":10,""Volkswagen...","{""Chevron"":26,""Walmart"":24,""Starbucks"":16,""Cos...","{""android"":16,""ios"":25}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,1748396,sg:80c8171264ba4358998ef8492345caec,Socal Auto Repair Center,8802 Winter Gardens Blvd,Lakeside,CA,92040,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0...",060730167023,"{""US"":4}",0,27.0,"{""<5"":1,""5-20"":1,""21-60"":2,""61-240"":2,"">240"":0}",{},{},"{""android"":4,""ios"":4}",1
204,202586315,sg:0a9da705a37a4391bb1cdf6dd91dcece,Lakeside Presb Preschool & Children's Ctr,9908 Channel Rd,Lakeside,CA,92040,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0...",060730167021,"{""US"":6}",2218,23.0,"{""<5"":1,""5-20"":7,""21-60"":5,""61-240"":4,"">240"":2}","{""Kohl's"":33,""Costco Wholesale Corp."":33}","{""Rubio's Restaurants"":20,""Jack in the Box"":19...","{""android"":4,""ios"":6}",1
211,208666063,sg:3c61a156af504e1b9dce05ebeafffe7e,JT Diesel,11982 Woodside Ave,Lakeside,CA,92040,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730167022,{},0,5.0,"{""<5"":1,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
210,209150966,sg:47d873bb609c4b75bc6b6eb445881e85,Rosarito's Mexican Food,9562 Winter Gardens Blvd,Lakeside,CA,92040,US,,,...,"[0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,1,0,1,2,0,0,0...",060730167022,"{""US"":122}",2613,14.0,"{""<5"":3,""5-20"":78,""21-60"":40,""61-240"":9,"">240"":0}","{""Walmart"":14,""Hampton"":10,""Rubio's Restaurant...","{""Starbucks"":28,""Walmart"":18,""Costco Wholesale...","{""android"":83,""ios"":42}",1
209,208566053,sg:ef2fc3f21f624dbe9d67b5acedc91a1c,Greek Chicken,9536 Winter Gardens Blvd,Lakeside,CA,92040,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,3,2,3,0,4,4,2,1,0,0,1,0...",060730167022,"{""US"":149}",3356,13.0,"{""<5"":10,""5-20"":92,""21-60"":50,""61-240"":14,"">24...","{""Grocery Outlet"":5}","{""Starbucks"":24,""7-Eleven"":17,""Walmart"":15,""Co...","{""android"":74,""ios"":76}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,3557681,sg:7118dc1b88d54b85b4ca3c43ace44192,Wynola Pizza & Bistro,4355 Highway 78,Santa Ysabel,CA,92070,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,2,0,0,0,0,0,0,0...",060730209041,"{""US"":32}",53036,23.0,"{""<5"":1,""5-20"":10,""21-60"":14,""61-240"":8,"">240"":1}","{""Kaiser Permanente"":20,""Mobil"":16,""Olive Gard...","{""Starbucks"":26,""In-N-Out Burger"":18,""Costco W...","{""android"":16,""ios"":14}",1
10,167240053,sg:e15fc1f23a084f13aee147c992bbc882,California Mountain Bakery,4367 Highway 78 Ste 101,Santa Ysabel,CA,92070,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209041,"{""US"":4}",0,21.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
17,281547821,sg:73d90861201d494d946265faacfd6617,Mountain Source Santa Ysabel,25575 Highway 79,Santa Ysabel,CA,92070,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730209033,{},0,5.5,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
16,274125772,sg:7c934d3f011d42599439e3c65171a141,Don's Market,30250 Hwy 78,Santa Ysabel,CA,92070,US,,,...,"[0,0,0,0,0,0,0,0,0,2,2,4,5,0,2,1,2,2,1,0,0,0,0...",060730209033,"{""US"":111}",30805,20.0,"{""<5"":2,""5-20"":63,""21-60"":46,""61-240"":15,"">240...","{""Mobil"":13,""Subway"":11,""Two Men And A Truck"":...","{""Starbucks"":15,""Chevron"":11,""99 Cents Only St...","{""android"":57,""ios"":51}",1
15,271999423,sg:0da0e509b03d48b18370ca18f3ef6c9e,The Barn Vintage Marketplace,4559 Highway 78,Santa Ysabel,CA,92070,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209033,"{""US"":17}",59983,12.0,"{""<5"":0,""5-20"":13,""21-60"":5,""61-240"":0,"">240"":1}","{""Albertsons"":25}","{""Walmart"":22,""Starbucks"":13,""Montage"":12,""Ral...","{""android"":15,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2968338,sg:61e350eadb364ed283e1e63ccbd2b1ec,Town & Country Animal Hospital,4055 Bonita Rd,Bonita,CA,91902,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730032071,"{""US"":5}",5662,37.0,"{""<5"":0,""5-20"":2,""21-60"":3,""61-240"":2,"">240"":0}",{},"{""Walmart"":37,""State Farm"":33,""Jack in the Box...","{""android"":6,""ios"":0}",1
1,5804462,sg:ea74022a186e4f5e8a0ab61159be3b33,Frutas 100 Natural,4232 Bonita Rd,Bonita,CA,91902,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,3,1,0,0,0,0,0...",060730134121,"{""US"":27,""MX"":4}",4774,8.0,"{""<5"":2,""5-20"":26,""21-60"":0,""61-240"":0,"">240"":1}","{""McDonald's"":47,""Hallmark Cards"":17,""7-Eleven...","{""Starbucks"":23,""Westfield"":20,""Simon mall"":20...","{""android"":18,""ios"":11}",1
102,195475558,sg:de24b0aa2a1142b199540c44efd5c2c5,Pinata District Party Supply & Candy,4240 Bonita Rd Ste B,Bonita,CA,91902,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730134121,"{""US"":4}",4504,265.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":1,"">240"":4}","{""Costco Wholesale Corp."":49}","{""Westfield"":40,""Costco Wholesale Corp."":38,""S...","{""android"":4,""ios"":4}",1
103,196328351,sg:c73669a42ad74d5c883f4b60532fc8c9,Accountants,295 Camino del Cerro Grande Ste 102,Bonita,CA,91902,US,,,...,"[1,1,0,1,0,0,0,0,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0...",060730134111,"{""US"":10}",153,41.0,"{""<5"":0,""5-20"":17,""21-60"":13,""61-240"":9,"">240""...","{""Islands Restaurants"":33,""Wings N' Things"":17...","{""Islands Restaurants"":20,""Jack in the Box"":19...","{""android"":6,""ios"":7}",1
104,202920354,sg:26becb27e25546759835ce0018b3ade1,J E T S Espresso,4502 Bonita Rd Ste A,Bonita,CA,91902,US,,,...,"[0,0,0,0,0,0,0,1,2,1,0,0,0,0,1,2,1,1,0,0,0,0,0...",060730134111,"{""US"":67}",4065,6.0,"{""<5"":10,""5-20"":50,""21-60"":14,""61-240"":2,"">240...","{""Chevron"":16,""McDonald's"":13,""ARCO"":12,""Shell...","{""Starbucks"":26,""ARCO"":22,""Jack in the Box"":15...","{""android"":41,""ios"":28}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2712579,sg:13d172018b2044238b60ace671b3d8c7,TCO Appraisals,3017 Garboso St,Carlsbad,CA,92009,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0...",060730200162,"{""US"":4}",0,66.5,"{""<5"":0,""5-20"":0,""21-60"":2,""61-240"":1,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
248,206443299,sg:7ef0c78cdab3413f8ff4f14a3c061fdb,Casero Taqueria,2674 Gateway Rd Ste 195,Carlsbad,CA,92009,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,2,0,0,0,0,2,4,3,0,0,0,0...",060730200131,"{""US"":95}",6388,61.0,"{""<5"":1,""5-20"":12,""21-60"":40,""61-240"":46,"">240...","{""The Bar Method"":9,""NÃ©kter Juice Bar"":9,""Sim...","{""Starbucks"":18,""Costco Wholesale Corp."":13,""T...","{""android"":28,""ios"":67}",1
246,205603660,sg:0554df5b8ccb4978a67da3cdf51aa20d,Shelley Lee Boyce,2784 Gateway Rd Ste 102,Carlsbad,CA,92009,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730200133,"{""US"":4}",0,87.0,"{""<5"":0,""5-20"":1,""21-60"":4,""61-240"":2,"">240"":4}",{},{},"{""android"":4,""ios"":0}",1
245,203964168,sg:fce12d828325432fa8dfeaf4ad694dba,La Costa Glen,1940 Levante St,Carlsbad,CA,92009,US,,,...,"[1,0,0,0,0,0,2,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0...",060730176013,"{""US"":12}",11055,83.0,"{""<5"":0,""5-20"":9,""21-60"":4,""61-240"":13,"">240"":6}","{""Bowlero"":33,""Goodwill Industries"":33,""Shell ...","{""Panera Bread"":24,""Ross Stores"":16,""7-Eleven""...","{""android"":5,""ios"":8}",1
244,204396357,sg:01b6adf77bf44a62920bd9550f008f3c,Faith Community Church,2700 Rancho Pancho,Carlsbad,CA,92009,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730200133,"{""US"":25}",10893,108.0,"{""<5"":1,""5-20"":2,""21-60"":3,""61-240"":24,"">240"":1}","{""Jersey Mike's"":33,""lululemon athletica"":25,""...","{""In-N-Out Burger"":29,""PetSmart"":16,""Chick-fil...","{""android"":7,""ios"":14}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4863905,sg:9856cc6072a64baa9ff38ee71a45aa4e,Peppertree Montessori,427 College Blvd Ste I,Oceanside,CA,92057,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1...",060730185071,"{""US"":20}",3083,58.0,"{""<5"":1,""5-20"":15,""21-60"":5,""61-240"":8,"">240"":12}","{""Black Angus Steakhouse"":17,""CrossFit"":16,""Co...","{""Costco Wholesale Corp."":18,""Shell Oil"":17,""P...","{""android"":10,""ios"":9}",1
142,211676032,sg:d9ed2a53611544c2b018165ad9b8a92b,McDonald's,487 College Blvd,Oceanside,CA,92057,US,SG_BRAND_5179b21fc1d50950b99b4eecaa48c614,McDonald's,...,"[0,0,0,0,1,0,0,0,1,1,3,6,3,3,4,1,4,1,1,1,4,0,0...",060730185071,"{""US"":180,""MX"":4}",3615,9.0,"{""<5"":11,""5-20"":163,""21-60"":23,""61-240"":20,"">2...","{""Starbucks"":7,""PetSmart"":7,""Taco Bell"":6,""Wal...","{""Walmart"":24,""Starbucks"":18,""7-Eleven"":14,""Ja...","{""android"":90,""ios"":95}",1
132,193801287,sg:f92bc8b3d6484425b2c02231405d3f85,Sally Beauty Supply,825 College Blvd Ste 103,Oceanside,CA,92057,US,SG_BRAND_57bdb072ef4ee4c0fcd12ab460b8466f,Sally Beauty Supply,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730185141,"{""US"":4}",0,10.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
133,195783872,sg:1f5fbf8fa94d49c7a8d1d841ef43bdbc,Victoria's Mexican Food,495 College Blvd Ste C,Oceanside,CA,92057,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,3,2,4,4,2,1,1,1,0,0,0,0...",060730185071,"{""US"":76}",5869,14.0,"{""<5"":2,""5-20"":49,""21-60"":27,""61-240"":1,"">240"":0}","{""United States Postal Service (USPS)"":14,""Dol...","{""Starbucks"":16,""In-N-Out Burger"":14,""Target"":...","{""android"":34,""ios"":41}",1
134,197510243,sg:09eea0076ed848099f518bf31dc4f25f,GNC (General Nutrition Centers),835 College Blvd,Oceanside,CA,92057,US,SG_BRAND_4709e5fc9280fbd74e23d1d4f930841b,GNC (General Nutrition Centers),...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0...",060730185141,"{""US"":5}",2908,49.5,"{""<5"":0,""5-20"":2,""21-60"":4,""61-240"":2,"">240"":0}","{""GameStop"":33}","{""Starbucks"":24,""Burn Boot Camp"":14,""Vons"":14,...","{""android"":5,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,2706355,sg:8aa244bb07e240038b3e9d4079ff3980,Ice Cream Depot,3509 Sweetwater Springs Blvd Ste 3,Spring Valley,CA,91978,US,,,...,"[0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,1,0,0,0,0...",060730135051,"{""US"":39}",7134,35.0,"{""<5"":2,""5-20"":18,""21-60"":15,""61-240"":17,"">240...","{""Red Lobster"":17,""Little Caesars"":16,""Costco ...","{""Jack in the Box"":19,""Starbucks"":18,""24 Hour ...","{""android"":7,""ios"":31}",1
50,214455589,sg:1363bc44eb3245b691ed2950f6690356,Liberty Call Distilling LLC,2739 Via Orange Way Ste 110,Spring Valley,CA,91978,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730135053,"{""US"":4}",0,10.0,"{""<5"":0,""5-20"":7,""21-60"":2,""61-240"":2,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
57,232303232,sg:b22a9099b2ff4c6ea3b5ab707db5801d,Circle K,11906 Campo Rd,Spring Valley,CA,91978,US,SG_BRAND_4cbffa4318cebdb09227afca3fe16846,Circle K,...,"[0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,2,0,2,1,0,0,1...",060730136062,"{""US"":44}",12083,6.0,"{""<5"":7,""5-20"":36,""21-60"":7,""61-240"":2,"">240"":0}","{""Michaels Stores"":33,""Albertsons"":20,""Mobil"":...","{""Starbucks"":17,""Target"":14,""Albertsons"":14,""J...","{""android"":32,""ios"":19}",1
56,231069719,sg:6fb5eeecf7ea4ba9a18ddac87aa34549,Wienerschnitzel,3523 Sweetwater Springs Blvd,Spring Valley,CA,91978,US,SG_BRAND_a8538498c68190d305f7b19f24efd71c,Wienerschnitzel,...,"[0,0,0,0,0,0,0,0,0,0,0,2,2,1,1,0,0,1,1,0,1,1,0...",060730135051,"{""US"":53}",4116,9.0,"{""<5"":5,""5-20"":49,""21-60"":7,""61-240"":1,"">240"":0}","{""Applebee's"":20,""Taco Bell"":19,""Hallmark Card...","{""Starbucks"":24,""Jack in the Box"":23,""Target"":...","{""android"":33,""ios"":21}",1
55,228907584,sg:6e88a1ce21864c24b4084132bcc4b832,Atonement Lutheran Church Missouri Synod,10245 Loma Rancho Dr,Spring Valley,CA,91978,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0...",060730135051,"{""US"":9}",6341,101.0,"{""<5"":0,""5-20"":2,""21-60"":6,""61-240"":5,"">240"":5}","{""Jamba"":25,""IHOP"":25,""Target"":24}","{""Crunch"":17,""Target"":13,""Coco's Bakery Restau...","{""android"":6,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4798025,sg:1b51babb5d994271844cc5d74b787039,The Habit Burger Grill,5500 Campanile Dr. Aztec Student Union,San Diego,CA,92182,US,SG_BRAND_f06de432fc340ee71aa12222d087ce84,The Habit Burger Grill,...,"[0,0,0,0,0,0,1,0,0,1,1,2,3,2,4,1,1,1,1,3,0,0,0...",060730028012,"{""US"":412,""MX"":5,""TR"":4}",20011,25.0,"{""<5"":9,""5-20"":238,""21-60"":204,""61-240"":145,"">...","{""Juice It Up!"":34}","{""Juice It Up!"":49,""Westfield"":20,""Starbucks"":...","{""android"":139,""ios"":289}",1
13,138981843,sg:154b36a56f7a4df8b9262e0833e18e0b,Salad Bistro,5500 Campanile Dr,San Diego,CA,92182,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,2,1,0,1,2,0,0,0...",060730028012,"{""US"":101}",17779,21.0,"{""<5"":8,""5-20"":62,""21-60"":11,""61-240"":25,"">240...","{""Juice It Up!"":13,""McDonald's"":11,""Subway"":5}","{""Juice It Up!"":30,""The Habit Burger Grill"":18...","{""android"":34,""ios"":68}",1
23,272635889,sg:8d5221c73df6494dacb37ba175c657f1,Juice It Up!,5200 Campanile Ave East Commons Bldg,San Diego,CA,92182,US,SG_BRAND_c0bca08bc6a7fbcf59559b9a67e51e08,Juice It Up!,...,"[0,0,0,0,0,2,1,0,2,2,5,4,9,1,2,4,4,0,0,0,0,0,0...",060730028012,"{""US"":812,""MX"":10,""PH"":4,""BR"":4}",19022,40.0,"{""<5"":15,""5-20"":392,""21-60"":474,""61-240"":412,""...","{""The Habit Burger Grill"":12,""Starbucks"":11,""T...","{""The Habit Burger Grill"":26,""Starbucks"":18,""W...","{""android"":234,""ios"":603}",1
22,272747446,sg:43bc517aaeef41768358a032e0d3f0e3,Parking Structure 6,1200 Zura Way San Diego State University,San Diego,CA,92182,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,2,1,1,0,1,0,1,0,0,0,0,0...",060730028012,"{""US"":47}",21712,26.0,"{""<5"":3,""5-20"":28,""21-60"":6,""61-240"":23,"">240"":5}","{""Yum Yum Donuts"":25,""The Salvation Army"":25,""...","{""The Salvation Army"":22,""Starbucks"":22,""Westf...","{""android"":13,""ios"":34}",1
21,266367673,sg:500b694e9513431db2474b77f9d57229,Associated Students Child Care Center Infant Ctr,5500 Campanile Dr,San Diego,CA,92182,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730028012,"{""US"":19}",17325,63.0,"{""<5"":0,""5-20"":2,""21-60"":8,""61-240"":14,"">240"":1}","{""Juice It Up!"":50,""Target"":24,""Trader Joe's"":...","{""The Habit Burger Grill"":61,""Juice It Up!"":57...","{""android"":0,""ios"":20}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4863943,sg:9994e709bed541fd9b677cf0f99acaab,Bdo,3570 Carmel Mountain Rd Ste 400,San Diego,CA,92130,US,,,...,"[1,0,0,0,0,0,0,2,2,2,0,1,1,0,0,0,3,0,0,0,0,0,0...",060730083332,"{""US"":13}",16762,175.5,"{""<5"":0,""5-20"":6,""21-60"":6,""61-240"":39,"">240"":19}","{""Wells Fargo"":11,""LA Fitness"":11,""Starbucks"":...","{""Starbucks"":28,""Mutual of Omaha Bank"":20,""Yog...","{""android"":4,""ios"":10}",1
330,192829162,sg:7855356348b646ba927c100e146e98e1,The League of Amazing Programmers,12625 High Bluff Dr Ste 113,San Diego,CA,92130,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083291,"{""US"":4}",0,207.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":6,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
343,200416610,sg:4345192762684d5497eef6feae8126e3,Sammy's Woodfired Pizza and Grill,1 2 9 2 5 El Camino Real 12925 El Camino Real,San Diego,CA,92130,US,SG_BRAND_3d4fd9a07fad4127,Sammy's Woodfired Pizza and Grill,...,"[0,0,0,0,0,0,0,0,2,0,0,0,2,0,1,1,1,1,0,0,0,0,0...",060730083291,"{""US"":37}",6980,26.0,"{""<5"":1,""5-20"":16,""21-60"":5,""61-240"":10,"">240"":5}","{""Lorna Jane"":25,""Vons"":17,""McDonald's"":13,""St...","{""Starbucks"":31,""Vons"":22,""McDonald's"":17,""Wes...","{""android"":4,""ios"":28}",1
342,200822448,sg:bca1a641150a41a98a57241722be1b4d,Little Rookies T Ball School,3830 Valley Centre Dr Ste 705 113,San Diego,CA,92130,US,,,...,"[0,0,0,0,0,0,0,2,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0...",060730083292,"{""US"":37}",3068,12.0,"{""<5"":2,""5-20"":23,""21-60"":10,""61-240"":2,"">240"":0}","{""Starbucks"":27,""Souplantation"":20,""Sammy's Wo...","{""Starbucks"":28,""Westfield"":21,""Baskin Robbins...","{""android"":16,""ios"":19}",1
341,200387099,sg:bd2e858a29e340c091c20425548ab9c8,Yoga Six,4639 Carmel Mountain Rd Ste 102,San Diego,CA,92130,US,SG_BRAND_3789066f2367a5be,Yoga Six,...,"[0,0,0,0,0,0,1,1,3,2,3,3,0,1,0,0,1,1,1,2,0,0,0...",060730083331,"{""US"":81}",3932,52.0,"{""<5"":1,""5-20"":8,""21-60"":46,""61-240"":46,"">240"":0}","{""Burger Lounge"":11,""Bank of America"":9,""T.J. ...","{""Starbucks"":31,""Westfield"":25,""Vons"":19,""Shel...","{""android"":30,""ios"":55}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4271595,sg:86d43ebfe3174740a0c8eaf4f370e0e4,Office Depot,920 Eastlake Pkwy,Chula Vista,CA,91914,US,SG_BRAND_9575df69ce667567,Office Depot,...,"[0,0,0,0,0,0,0,0,0,2,3,2,2,1,2,3,3,0,2,0,2,0,0...",060730134192,"{""US"":119,""MX"":4}",3048,16.0,"{""<5"":5,""5-20"":86,""21-60"":40,""61-240"":16,"">240...","{""Target"":30,""The Home Depot"":9,""McDonald's"":8...","{""Target"":25,""Starbucks"":20,""Walmart"":20,""Cost...","{""android"":52,""ios"":68}",1
105,148967081,sg:36ae2c495d184fcb8f17f2f00c86dbb3,Aaron Chaney Fitness,2381 Boswell Rd,Chula Vista,CA,91914,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730134192,"{""US"":4}",5623,15.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":1,"">240"":0}","{""Jack in the Box"":100,""Baskin Robbins"":50}","{""Westfield"":43,""Carl's Jr."":28,""Jack in the B...","{""android"":8,""ios"":0}",1
133,198861566,sg:71b6825485564003a77829d2c512d4a7,The Phana Par Group at Caliber Home Loans,877 Anchorage Pl,Chula Vista,CA,91914,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0...",060730134191,"{""US"":4}",0,62.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":4,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
134,199006173,sg:2baf34ef241f43b4a51af07608feee58,Foundry United Methodist Church,861 Harold Pl,Chula Vista,CA,91914,US,,,...,"[0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0...",060730134191,"{""US"":4}",0,225.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":4,"">240"":4}",{},{},"{""android"":4,""ios"":0}",1
135,199598280,sg:f0d2f948310f4c05954363cf68d74fbd,Credit Corner,2571 Mast Way Ste 202,Chula Vista,CA,91914,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0...",060730134191,{},0,99.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4753456,sg:84534769c2954936af86ad09b38fc211,Fat Anthony's Delicatessen,2818 4th St,Julian,CA,92036,US,,,...,"[0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,0,3,1,0,0,0,0,0...",060730209043,"{""US"":21}",63293,40.0,"{""<5"":0,""5-20"":7,""21-60"":16,""61-240"":2,"">240"":5}","{""Haagen Dazs"":50,""Trader Joe's"":50,""Simon mal...","{""Costco Wholesale Corp."":25,""ARCO"":22,""Jack i...","{""android"":10,""ios"":11}",1
54,189088004,sg:6a7f63c88b20443194dc17ffe4002ba4,All State Propane,3582 Highway 78,Julian,CA,92036,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0...",060730209041,"{""US"":4}",56705,80.0,"{""<5"":1,""5-20"":3,""21-60"":3,""61-240"":4,"">240"":4}",{},"{""Benihana"":17,""Petco"":16,""7-Eleven"":15,""Chevr...","{""android"":4,""ios"":0}",1
62,221787372,sg:0d0b695b84664de1b0e6bfeffb498813,Julian Homes and Happenings,1933 Main St,Julian,CA,92036,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0...",060730209043,"{""US"":7}",60187,16.0,"{""<5"":1,""5-20"":5,""21-60"":3,""61-240"":2,"">240"":0}",{},"{""Trader Joe's"":27,""NÃ©kter Juice Bar"":18,""In-...","{""android"":6,""ios"":6}",1
61,219593611,sg:ccd936f210fe4571b02ae285a2b1143f,Redding Ray High Continuation,1517 Highway 78,Julian,CA,92036,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209043,"{""US"":5}",0,38.5,"{""<5"":0,""5-20"":4,""21-60"":10,""61-240"":2,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
60,218184188,sg:603139160b4344a8beff9205d8a10602,La Cima Conservation Camp 42,15108 Sunrise Hwy,Julian,CA,92036,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209021,"{""US"":5}",0,364.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":2,"">240"":6}",{},{},"{""android"":0,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,3858857,sg:2e4d0d73dbbf4d9d9e7d8519d543c30a,Drain Crew,3141 Tiger Run Ct Ste 108,Carlsbad,CA,92010,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730198063,"{""US"":10}",7209,61.0,"{""<5"":0,""5-20"":5,""21-60"":2,""61-240"":7,"">240"":0}","{""Starbucks"":98,""Lazy Acres Natural Market"":33...","{""Chevron"":26,""Starbucks"":22,""Swami's Cafe"":18...","{""android"":4,""ios"":8}",1
98,225010901,sg:205bb335c7374d11b2e122940ea35288,Schreyer Audio,2720 Loker Ave W,Carlsbad,CA,92010,US,,,...,"[0,0,0,0,0,0,0,0,5,1,5,2,1,1,0,0,2,0,0,0,0,0,0...",060730198063,"{""US"":48}",9173,108.0,"{""<5"":3,""5-20"":17,""21-60"":21,""61-240"":62,"">240...","{""Crunch"":20,""Boys & Girls Clubs of America"":7...","{""Shell Oil"":13,""Chevron"":11,""Costco Wholesale...","{""android"":29,""ios"":16}",1
96,221686921,sg:83e7d76628314709946d335470f722b8,Carlsbad Training Camp,5751 Palmer Way Ste E,Carlsbad,CA,92010,US,,,...,"[0,0,0,0,0,0,2,1,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0...",060730198063,"{""US"":25}",10650,68.5,"{""<5"":2,""5-20"":11,""21-60"":6,""61-240"":12,"">240"":9}","{""Carl's Jr."":20,""CrossFit"":20,""7-Eleven"":20,""...","{""Walmart"":19,""Chevron"":18,""The Home Depot"":18...","{""android"":18,""ios"":4}",1
95,222874133,sg:bc9c488755444de8aa3f404ec0e5dc35,Frank Financial Advisors,2710 Loker Ave W Ste 230,Carlsbad,CA,92010,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730198063,"{""US"":4}",0,99.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
94,216612738,sg:cf11428987d54655b4f645386c5aeb93,Build at Home Skateparks,2777 Loker Ave W,Carlsbad,CA,92010,US,,,...,"[1,0,1,0,0,2,9,3,4,0,5,0,3,2,4,0,5,1,0,0,0,0,2...",060730198063,"{""US"":87}",13345,49.0,"{""<5"":6,""5-20"":58,""21-60"":65,""61-240"":39,"">240...","{""EoS Fitness"":8,""Jack in the Box"":8,""Circle K...","{""Shell Oil"":15,""ARCO"":12,""Chevron"":8,""Starbuc...","{""android"":63,""ios"":36}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,4889029,sg:fde1d6c235a140b491ef6a8b8103da8a,Leatherneck Lanes,1339 Vandegrift Blvd,Oceanside,CA,92055,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730186081,{},0,5.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
45,173824203,sg:69bba9c41e7840879d40320cccae9208,Subway,Building 15102 Marine Corps Base,Camp Pendleton,CA,92055,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0...",060730187001,"{""US"":43}",9892,16.5,"{""<5"":1,""5-20"":31,""21-60"":18,""61-240"":2,"">240"":4}","{""Panda Express"":33,""Walmart"":27,""McDonald's"":...","{""Panda Express"":20,""McDonald's"":20,""ARCO"":13,...","{""android"":14,""ios"":29}",1
51,192262424,sg:86221388e2994bf4a784d9d5ae9b5aaf,McDonald's,430314 Brown St,Camp Pendleton,CA,92055,US,SG_BRAND_5179b21fc1d50950b99b4eecaa48c614,McDonald's,...,"[0,1,0,0,0,0,0,0,1,2,1,1,1,1,1,3,4,1,2,0,1,1,1...",060730187001,"{""US"":205}",8472,8.0,"{""<5"":19,""5-20"":183,""21-60"":28,""61-240"":11,"">2...","{""HearUSA"":13,""H&R Block"":7,""Bank of America"":7}","{""United States Postal Service (USPS)"":12,""Pan...","{""android"":110,""ios"":103}",1
50,186068729,sg:4abd172850624f77bb0224b5add233a3,Pendleton Family Dental,U S Marine Corps Base Library Bldg 555020 Ste ...,Camp Pendleton,CA,92055,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730187001,"{""US"":40}",10300,29.0,"{""<5"":0,""5-20"":19,""21-60"":15,""61-240"":10,"">240...","{""McDonald's"":17,""Albertsons"":17,""Wendy's"":7}","{""McDonald's"":32,""Panda Express"":22,""Domino's ...","{""android"":22,""ios"":23}",1
49,179494998,sg:a7b1be95e31745b993efc34afb48567f,United States Postal Service (USPS),33307 A St,Camp Pendleton,CA,92055,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730187001,"{""US"":16}",12107,63.0,"{""<5"":1,""5-20"":5,""21-60"":11,""61-240"":9,"">240"":8}","{""ARCO"":10}","{""McDonald's"":15,""ARCO"":11,""Panera Bread"":10,""...","{""android"":10,""ios"":6}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,5350823,sg:9039fc3dfa094bda8f825932081aad9b,Bonsall Flowers and Gifts,5266 S Mission Rd,Bonsall,CA,92003,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2,1,0,0,0,0,0,0...",060730188021,"{""US"":27}",8413,39.0,"{""<5"":1,""5-20"":9,""21-60"":11,""61-240"":10,"">240"":5}","{""Jack in the Box"":100,""Blaze Pizza"":12,""Costc...","{""ARCO"":21,""Jack in the Box"":21,""Costco Wholes...","{""android"":5,""ios"":15}",1
1,5589201,sg:0d5414e5f5a74ddc8ee403eb269c4b56,Outrider Motorcycles,30161 Hwy 76,Bonsall,CA,92003,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730188033,{},0,21.0,"{""<5"":0,""5-20"":0,""21-60"":2,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
34,147439985,sg:a063807a164c425f979c2d98be2b53bd,San Luis Rey River Park,San Luis Rey River Park,San Diego,CA,92003,US,,,...,"[0,1,0,0,0,1,0,1,1,0,0,0,2,0,1,2,0,0,0,0,0,0,0...",060730188031,"{""US"":34}",6563,26.0,"{""<5"":2,""5-20"":17,""21-60"":15,""61-240"":8,"">240"":5}","{""Hobby Lobby Stores"":25,""Restaurant Depot"":7,...","{""ARCO"":10,""Costco Wholesale Corp."":9,""Jack in...","{""android"":12,""ios"":22}",1
35,155171310,sg:2dc6c5e906be4e6fb9ba2cf106bc5afd,Rainbow Meal Worms,4246 Holly Ln,Bonsall,CA,92003,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730186121,"{""US"":4}",0,450.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1
36,162506272,sg:91f24ce69cad46f1b7429fea61f4e2a6,Bonsall Fine Wine and Spirits,5256 S Mission Rd Ste 841,Bonsall,CA,92003,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0...",060730188021,"{""US"":13}",5498,9.5,"{""<5"":0,""5-20"":11,""21-60"":2,""61-240"":0,"">240"":1}","{""Carl's Jr."":50,""Albertsons"":25,""Costco Whole...","{""Kahoots Pet Products"":15,""In-N-Out Burger"":1...","{""android"":4,""ios"":8}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,7165544,sg:82ce394815ff492d9d48e3241f359c9a,Fleet and Family Support Center,3005 Corbina Aly Ste 1,San Diego,CA,92136,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730038001,"{""US"":14}",14043,22.0,"{""<5"":0,""5-20"":7,""21-60"":10,""61-240"":4,"">240"":0}","{""EarthWise Pet Supply"":20}","{""Navy Exchange"":26,""Subway"":12,""Starbucks"":11...","{""android"":12,""ios"":8}",1
26,201883962,sg:d7721ae027384693bdb3abbe6956b4b6,MAC Cosmetics,2260 Callagan Hwy Bldg 3187,San Diego,CA,92136,US,SG_BRAND_58e2e2ddc4008302e9cdd190f7f7f1e8,MAC Cosmetics,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730038001,{},0,7.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
20,156754406,sg:32732ddcce594827a755e4b1fe198764,Admiral Robinson Recreation Centre,2375 Recreation Way Bldg 3223,San Diego,CA,92136,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,3,2,0,0,0,0,0,0,0,0,0...",060730219002,"{""US"":65}",10509,28.5,"{""<5"":1,""5-20"":38,""21-60"":38,""61-240"":23,"">240...","{""Navy Exchange"":33,""CrossFit"":6,""Chick-fil-A""...","{""Navy Exchange"":37,""Subway"":15,""Bruegger's"":9...","{""android"":43,""ios"":26}",1
21,166312588,sg:a9837a7fe1544743bebe6ab0e34b5e20,Navy Federal Credit Union Restricted Access,2505 Callagan Hwy,San Diego,CA,92136,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0...",060730038001,"{""US"":55}",11131,18.0,"{""<5"":1,""5-20"":43,""21-60"":11,""61-240"":18,"">240...","{""Chevron"":99,""Subway"":13,""Valvoline"":8,""ARCO"":7}","{""Navy Exchange"":57,""Subway"":17,""Chevron"":16,""...","{""android"":31,""ios"":28}",1
22,174128074,sg:c6c9d0d8c0474feba6bcc2884d9eab8f,Bruegger's,3705 Norman Scott Rd Bldg 3631,San Diego,CA,92136,US,SG_BRAND_51da2a22f584d0f11bb45e1307bbaefe,Bruegger's,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,2,0,0,0,0,0...",060730038001,"{""US"":26}",114,862.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":40}","{""Ross Stores"":8}","{""Subway"":17,""Navy Exchange"":14,""Chevron"":5}","{""android"":16,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,6299861,sg:8e5b126e65e34a09b23f91eb4767adeb,Gems of Pala,35940 Magee Rd,Pala,CA,92059,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730191011,"{""US"":4}",0,99.5,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
1,8919576,sg:13d5a3e5fb6e482fab07d208b007ee38,Pala Fitness Center,12194 Pala Mission Rd,Pala,CA,92059,US,,,...,"[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191011,"{""US"":14}",20364,27.0,"{""<5"":2,""5-20"":5,""21-60"":4,""61-240"":7,"">240"":1}","{""The Habit Burger Grill"":12,""Ross Stores"":12}","{""Wells Fargo"":37,""Walmart"":37,""Vons"":31,""ARCO...","{""android"":15,""ios"":0}",1
18,278701220,sg:d20d91687e4b44558254db31a3705891,Cave,Pala Casino Spa Resort 11154 Hwy 76,Pala,CA,92059,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0...",060730191013,"{""US"":15}",62111,616.0,"{""<5"":1,""5-20"":2,""21-60"":2,""61-240"":0,"">240"":14}","{""Denny's"":25,""Starbucks"":23,""ARCO"":20,""Walmar...","{""ARCO"":21,""Simon mall"":15,""Walmart"":13,""Starb...","{""android"":9,""ios"":7}",1
17,269367486,sg:ecd3df112a6244fdb61638ded2b13d83,Mission San Antonio De Pala,3015 Pala Mission Rd,Pala,CA,92059,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191014,"{""US"":4}",211,55.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":2,"">240"":0}","{""Food 4 Less"":100}","{""Walgreens"":37,""Walmart"":27,""Kahoots Pet Prod...","{""android"":4,""ios"":0}",1
16,265489320,sg:6524b3e357974272839c85dbeda18a64,Pala Reservation Fire Department,34884 Lilac Extension Rd,Pala,CA,92059,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191013,"{""US"":4}",25050,116.0,"{""<5"":0,""5-20"":7,""21-60"":1,""61-240"":3,"">240"":6}",{},"{""Walmart"":67,""Bass Pro Shops"":40,""Ross Stores...","{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,6438153,sg:e3a477c061f14c63a7bb20be3bec1ece,SD Prime Limo Service,10601 Tierrasanta Blvd Ste 234,San Diego,CA,92124,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730095092,{},0,7.5,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
97,202066502,sg:23e42d88ef374b0a894e405f516cd030,Spa No 5,10211 Waddell Cir,San Diego,CA,92124,US,,,...,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,3,2,1,0,0,0,0...",060730095103,"{""US"":16}",1020,228.0,"{""<5"":1,""5-20"":5,""21-60"":12,""61-240"":14,"">240""...","{""Navy Exchange"":33,""The Coffee Bean & Tea Lea...","{""Vons"":44,""McDonald's"":30,""Navy Exchange"":25,...","{""android"":13,""ios"":8}",1
91,187230403,sg:f2e7a736b50a40afb4bed935ef39d0fe,Lucas River Drums,4786 Quito Ct,San Diego,CA,92124,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730095051,"{""US"":4}",23503,10.0,"{""<5"":0,""5-20"":6,""21-60"":3,""61-240"":2,"">240"":0}","{""The Coffee Bean & Tea Leaf"":100}","{""Costco Wholesale Corp."":31,""The Coffee Bean ...","{""android"":6,""ios"":4}",1
92,185914839,sg:8df68ab9074f4ece987cd2bfa3b2aab9,Canine Cleaners,10448 Clairemont Mesa Blvd,San Diego,CA,92124,US,,,...,"[0,0,0,0,0,0,0,1,1,1,0,0,3,0,0,0,2,0,0,2,0,1,0...",060730095021,"{""US"":72}",1992,20.0,"{""<5"":0,""5-20"":44,""21-60"":25,""61-240"":15,"">240...","{""Creamistry"":20,""Subway"":19,""McDonald's"":9,""K...","{""Starbucks"":24,""Vons"":23,""Westfield"":20,""McDo...","{""android"":33,""ios"":37}",1
93,189327777,sg:924efca22d4745449114e01d40c620ff,Tierrasanta Lutheran Church,11240 Clairemont Mesa Blvd,San Diego,CA,92124,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730095053,"{""US"":4}",0,128.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":5,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,8433159,sg:2ccb4e0f235740ac9050589405b35cb9,Top3Dentists com,3953 Stonebridge Ln Ste 108,Rancho Santa Fe,CA,92091,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730171061,"{""US"":8}",7658,147.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":4,"">240"":2}","{""Maui Wowi"":14}","{""McDonald's"":42,""Panera Bread"":37,""7-Eleven"":...","{""android"":4,""ios"":6}",1
16,124084969,sg:82735387a37b40e886fa60e6603d55aa,Allstate Insurance,16236 San Dieguito Rd Ste 131,Rancho Santa Fe,CA,92091,US,SG_BRAND_5a9e6695c8055aeb6c210e6bfb45d6b5,Allstate Insurance,...,"[0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0...",060730170292,"{""US"":9}",3988,39.5,"{""<5"":0,""5-20"":15,""21-60"":9,""61-240"":10,"">240"":6}","{""Oggi's"":50,""Panera Bread"":33,""Charles Schwab...","{""Panera Bread"":26,""Oggi's"":20,""HomeGoods"":20,...","{""android"":7,""ios"":7}",1
29,282301105,sg:d7d00cfad677495f966c9cb65602f870,Von Henkle Equestrian,18539 Via De Las Fl Ores,Rancho Santa Fe,CA,92091,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730171101,{},0,119.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
28,266899739,sg:35fe31452b2f4761a5bc5458febc8448,Rancho Riding Club,16924 Rambla De Las Fl Ores,Rancho Santa Fe,CA,92091,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0...",060730171061,"{""US"":7}",1757,48.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":5,"">240"":0}",{},"{""Kahoots Pet Products"":14,""Islands Restaurant...","{""android"":0,""ios"":4}",1
27,252703329,sg:4af1a93cc6c64335aa926ebc04755336,Kupiec Orthodontics & Pediatric Dentistry,16236 San Dieguito Rd Ste 2 22,Rancho Santa Fe,CA,92091,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730170292,{},0,10.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,8331563,sg:8b85f0c4ab7e4d4587ee7e71cc6b768a,Village Nurseries,17325 Highway 76,Pauma Valley,CA,92061,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191011,{},0,4.0,"{""<5"":2,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
1,33488094,sg:74f3d59cfa344717ad4feda58aa350bd,Maac Project Pauma Valley Headstart State Pres...,33158A Cole Grade Rd,Pauma Valley,CA,92061,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191012,"{""US"":9}",23924,25.0,"{""<5"":1,""5-20"":7,""21-60"":4,""61-240"":3,"">240"":4}","{""Jimbo's"":25}","{""Costco Wholesale Corp."":31,""99 Cents Only St...","{""android"":5,""ios"":4}",1
22,269683291,sg:d42e8c3d06c64e378fbc649067476e9d,Kica Mik Overlook,S Grade Rd,Pauma Valley,CA,92061,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209031,"{""US"":4}",0,14.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
21,268205915,sg:04dc3e5e3ed844aebbcd32152963af0c,St Francis Episcopal Church,16608 Highway 76,Pauma Valley,CA,92061,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730191011,{},0,10.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",1
20,253850906,sg:e5a3ea92998a4ae2ba9076ac64bb442b,Pauma Valley Trading Center,16220 Hwy 76,Pauma Valley,CA,92061,US,,,...,"[0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,1,1,0,1,0,0,0,0...",060730191011,"{""US"":46}",17068,28.0,"{""<5"":0,""5-20"":24,""21-60"":19,""61-240"":12,"">240...","{""Chipotle Mexican Grill"":16,""Chevron"":12,""ARC...","{""Starbucks"":14,""Costco Wholesale Corp."":13,""7...","{""android"":26,""ios"":19}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,11884000,sg:da29b0d928fc4734b720a542f389dfae,Descanso Hay & Feed,25077 Viejas Blvd,Descanso,CA,91916,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730212021,"{""US"":5}",5665,19.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":1,"">240"":2}",{},"{""Kahoots Pet Products"":33,""Walmart"":20,""Uptow...","{""android"":4,""ios"":0}",1
1,12650763,sg:dcea8f178fb7473785dd51d3972eaddb,Descanso Branch Library,9545 River Dr,Descanso,CA,91916,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0...",060730212021,"{""US"":7}",18084,9.5,"{""<5"":0,""5-20"":4,""21-60"":2,""61-240"":0,"">240"":0}","{""Walmart"":44}","{""Starbucks"":35,""Walmart"":27,""DixieLine"":20,""T...","{""android"":4,""ios"":0}",1
2,27692449,sg:77348be899cc4094a6df3d2f48b51211,Descanso Elementary,24842 Viejas Blvd,Descanso,CA,91916,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730212021,"{""US"":18}",13758,27.0,"{""<5"":1,""5-20"":12,""21-60"":16,""61-240"":4,"">240"":6}","{""Target"":10}","{""McDonald's"":17,""Walmart"":17,""Starbucks"":15,""...","{""android"":12,""ios"":7}",1
3,37125033,sg:60ce97d2883a4dd2822ac95e687462b9,Descanso Mercantile,8306 Highway 79,Descanso,CA,91916,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,1,1,5,0,0,2,1,1,0,0,1,0...",060730212021,"{""US"":62}",15401,47.0,"{""<5"":1,""5-20"":10,""21-60"":40,""61-240"":25,"">240...","{""Albertsons"":20,""Ross Stores"":13,""PPG Pittsbu...","{""Chevron"":17,""Walmart"":15,""Sinclair Oil"":14,""...","{""android"":32,""ios"":32}",1
4,54390593,sg:a48c676d86984b04bef72f1f2c0a5bb7,Amos Fence,9163 Riverside Dr,Descanso,CA,91916,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730212021,{},0,69.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,11599895,sg:396e6d5b325445fabe803da525879051,Greater San Diego Academy,13881 Campo Rd,Jamul,CA,91935,US,,,...,"[0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0...",060730213033,"{""US"":33}",11486,12.0,"{""<5"":3,""5-20"":28,""21-60"":5,""61-240"":6,"">240"":1}","{""Motel 6"":25,""Burger King"":24,""Fuddruckers"":2...","{""7-Eleven"":24,""Starbucks"":20,""ARCO"":19,""Targe...","{""android"":26,""ios"":8}",1
1,13017925,sg:6c42c3f42cd44568b402a44570b03849,coyote canyon Cafe,14615 Otay Lakes Rd,Jamul,CA,91935,US,,,...,"[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730213021,"{""US"":4,""MX"":4}",0,638.5,"{""<5"":1,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":4}","{""7-Eleven"":100}","{""Baskin Robbins"":40,""7-Eleven"":39,""True Value...","{""android"":0,""ios"":4}",1
32,199144989,sg:93ca53b9ea6940b096d2d62df6b8f7bb,Tony Gwynn's Sports Pub,14145 Campo Rd,Jamul,CA,91935,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730213041,"{""US"":13}",16835,5.0,"{""<5"":2,""5-20"":9,""21-60"":0,""61-240"":1,"">240"":1}","{""KFC"":50}","{""Chevron"":29,""7-Eleven"":22,""CVS"":21,""Wetzel's...","{""android"":6,""ios"":7}",1
33,201518499,sg:8daa15b84b69495fb82c55867deabdca,Jamul Dulzura Union School District Preschool,14545 Lyons Valley Rd,Jamul,CA,91935,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730213042,"{""US"":7}",7962,25.5,"{""<5"":0,""5-20"":4,""21-60"":3,""61-240"":1,"">240"":0}","{""Raising Cane's"":25}","{""Smart & Final"":37,""ARCO"":37,""Ross Stores"":24...","{""android"":4,""ios"":0}",1
34,206150887,sg:1e6733cd28294ea489920991b5d47a74,True Value Hardware,13881 Campo Rd Ste A 7,Jamul,CA,91935,US,SG_BRAND_0b1f746a0c413ffd,True Value Hardware,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730213033,"{""US"":15}",12277,11.0,"{""<5"":1,""5-20"":11,""21-60"":5,""61-240"":1,"">240"":0}","{""Albertsons"":33,""Boost Mobile"":25}","{""The Home Depot"":25,""ARCO"":22,""Jack in the Bo...","{""android"":8,""ios"":8}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,17082173,sg:227108952e484ede9593e484d5561359,Frontwave Credit Union,Marine Corps Recruit Depot Bldg 2,San Diego,CA,92140,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730063001,"{""US"":42}",796814,20.0,"{""<5"":1,""5-20"":23,""21-60"":15,""61-240"":8,"">240"":0}","{""Comfort Inn"":33,""F45 Training"":20,""GNC (Gene...","{""GNC (General Nutrition Centers)"":43,""In-N-Ou...","{""android"":28,""ios"":10}",1
1,46633079,sg:348426c5f17d4444b38c3d9254a19963,United States Postal Service (USPS),4300 Belleau Wood Ave Bldg 148,San Diego,CA,92140,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730063001,"{""US"":11}",17831,27.0,"{""<5"":0,""5-20"":17,""21-60"":11,""61-240"":8,"">240"":1}","{""GNC (General Nutrition Centers)"":20}","{""GNC (General Nutrition Centers)"":54,""Walmart...","{""android"":11,""ios"":4}",1
16,288452969,sg:e22f3a66ceeb4f69b1ef2e5f2a0b5851,NTC MCRD Energy Facility,End of Neville Road Bldg 566,San Diego,CA,92140,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0...",060730063001,{},0,10.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
15,246912870,sg:36d190835fd049dbaf25b4b8b5b4440e,Duncan Hall,Marine Corps Recruit Depot,San Diego,CA,92140,US,,,...,"[0,0,0,0,0,0,0,1,1,1,1,5,3,1,0,0,5,2,0,1,1,0,0...",060730063001,"{""US"":105}",53244,57.5,"{""<5"":4,""5-20"":67,""21-60"":68,""61-240"":58,"">240...","{""Chevron"":6}","{""GNC (General Nutrition Centers)"":15,""Chevron...","{""android"":67,""ios"":47}",1
14,240096949,sg:1cc3a18db00c4a9a8f5c703f893f2792,Marine Corps Recruit Depot Library,3800 Chosin Ave Bldg 7,San Diego,CA,92140,US,,,...,"[0,0,0,0,0,0,0,0,0,0,3,1,2,0,0,0,0,0,0,0,1,0,0...",060730063001,"{""US"":40}",11829,47.0,"{""<5"":0,""5-20"":13,""21-60"":30,""61-240"":33,"">240...","{""GNC (General Nutrition Centers)"":21,""Simon m...","{""GNC (General Nutrition Centers)"":13,""Simon m...","{""android"":25,""ios"":19}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,16944553,sg:4cc16306bf7542f3afb99a14292615e8,Starbucks,9500 Gilman Dr,La Jolla,CA,92093,US,SG_BRAND_f116acfe9147494063e58da666d1d57e,Starbucks,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730083051,"{""US"":4}",0,670.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":1,"">240"":3}",{},{},"{""android"":0,""ios"":0}",1
1,18896251,sg:fee052a7227a42a6941642fb9a5f395d,Allen Field,Torrey Pines Rd,La Jolla,CA,92093,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2,6,1,0,0,0,0,0...",060730083123,"{""US"":21}",6316,41.0,"{""<5"":0,""5-20"":7,""21-60"":11,""61-240"":10,"">240"":1}","{""Wetzel's Pretzels"":11,""Staples"":11,""Simon ma...","{""Starbucks"":30,""Westfield"":20,""Subway"":16,""7-...","{""android"":4,""ios"":17}",1
26,173078787,sg:f8b5b87e34994c13891ebbe72b5d175c,Shiley Eye Institute at UC San Diego Health,9415 Campus Point Dr,La Jolla,CA,92093,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",060730083052,"{""US"":4}",0,19.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":0,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
27,179822791,sg:2754eb76df7441e68a20effa4b899ebc,Digital Media Academy,Held At Uc San Diego 9500 Gilman Dr,La Jolla,CA,92093,US,,,...,"[0,0,0,0,0,0,0,1,0,2,0,0,1,0,0,0,2,0,1,0,1,0,0...",060730083051,"{""US"":101,""PH"":4}",2069,39.5,"{""<5"":4,""5-20"":61,""21-60"":29,""61-240"":46,"">240...","{""Handel's Home Made Ice Cream"":12,""The Old Sp...","{""Westfield"":15,""Vons"":11,""Starbucks"":10}","{""android"":50,""ios"":52}",1
28,193640586,sg:eebb32bc3d9440fb8b5e695ff26a657a,USE Credit Union,3100 Gilman Dr,La Jolla,CA,92093,US,,,...,"[1,1,0,1,0,0,0,0,0,0,0,1,1,2,4,2,12,3,4,5,8,6,...",060730083051,"{""US"":384}",1740,62.0,"{""<5"":5,""5-20"":142,""21-60"":308,""61-240"":323,"">...",{},"{""Westfield"":17,""Starbucks"":11,""Subway"":7}","{""android"":165,""ios"":224}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,20712919,sg:f8d65ddda4ba456690b1ea7b08a6798d,San Diego Aircraft Carrier Museum,937 N Harbor Dr,San Diego,CA,92132,US,,,...,"[0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0...",060730054002,"{""US"":79}",21038,139.0,"{""<5"":2,""5-20"":29,""21-60"":32,""61-240"":73,"">240...","{""Office Depot"":20,""Shell Oil"":19,""Starbucks"":...","{""Starbucks"":14,""Costco Wholesale Corp."":10,""W...","{""android"":54,""ios"":32}",1
1,86219349,sg:166ab9d65da540f3b6d649facc899585,Animae,969 Pacific Hwy,San Diego,CA,92132,US,,,...,"[1,0,0,0,0,0,3,1,0,1,0,2,0,0,0,0,3,0,1,1,0,0,0...",060730054002,"{""US"":72,""MX"":4}",19060,126.0,"{""<5"":2,""5-20"":22,""21-60"":20,""61-240"":50,"">240...","{""Office Depot"":36,""CVS"":9,""Curio Collection"":...","{""Starbucks"":33,""Westfield"":21,""Office Depot"":...","{""android"":34,""ios"":43}",1
2,106019430,sg:4912f5451b0044e3b00d97743f27ec3e,Nima Cafe,969 Pacific Hwy,San Diego,CA,92132,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730054002,"{""US"":8}",28922,37.0,"{""<5"":0,""5-20"":3,""21-60"":5,""61-240"":3,"">240"":2}",{},"{""Office Depot"":41,""Starbucks"":37,""Chevron"":23...","{""android"":4,""ios"":5}",1
3,136706166,sg:6aa3d90d321e4575905cf17dc07a4536,Quality Coast Gourmet Street Kitchen,910 N Harbor Dr,San Diego,CA,92132,US,,,...,"[0,0,0,0,1,0,0,2,1,1,4,1,4,5,1,4,2,0,0,0,0,0,0...",060730054001,"{""US"":137,""MX"":6,""BR"":4}",607577,18.0,"{""<5"":11,""5-20"":97,""21-60"":43,""61-240"":29,"">24...","{""Marriott Hotels"":12,""Starbucks"":10,""Chevron""...","{""Starbucks"":14,""Westfield"":10,""Costco Wholesa...","{""android"":95,""ios"":60}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,19866766,sg:35c5a77ad3354f0db6a6a8c4029e9a91,Warner Union School District Pre School,30951 Highway 79,Warner Springs,CA,92086,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209033,"{""US"":4}",13814,74.0,"{""<5"":1,""5-20"":2,""21-60"":1,""61-240"":3,"">240"":1}","{""New York & Company"":50,""Kohl's"":50}","{""New York & Company"":20,""Dickey's Barbecue Pi...","{""android"":4,""ios"":4}",1
1,22983967,sg:0c1f7dbd06864b83bc24e66ca1381306,San Jose Valley Continuation High,30951 Highway 79,Warner Springs,CA,92086,US,,,...,"[0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0...",060730209033,"{""US"":18}",44449,26.5,"{""<5"":2,""5-20"":14,""21-60"":5,""61-240"":5,"">240"":10}","{""True Value Hardware"":14,""Kohl's"":12}","{""Starbucks"":22,""ARCO"":22,""In-N-Out Burger"":13...","{""android"":14,""ios"":8}",1
2,68767719,sg:a515de7cf73148a18ae930293552a825,Warner Carrillo Ranch House Museum,29181 San Felipe Rd,Warner Springs,CA,92086,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209033,{},0,6.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
3,104322221,sg:68d52dc12f7645e49949226f23bac89f,Warner Springs Resort,31652 Ca 79,Warner Springs,CA,92086,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209033,"{""US"":4}",0,6.5,"{""<5"":1,""5-20"":5,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
4,104710043,sg:19aa74ae9c4947f3bc2a6355e7589f7e,Warner Springs Ranch Resort,31652 Highway 79,Warner Springs,CA,92086,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209031,"{""US"":9}",91954,20.5,"{""<5"":0,""5-20"":5,""21-60"":2,""61-240"":3,"">240"":0}","{""In-N-Out Burger"":50}","{""In-N-Out Burger"":25,""J.Jill"":12,""The Broken ...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,24156734,sg:9264ca9f728d4be0a14017b647a7cb4d,Surinder's Coffeeshack,Naval Base Coronado Guadalcanal Road,Coronado,CA,92155,US,,,...,"[0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,2...",060730216001,"{""US"":15}",2698,502.0,"{""<5"":0,""5-20"":11,""21-60"":0,""61-240"":0,"">240"":16}","{""Walmart"":8}","{""Navy Exchange"":44,""Subway"":30,""Vons"":11,""The...","{""android"":8,""ios"":7}",1
1,53964336,sg:a50074c78589427dbc25770838c532f0,Navy Gateway Inn & Suites,3628 Tulagi Rd Naval Amphibious Base,San Diego,CA,92155,US,,,...,"[0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,1,0,0,0,1...",060730216001,"{""US"":37}",18505,89.0,"{""<5"":1,""5-20"":16,""21-60"":28,""61-240"":26,"">240...","{""Circle K"":16,""Benihana"":12,""Panera Bread"":7,...","{""Navy Exchange"":33,""Subway"":30,""The Home Depo...","{""android"":19,""ios"":17}",1
2,78198934,sg:7b805de2f8bc43ddb627341b28872ff9,Subway,Naval Amphibious Base Bldg #33 Naval Amphibiou...,Coronado,CA,92155,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,2,0,0,1,1,0,0...",060730216001,"{""US"":61}",15366,32.0,"{""<5"":0,""5-20"":38,""21-60"":39,""61-240"":23,"">240...","{""Navy Exchange"":20,""Dunkin'"":5}","{""Navy Exchange"":34,""Jack in the Box"":7,""Shell...","{""android"":35,""ios"":28}",1
3,92965705,sg:6fe8d36cfaa24edb8ca7219b2386709d,Navy Exchange,3238 Guadacanal Road Building No. 18,Coronado,CA,92155,US,SG_BRAND_be82c0a3c3953343b719c69862917553,Navy Exchange,...,"[0,0,0,0,0,0,0,1,1,2,1,0,1,0,0,0,2,0,0,0,0,0,0...",060730216001,"{""US"":85}",13957,20.0,"{""<5"":6,""5-20"":69,""21-60"":33,""61-240"":16,"">240...","{""Subway"":29}","{""Subway"":26,""Costco Wholesale Corp."":7,""Shell...","{""android"":37,""ios"":48}",1
4,101980642,sg:878898ed001643098613f2426143a016,Naval Amphibious Base Coronado,3420 Guadalcanal Rd,San Diego,CA,92155,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0...",060730216001,"{""US"":32}",15662,19.0,"{""<5"":4,""5-20"":19,""21-60"":8,""61-240"":7,"">240"":7}","{""San Diego Style Sombrero Mexican Food"":17,""A...","{""Navy Exchange"":19,""Subway"":15,""Starbucks"":11...","{""android"":18,""ios"":19}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,25212478,sg:647b7fd65c3b4fbca6302a833f67b94d,Rancho Noel,25655 Potrero Park Dr,Potrero,CA,91963,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,{},0,4.0,"{""<5"":1,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
1,82241379,sg:3a638b1ee1234926ad505c2c98c60ceb,Potrero Elementary,24875 Potrero Valley Rd,Potrero,CA,91963,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,"{""US"":5,""MX"":4}",10531,169.0,"{""<5"":0,""5-20"":5,""21-60"":7,""61-240"":4,"">240"":12}","{""ARCO"":33,""Target"":32}","{""Walmart"":25,""In-N-Out Burger"":15,""ARCO"":15,""...","{""android"":11,""ios"":4}",1
2,137438684,sg:51825f0f36ca4eba8b588a0f2438986b,Cafe 94,25275 Potrero Valley Rd,Potrero,CA,91963,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,{},0,77.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
3,155464602,sg:8c790c1c7ecc499587a891decb19f257,Potrero Elementary State Preschool Center,24875 Potrero Valley Rd,Potrero,CA,91963,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,"{""US"":4,""MX"":4}",10531,19.0,"{""<5"":0,""5-20"":5,""21-60"":0,""61-240"":1,"">240"":3}",{},"{""BevMo"":14,""Souplantation"":14,""24 Hour Fitnes...","{""android"":7,""ios"":0}",1
4,261371844,sg:490ded0f2a2641759e3eca9a376f626b,San Diego Rural Fire Protection District Stati...,24550 State Highway 94,Potrero,CA,91963,US,,,...,"[1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211001,"{""US"":4}",0,12.0,"{""<5"":0,""5-20"":2,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,25727884,sg:aa3e161eb9f2454298e0438ad430a0cc,Firestone Complete Auto Care,Bldg 6214 Miramar Court,Miramar,CA,92145,US,SG_BRAND_c8cd3015bd66459919ee3d72cfb148f6,Firestone Complete Auto Care,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1...",060730094001,"{""US"":51}",21133,18.0,"{""<5"":2,""5-20"":28,""21-60"":17,""61-240"":7,"">240"":0}","{""Denny's"":50,""Chick-fil-A"":8,""Pressed Juicery...","{""Starbucks"":20,""McDonald's"":15,""Shell Oil"":14...","{""android"":30,""ios"":24}",1
14,185695147,sg:20d3f05ea35946f48147571e9c2ed55b,A 1 Soils Hanson Aggregates,9229 Harris Plant Rd,San Diego,CA,92145,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730094001,"{""US"":8}",32568,15.0,"{""<5"":1,""5-20"":6,""21-60"":2,""61-240"":1,"">240"":0}","{""ampm"":100,""ARCO"":100,""Target"":99}","{""Kaiser Permanente"":43,""ARCO"":42,""The Home De...","{""android"":4,""ios"":4}",1
25,290219067,sg:47e034f46de744479620e0fa7f4a261e,Jamba,2761 Gonsalves Avenue,San Diego,CA,92145,US,SG_BRAND_d3a2bc5695cfc85f68248eb8399304a4,Jamba,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730094001,"{""US"":9}",22042,20.0,"{""<5"":0,""5-20"":6,""21-60"":4,""61-240"":1,"">240"":0}","{""McDonald's"":97}","{""Starbucks"":40,""Westfield"":22,""Costco Wholesa...","{""android"":4,""ios"":5}",1
24,290486648,sg:75e69452d14c4b94a2cb720538e722e4,Dunkin',8635 Obregon Avebuilding 8675,San Diego,CA,92145,US,SG_BRAND_9b4045db0fbb461cf9ed78916d9b16b4,Dunkin',...,"[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730094001,"{""US"":103}",14676,10.0,"{""<5"":11,""5-20"":104,""21-60"":20,""61-240"":13,"">2...","{""Domino's Pizza"":16,""Chick-fil-A"":6}","{""Starbucks"":22,""Denny's"":16,""McDonald's"":13,""...","{""android"":62,""ios"":41}",1
23,278972619,sg:0130c28c5d64493b889d8aca92313872,MCAS Miramar Memorial Golf Course,3750 Anderson Ave,San Diego,CA,92145,US,,,...,"[0,0,0,0,0,0,2,1,3,1,5,5,2,1,1,2,5,2,0,0,0,0,1...",060730094001,"{""US"":133}",9899,36.0,"{""<5"":13,""5-20"":89,""21-60"":88,""61-240"":72,"">24...","{""Denny's"":65,""Domino's Pizza"":10,""Ashley Furn...","{""Denny's"":61,""Dunkin'"":13,""Navy Exchange"":10,...","{""android"":78,""ios"":60}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,26847448,sg:362f6d3436874ab2ad842c23b668aac1,Foodworx,9450 Gilman Dr Matthews & 6th College Apts Com...,La Jolla,CA,92092,US,,,...,"[1,0,1,1,0,0,0,0,1,1,1,1,1,2,2,1,12,1,5,3,6,1,...",060730083051,"{""US"":71}",1311,165.0,"{""<5"":0,""5-20"":47,""21-60"":46,""61-240"":112,"">24...",{},"{""Westfield"":17,""Starbucks"":10,""In-N-Out Burge...","{""android"":27,""ios"":46}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,31848260,sg:b2bfc86bbb574ff3afde1fbb1e2c5fc2,Vincennes University Nab,34800 Bob Wilson Dr,San Diego,CA,92134,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730055001,{},0,14.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
1,182297730,sg:1a7f95ff789b439dafa49ef7fd0b9441,Navy Exchange,34800 Bob Wilson Dr Bldg NO1,San Diego,CA,92134,US,SG_BRAND_be82c0a3c3953343b719c69862917553,Navy Exchange,...,"[0,1,2,1,0,3,2,0,1,5,1,1,2,3,0,1,3,2,1,0,2,1,0...",060730055001,"{""US"":223}",17660,53.5,"{""<5"":11,""5-20"":136,""21-60"":119,""61-240"":137,""...","{""Buffalo Wild Wings"":6,""The Home Depot"":6}","{""Starbucks"":10,""ARCO"":10,""Subway"":9,""Westfiel...","{""android"":135,""ios"":103}",1
2,204586092,sg:495457ecfbb64d80a6ca6dcd48da3203,San Diego Lawn Bowling Club,2125 Park Blvd Balboa Park,San Diego,CA,92134,US,,,...,"[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730055001,"{""US"":6}",19604,61.5,"{""<5"":0,""5-20"":4,""21-60"":6,""61-240"":6,"">240"":4}","{""Panda Express"":33,""Valero Energy"":33}","{""Costco Wholesale Corp."":27,""McDonald's"":21,""...","{""android"":6,""ios"":0}",1
3,228084716,sg:069e33bdd544435aa45ba130e2d1efe4,Saint Tropez Bistro,34800 Bob Wilson Dr Bldg 26,San Diego,CA,92134,US,,,...,"[0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,2,0,0,0,0,0,0,0...",060730055001,"{""US"":151}",16906,20.0,"{""<5"":7,""5-20"":103,""21-60"":45,""61-240"":38,"">24...","{""Vons"":50,""Navy Exchange"":25,""Denny's"":25}","{""Navy Exchange"":34,""Starbucks"":14,""Subway"":12...","{""android"":81,""ios"":75}",1
4,239403373,sg:127a64985c364fdca7e12fbada086fbb,NMC San Diego,34800 Bob Wilson Dr,San Diego,CA,92134,US,,,...,"[0,0,0,0,0,1,1,0,0,0,0,2,0,0,1,2,0,0,0,0,0,1,0...",060730055001,"{""US"":194}",17344,15.0,"{""<5"":14,""5-20"":158,""21-60"":59,""61-240"":46,"">2...","{""Vons"":50,""Subway"":24,""Navy Exchange"":20,""Den...","{""Navy Exchange"":35,""Subway"":30,""Starbucks"":15...","{""android"":108,""ios"":87}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,34050362,sg:448d5a9ceed44c6eb6d6ecba5e369208,Grossmont High,1100 Murray Dr.,La Mesa,CA,91944,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730160002,"{""US"":70}",5201,99.0,"{""<5"":1,""5-20"":3,""21-60"":47,""61-240"":68,"">240""...","{""Kahoots Pet Products"":50,""Wendy's"":9}","{""Starbucks"":20,""7-Eleven"":15,""Jack in the Box...","{""android"":35,""ios"":39}",1
1,180368891,sg:0214321708a340958f4ac2a10ca15a6d,Grossmont Union High Special Education Program,1100 Murray Dr.,La Mesa,CA,91944,US,,,...,"[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730160002,"{""US"":130}",4120,44.0,"{""<5"":1,""5-20"":59,""21-60"":118,""61-240"":81,"">24...","{""Kahoots Pet Products"":25,""California Pizza K...","{""Jack in the Box"":13,""Shell Oil"":11,""Starbuck...","{""android"":51,""ios"":82}",1
2,192963873,sg:bdfd5e11b20941ab8e7324789a134ead,Express Gasoline,8602 Lake Murray Blvd,La Mesa,CA,91944,US,,,...,"[0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0...",060730098025,"{""US"":23}",1495,9.0,"{""<5"":2,""5-20"":17,""21-60"":3,""61-240"":4,"">240"":2}","{""Chipotle Mexican Grill"":40,""Albertsons"":25,""...","{""7-Eleven"":33,""Costco Wholesale Corp."":15,""Mc...","{""android"":10,""ios"":12}",1
3,259689268,sg:d1432d482698418ebd2a59e5ac356174,Skatedogz,6788 University Ave,La Mesa,CA,91944,US,,,...,"[0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0...",060730029021,"{""US"":22}",5195,17.0,"{""<5"":0,""5-20"":13,""21-60"":6,""61-240"":6,"">240"":0}","{""Chrysler"":14}","{""The Salvation Army"":23,""Food 4 Less"":18,""Wes...","{""android"":15,""ios"":9}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,36676129,sg:ee7639b08400497a82663f9d91ea36f9,Bias Handyman Services,11251 Rancho Carmel Dr Unit 501496,San Diego,CA,92150,US,,,...,"[0,0,1,0,0,0,2,0,0,1,0,1,5,4,6,1,13,0,0,0,5,0,...",060730170561,"{""US"":187}",11257,50.5,"{""<5"":18,""5-20"":155,""21-60"":73,""61-240"":153,"">...","{""Discount Tire"":6,""Kaiser Permanente"":6}","{""Costco Wholesale Corp."":24,""United States Po...","{""android"":119,""ios"":72}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,44814843,sg:3f8aae7b64c947f0aefd0916f2547cc8,San Diego Seaplanes,1140 Wall St Unit 125,La Jolla,CA,92038,US,,,...,"[0,0,0,0,0,0,0,0,1,3,1,0,3,3,0,6,4,0,0,0,0,0,0...",060730082003,"{""US"":74}",16703,41.0,"{""<5"":6,""5-20"":32,""21-60"":33,""61-240"":36,"">240...","{""Vons"":20,""Subway"":14,""Westfield"":10,""Carl's ...","{""Starbucks"":24,""Westfield"":18,""Costco Wholesa...","{""android"":29,""ios"":46}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,51479486,sg:92a730981f32445bb7c8f2558343dd63,Active Shooter Defense School,1020 Marron Valley Rd,Dulzura,CA,91917,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730213021,"{""US"":4}",0,197.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":3,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
1,74839057,sg:d2779a42b7f740cf977842cbb5247166,Barrett Junction Cafe & Mercantile,1020 Barrett Lake Rd,Dulzura,CA,91917,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0...",060730213021,"{""US"":14}",36424,48.0,"{""<5"":0,""5-20"":5,""21-60"":4,""61-240"":7,"">240"":1}","{""76"":50,""Walmart"":44,""Chevron"":24,""Target"":24}","{""76"":18,""ARCO"":18,""Walmart"":18,""McDonald's"":1...","{""android"":11,""ios"":0}",1
2,124132625,sg:d0c1b4f4591e44d7968f54ad69c3f2c0,San Diego Rural Fire Protection District Stati...,1135 Community Building Rd,Dulzura,CA,91917,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730213021,{},0,92.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":0,""ios"":0}",1
3,155331266,sg:cf978542e4ae48fdb33d1c5dc27d6cac,911academy,1020 Marron Valley Rd,Dulzura,CA,91917,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730213021,"{""US"":10}",36650,144.0,"{""<5"":0,""5-20"":1,""21-60"":3,""61-240"":4,"">240"":5}","{""Jersey Mike's"":33}","{""McDonald's"":22,""Navy Exchange"":20,""Vons"":20,...","{""android"":5,""ios"":6}",1
4,175326011,sg:a4f544fa939d4ed5b0e92ff126e31dd6,Dulzura California,17023 Highway 94,Dulzura,CA,91917,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730213021,"{""US"":7,""MX"":4}",23519,14.0,"{""<5"":0,""5-20"":3,""21-60"":2,""61-240"":0,"">240"":0}","{""Walmart"":94}","{""Walmart"":47,""AutoZone"":39,""Subway"":36,""UNFI ...","{""android"":7,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,55635933,sg:b4757b003f5549be83559defe927dd60,DaVita,480 Alta Rd,San Diego,CA,92179,US,SG_BRAND_b92d75d5850ea7f89a9d03198bfeb0a3,DaVita,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730100141,"{""US"":7}",13191,77.5,"{""<5"":1,""5-20"":3,""21-60"":0,""61-240"":7,"">240"":1}","{""Pilot Flying J"":50}","{""Costco Wholesale Corp."":35,""Claim Jumper Res...","{""android"":4,""ios"":4}",1
1,151396000,sg:1bc6bf1ddd44448d938a023fc607af90,Richard J Donovan Correctional Facility,480 Alta Rd,San Diego,CA,92179,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730100141,{},0,12.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
2,259736933,sg:85fd50245096454fb35b6cd76265c400,R J Donovan Correctional Facility Rjd,480 Alta Rd,San Diego,CA,92179,US,,,...,"[2,0,0,0,0,4,6,1,2,1,0,1,0,6,1,2,8,1,1,1,2,0,2...",060730100141,"{""US"":116,""MX"":4}",11963,272.5,"{""<5"":3,""5-20"":65,""21-60"":29,""61-240"":91,"">240...","{""Jack in the Box"":7}","{""Costco Wholesale Corp."":8,""7-Eleven"":8,""Star...","{""android"":90,""ios"":42}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,56169401,sg:f110039e300449e38b186fcbe384d01b,Montezuma Valley Market,37552 Montezuma Valley Rd,Ranchita,CA,92066,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209033,"{""US"":4}",0,24.0,"{""<5"":0,""5-20"":4,""21-60"":1,""61-240"":2,"">240"":2}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,57449569,sg:1522bfc3e94b43e78af6f14bc0ebdcfc,Aliso Creek Rest Area,Interstate 5 5.8 Miles North of Oceanside,Oceanside,CA,92049,US,,,...,"[1,1,1,0,0,0,1,7,2,7,9,5,7,3,2,2,2,2,1,4,3,1,0...",060730187001,"{""US"":361,""MX"":20,""CA"":4}",104455,10.0,"{""<5"":29,""5-20"":288,""21-60"":55,""61-240"":29,"">2...","{""Carl's Jr."":5,""Pilot Flying J"":5}","{""ARCO"":18,""Chevron"":17,""Shell Oil"":12,""76"":11...","{""android"":277,""ios"":123}",1
1,126657931,sg:371422fbce5f4d66b3532ec5d025c157,Sunset Market,Tremont St & Pier View Way,Oceanside,CA,92049,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,3,1,1,1,0,1,0,0,0,0,0...",060730184002,"{""US"":63}",13625,29.0,"{""<5"":2,""5-20"":19,""21-60"":27,""61-240"":14,"">240...","{""GameStop"":12,""Walmart"":6}","{""In-N-Out Burger"":8,""Denny's"":8,""Domino's Piz...","{""android"":37,""ios"":25}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,60142635,sg:cf57f0941bd54377b92d4100cd711685,Shell Oil,1494 Carrizo Gorge Rd,Jacumba,CA,91934,US,SG_BRAND_2591c98b70119fe624898b1e424b5e91,Shell Oil,...,"[0,0,0,0,0,0,1,0,0,1,2,0,2,1,4,0,1,1,1,1,0,0,0...",060730211004,"{""US"":65,""MX"":4}",132880,10.0,"{""<5"":3,""5-20"":57,""21-60"":10,""61-240"":1,"">240"":4}","{""99 Cents Only Stores"":17,""Burger King"":13,""S...","{""Chevron"":24,""Starbucks"":17,""McDonald's"":15,""...","{""android"":42,""ios"":28}",1
1,72745644,sg:eac8670cd33c491dbca77dfc51f49524,Wright Fuel Stop Jacumba,Carrizo Gorge Rd & I,Jacumba,CA,91934,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211004,"{""US"":6,""MX"":4}",82895,41.5,"{""<5"":0,""5-20"":2,""21-60"":5,""61-240"":3,"">240"":2}","{""Chevron"":99,""ARCO"":25}","{""Chevron"":98,""TravelCenters of America"":43,""T...","{""android"":7,""ios"":0}",1
2,83360317,sg:5553a567c6404800a846bc52f114ad7c,San Diego Rural Fire Protection District Stati...,1255 Jacumba St,Jacumba,CA,91934,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0...",060730211004,"{""US"":4}",0,27.5,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":0,"">240"":1}",{},{},"{""android"":0,""ios"":0}",1
3,85268370,sg:56749b02cb404ca9b7693c9ab0a00d47,Desert View Tower,Old Hig 80 In Ko Pah Park Rd,Jacumba,CA,91934,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,1,0,0,0,0,0,0,0...",060250123011,"{""US"":14}",86405,34.0,"{""<5"":1,""5-20"":3,""21-60"":7,""61-240"":5,"">240"":0}","{""Jack in the Box"":33}","{""Jack in the Box"":37,""Chevron"":30,""Starbucks""...","{""android"":7,""ios"":6}",1
4,101572551,sg:07dbaa77c7c14ff4a06f6f52b0caa0db,Jacumba Library,44605 Old Highway 80,Jacumba,CA,91934,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730211004,{},0,108.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,61530344,sg:968b1c1fb78143cbbe316cbb334f3aba,Crash's Cafe,333 S Twin Oaks Valley Rd,San Marcos,CA,92096,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203061,"{""US"":4}",0,6.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":4,""ios"":0}",1
1,140940982,sg:749330c72aff4f52b83f23eec48f521f,Panda Express,333 South Twin Oaks Valley Road,San Marcos,CA,92096,US,SG_BRAND_4a453a402f10c481d2fe4cefaa1d2b09,Panda Express,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203061,"{""US"":70}",25134,19.0,"{""<5"":0,""5-20"":52,""21-60"":16,""61-240"":9,"">240"":0}","{""Jamba"":23,""In-N-Out Burger"":20,""McDonald's"":...","{""Jamba"":65,""Starbucks"":55,""Target"":14,""In-N-O...","{""android"":30,""ios"":38}",1
2,197190110,sg:d5c2d9c64f294e73a3a0ac21f446ce41,Annual San Marcos Fitness Roundup,333 S Twin Oaks Valley Rd,San Marcos,CA,92096,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203061,"{""US"":248,""AR"":4}",22140,54.5,"{""<5"":2,""5-20"":64,""21-60"":171,""61-240"":177,"">2...","{""Crunch"":33,""In-N-Out Burger"":33,""Jamba"":20,""...","{""Starbucks"":63,""Jamba"":52,""Target"":13,""In-N-O...","{""android"":76,""ios"":180}",1
3,200067581,sg:e6e891e750504be596b9b566d2a4361a,Jamba,333 S Twin Oaks Valley Rd,San Marcos,CA,92096,US,SG_BRAND_d3a2bc5695cfc85f68248eb8399304a4,Jamba,...,"[0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0...",060730203061,"{""US"":374}",23752,49.0,"{""<5"":10,""5-20"":141,""21-60"":238,""61-240"":261,""...",{},"{""Starbucks"":59,""In-N-Out Burger"":15,""Target"":...","{""android"":103,""ios"":271}",1
4,212743555,sg:4c2b8fd70b054defa8763f4c10829798,Campus Coffee Cart,333 S Twin Oaks Valley Rd,San Marcos,CA,92096,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203061,{},0,439.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,71476550,sg:b37d98bed5cc47eda02ae5c55f077e87,Sharp Perfection,650 Dennery Rd,San Diego,CA,92153,US,,,...,"[0,0,0,0,0,0,1,0,1,1,0,1,3,2,2,1,2,1,3,2,1,0,0...",060730100142,"{""US"":119,""MX"":25}",2920,12.0,"{""<5"":8,""5-20"":117,""21-60"":31,""61-240"":7,"">240...","{""Walmart"":19,""Starbucks"":13,""McDonald's"":6}","{""Walmart"":24,""Starbucks"":21,""Chevron"":19,""McD...","{""android"":98,""ios"":49}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,76190501,sg:b9c7620bfd7044d8ad45ef3ceff254a3,Stylehawk Event Services,1150 Garden View Rd Unit 231822,Encinitas,CA,92023,US,,,...,"[0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,1,1,0,0,0,0,0,0...",060730176042,"{""US"":61}",4599,13.0,"{""<5"":8,""5-20"":63,""21-60"":10,""61-240"":27,"">240...","{""Best Buy"":20,""Starbucks"":18,""CVS"":14,""O'Reil...","{""Vons"":24,""Starbucks"":22,""Chevron"":13,""Trader...","{""android"":35,""ios"":29}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,78928651,sg:99d9f93c899643a3b737f0676d61ea79,San Diego Rural Fire Protection District Stati...,446 Alta Rd,San Diego,CA,92158,US,,,...,"[0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1...",060730213021,"{""US"":4}",10437,193.0,"{""<5"":0,""5-20"":2,""21-60"":3,""61-240"":6,"">240"":8}",{},"{""Walmart"":27,""The Kebab Shop"":20,""WestCoast H...","{""android"":4,""ios"":4}",1
1,78835999,sg:84ef002a7a594c9aaf99f30d53b8116f,George F Bailey Detention Facility,446 Alta Rd Ste 5300,San Diego,CA,92158,US,,,...,"[0,0,0,0,0,0,2,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0...",060730213021,"{""US"":13}",15928,100.0,"{""<5"":0,""5-20"":9,""21-60"":5,""61-240"":10,"">240"":13}","{""LA Fitness"":25,""ARCO"":25,""Shell Oil"":24}","{""Shell Oil"":20,""Westfield"":15,""Kaiser Permane...","{""android"":7,""ios"":6}",1
2,179382708,sg:f2e08bfd098e42b5b4fecdc9eb012054,East Mesa Juvenile Detention Facility,446 Alta Rd Ste 6100,San Diego,CA,92158,US,,,...,"[0,0,0,0,0,0,2,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1...",060730213021,"{""US"":13}",18968,110.5,"{""<5"":0,""5-20"":4,""21-60"":5,""61-240"":20,"">240"":11}","{""Boys & Girls Clubs of America"":14,""Costco Wh...","{""Costco Wholesale Corp."":17,""Subway"":15,""Star...","{""android"":11,""ios"":6}",1
3,241184363,sg:9a9edd46e8bc47e792aba310157e7491,Facility 8 Detention Facility,446 Alta Rd Ste 5300,San Diego,CA,92158,US,,,...,"[0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0...",060730213021,"{""US"":5}",0,484.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":0,"">240"":5}",{},{},"{""android"":4,""ios"":5}",1
4,250211114,sg:9531f7c8819a4d81b88d2c0a982d6170,East Mesa Reentry Facility,446 Alta Rd Ste 5200,San Diego,CA,92158,US,,,...,"[0,0,0,0,0,3,6,3,1,1,0,1,2,2,0,0,3,5,0,0,0,0,0...",060730213021,"{""US"":61}",16102,120.0,"{""<5"":0,""5-20"":35,""21-60"":28,""61-240"":57,"">240...","{""Rubio's Restaurants"":11,""LA Fitness"":8,""Denn...","{""Costco Wholesale Corp."":15,""Chevron"":11,""Sta...","{""android"":42,""ios"":23}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,78928744,sg:9e170bbed77d4de981e34bfc39067793,Greasy Spoon Mls Cafeteria,11251 Rancho Carmel Dr,San Diego,CA,92199,US,,,...,"[1,1,0,0,2,1,0,1,3,0,0,3,0,0,0,0,0,0,0,1,2,3,2...",060730170561,"{""US"":111}",17934,105.0,"{""<5"":7,""5-20"":44,""21-60"":39,""61-240"":100,"">24...","{""Best Buy"":11,""United States Postal Service (...","{""Costco Wholesale Corp."":20,""United States Po...","{""android"":68,""ios"":47}",1
1,122291496,sg:e59f57e832c445be9afd2c5919137223,United States Postal Service (USPS),11251 Rancho Carmel Dr,San Diego,CA,92199,US,SG_BRAND_27ee73cd1fb6f5e432852fea401eacce,United States Postal Service (USPS),...,"[1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1...",060730170561,"{""US"":10}",26351,18.0,"{""<5"":0,""5-20"":9,""21-60"":3,""61-240"":4,"">240"":1}",{},"{""The Bar Method"":15,""Costco Wholesale Corp."":...","{""android"":9,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,87924282,sg:bb5380b012ed4c02a6c0e4ceeeec0870,Montiel Park Disc Golf Course,Montiel Park Nordahl Rd And St Paul Dr,San Marcos,CA,92079,US,,,...,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,0,0...",060730203091,"{""US"":32}",2911,30.0,"{""<5"":0,""5-20"":14,""21-60"":16,""61-240"":7,"">240"":3}","{""McDonald's"":30,""The Habit Burger Grill"":25,""...","{""7-Eleven"":14,""Yum Yum Donuts"":12,""Jack in th...","{""android"":18,""ios"":15}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,91178882,sg:dc83a86965b043f1a411d378108f4088,Excellence General Construction,5505 Stevens Way Unit 742322,San Diego,CA,92174,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1...",060730031111,{},0,344.0,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,90882803,sg:7abf704ab501492588540a45e0b44a0a,Guatay Mountain Nursery,27423 Old Highway 80,Guatay,CA,91931,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0...",060730212022,"{""US"":4}",0,135.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":1}",{},{},"{""android"":4,""ios"":0}",1
1,113205736,sg:939b43e085ed4930907110f259b5f76b,Guatay Country Store,27560 Old Highway 80,Guatay,CA,91931,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730209021,"{""US"":4}",0,8.0,"{""<5"":0,""5-20"":3,""21-60"":0,""61-240"":1,"">240"":0}",{},{},"{""android"":7,""ios"":0}",1
2,121146146,sg:fcdac809d46b4653b368609d87b89b11,Guatay Christian Fellowship,27521 Old Highway 80,Guatay,CA,91931,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730212022,{},0,186.5,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":3,"">240"":2}",{},{},"{""android"":4,""ios"":0}",1
3,263338745,sg:3a7308f709fe4e31bd4226653729f6e3,Tryyn Wooden Spoon Gallery,27538 Old Highway 80,Guatay,CA,91931,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209021,"{""US"":4}",37123,129.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":3,"">240"":4}","{""ARCO"":100,""Chick-fil-A"":98,""Chevron"":49}","{""Walmart"":37,""Big 5 Sporting Goods"":25,""Baski...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,99257109,sg:2b0e80a06db3492d86ecdfa59d7dccf1,SDR Contracting,401 W Lexington Ave,El Cajon,CA,92022,US,,,...,"[9,7,0,1,6,16,13,15,56,37,37,27,0,1,3,1,3,11,3...",060730159011,"{""US"":713}",5131,30.0,"{""<5"":23,""5-20"":652,""21-60"":782,""61-240"":441,""...","{""United States Postal Service (USPS)"":15,""Gro...","{""United States Postal Service (USPS)"":24}","{""android"":207,""ios"":1389}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,98908321,sg:5bb7937d89234f55a36d59cbfacab8f7,Subway,Naval Exchange Bldg 2017 North Island Nas,Coronado,CA,92152,US,SG_BRAND_de80593878cb1673c62a7f338dc7e4e1,Subway,...,"[0,0,0,0,0,2,0,0,1,1,1,2,0,0,0,0,0,0,1,0,0,0,0...",060730113001,"{""US"":33}",14531,42.0,"{""<5"":1,""5-20"":17,""21-60"":21,""61-240"":18,"">240...","{""Walmart"":16,""KFC"":14,""Costco Wholesale Corp....","{""Navy Exchange"":24,""Dunkin'"":16,""Costco Whole...","{""android"":23,""ios"":11}",1
1,199584503,sg:54872e770d234628b01bfb214ea267f6,SPAWAR Systems Center Pacific Cafeteria,53560 Hull St,San Diego,CA,92152,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730071002,"{""US"":98}",25430,154.0,"{""<5"":1,""5-20"":40,""21-60"":51,""61-240"":94,"">240...",{},"{""Costco Wholesale Corp."":14,""The Home Depot"":...","{""android"":69,""ios"":32}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,118320245,sg:1ba96059a81e484aa89f9496ddba73f0,Taylor Made Fitness,4640 Cass St,San Diego,CA,92169,US,,,...,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0...",060730079052,"{""US"":33}",5133,22.0,"{""<5"":0,""5-20"":22,""21-60"":13,""61-240"":10,"">240...","{""The Habit Burger Grill"":20,""Saks Off Fifth"":...","{""Vons"":15,""Westfield"":15,""Five Guys"":15,""7-El...","{""android"":10,""ios"":23}",1
1,233661743,sg:c58f22ea3bf14fd4887ce289db3ee80e,RJ Landscape Construction,1234 Nordhal Rd,San Diego,CA,92169,US,,,...,"[0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1...",060730203091,"{""US"":8}",243,13.5,"{""<5"":0,""5-20"":8,""21-60"":2,""61-240"":2,"">240"":2}","{""Carl's Jr."":33,""Party City"":33,""Starbucks"":31}","{""Starbucks"":28,""The Cheesecake Factory"":22,""T...","{""android"":0,""ios"":9}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,133201516,sg:4d75be40de5e4f47a760f058edadef00,Navy Base Point Loma Gym,2482 2498 Mc Donough Rd,San Diego,CA,92147,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,3,1...",060730214001,"{""US"":35}",15015,169.0,"{""<5"":0,""5-20"":19,""21-60"":17,""61-240"":30,"">240...","{""Wingstop"":28,""Navy Exchange"":14,""T.J. Maxx"":...","{""Navy Exchange"":27,""Starbucks"":14,""Vons"":11,""...","{""android"":21,""ios"":14}",1
1,212723735,sg:b0fbec53b6a645ccb6b687110c393716,NMAWC Fitness Center,32444 Echo Ln Bldg 57 Nmawc Complex,San Diego,CA,92147,US,,,...,"[0,0,0,0,0,0,1,0,1,0,1,1,2,1,1,0,2,0,0,0,0,0,0...",060730214001,"{""US"":75,""MX"":4}",23158,101.0,"{""<5"":1,""5-20"":30,""21-60"":51,""61-240"":83,"">240...","{""Sarku Japan"":12,""The Art of Shaving"":11,""Sim...","{""Navy Exchange"":17,""Costco Wholesale Corp."":1...","{""android"":44,""ios"":40}",1
2,257389594,sg:d0d825462d854416893d4470feb0f4e3,Admiral Kidd Catering & Conference Center,33050 Acoustic Ave,San Diego,CA,92147,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,0,0...",060730214001,"{""US"":44}",21368,31.0,"{""<5"":1,""5-20"":32,""21-60"":21,""61-240"":27,"">240...","{""Westfield"":12,""Burlington"":9}","{""Starbucks"":12,""Costco Wholesale Corp."":11,""N...","{""android"":20,""ios"":25}",1
3,268466588,sg:4352e78caebc480caf8b80423251a92e,US Navy Recruiting Office,33055 Nixie Way,San Diego,CA,92147,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0...",060730214001,"{""US"":34}",18140,116.0,"{""<5"":0,""5-20"":21,""21-60"":26,""61-240"":32,"">240...","{""Sarku Japan"":11,""Sheraton Hotels & Resorts"":...","{""Navy Exchange"":15,""Costco Wholesale Corp."":1...","{""android"":30,""ios"":10}",1
4,282565911,sg:64aa65b730b741db89985ed9cbd08dea,Naval Base Point Loma,32444 Echo Ln,San Diego,CA,92147,US,,,...,"[0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,3,3,0,0,0,0,0,0...",060730214001,"{""US"":21}",12607,32.0,"{""<5"":0,""5-20"":21,""21-60"":11,""61-240"":5,"">240""...","{""Burger King"":14,""Applebee's"":12,""Phil's BBQ"":9}","{""Navy Exchange"":39,""Starbucks"":24,""Jack in th...","{""android"":15,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,150939494,sg:ef664cdeaa574eb78d74c60a1003a1e0,International Center Resale Shop,Ucsd,La Jolla,CA,92039,US,,,...,"[0,0,1,1,0,0,1,0,0,0,0,4,2,2,4,1,5,4,3,1,2,2,0...",060730083051,"{""US"":272}",2656,56.5,"{""<5"":9,""5-20"":99,""21-60"":182,""61-240"":164,"">2...",{},"{""Westfield"":15,""Starbucks"":12,""Costco Wholesa...","{""android"":104,""ios"":175}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,161209445,sg:6d2fe1821344467b9f63c5428a002b9a,City Heights Farmers' Market,4325 Wightman St,San Diego,CA,92125,US,,,...,"[0,0,3,0,0,1,2,0,0,1,1,0,1,1,0,0,0,0,1,0,3,0,0...",060730024021,"{""US"":46}",10012,69.0,"{""<5"":2,""5-20"":20,""21-60"":37,""61-240"":70,"">240...","{""Starbucks"":23,""99 Cents Only Stores"":17,""Jac...","{""Jack in the Box"":16,""7-Eleven"":14,""Costco Wh...","{""android"":26,""ios"":19}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,163062207,sg:e0f556bd157b48ce8403bccf64cf803c,Lawn,747 S Mission Rd Unit 2923,Fallbrook,CA,92088,US,,,...,"[0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0...",060730189051,"{""US"":40}",4967,11.0,"{""<5"":2,""5-20"":36,""21-60"":8,""61-240"":12,"">240"":1}","{""Sherwin-Williams"":14,""Subway"":13,""AutoZone"":...","{""Costco Wholesale Corp."":19,""AutoZone"":15,""Ka...","{""android"":26,""ios"":20}",1
1,198566495,sg:3d99400ab83e436a98acc93fe08df897,I Metro,747 S Mission Rd Unit 2923,Fallbrook,CA,92088,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730189051,{},0,1280.0,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":0,""ios"":0}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,167874627,sg:f39bc2f73c8d445dbd528b838a8cd187,Glorietta Bay Park,2201 Rendova Rd,Coronado,CA,92178,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0...",060730216001,"{""US"":24}",14883,68.0,"{""<5"":2,""5-20"":7,""21-60"":20,""61-240"":34,"">240"":6}","{""Residence Inn by Marriott"":33,""Subway"":32,""D...","{""Navy Exchange"":46,""Subway"":32,""Grand Hyatt"":...","{""android"":16,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,187651921,sg:74d46b33662549cbb63caaad982c263a,JJ Septic & Drain Service,2726 S Santa Fe Ave,Vista,CA,92085,US,,,...,"[0,0,0,0,0,1,1,3,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0...",060730200181,"{""US"":10}",13525,50.5,"{""<5"":0,""5-20"":4,""21-60"":13,""61-240"":9,"">240"":2}","{""Planet Fitness"":16}","{""7-Eleven"":35,""Costco Wholesale Corp."":34,""Mc...","{""android"":8,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,196993833,sg:74fba6146d0f453a8f432fb84f3ea8e2,Guanni Chocolate,Various Locations,Escondido,CA,92033,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730203072,"{""US"":5}",61364,15.0,"{""<5"":1,""5-20"":5,""21-60"":2,""61-240"":1,"">240"":0}","{""Mazda"":100,""BMW"":50,""Honda"":50,""Dodge"":50,""V...","{""Mazda"":57,""MINI"":43,""BMW"":43,""ampm"":43,""Kia ...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,243595266,sg:ffdff2a68a844a298e67cbbeee4491ff,Mount Laguna Campground,10678 Sunrise Hwy,Mount Laguna,CA,91948,US,,,...,"[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",060730209021,"{""US"":8}",69501,30.0,"{""<5"":0,""5-20"":5,""21-60"":1,""61-240"":2,"">240"":2}",{},"{""Sprouts Farmers Market"":25,""ARCO"":25,""Shell ...","{""android"":5,""ios"":4}",1
1,265488384,sg:5e2483d109cd48b18a7d7bc82ce2fea9,Tiny House Block,9849 Sunrise Hwy,Mount Laguna,CA,91948,US,,,...,"[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0...",060730209021,"{""US"":9}",61671,42.0,"{""<5"":1,""5-20"":2,""21-60"":3,""61-240"":2,"">240"":1}","{""Vons"":20,""Chevron"":19,""McDonald's"":17}","{""Chick-fil-A"":30,""Starbucks"":28,""Subway"":19,""...","{""android"":4,""ios"":4}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,247325719,sg:b5ae7c06c7a546c5bba931873202fb06,Drama Kids,2701 Midway Dr Unit 80957,San Diego,CA,92138,US,,,...,"[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,0,0...",060730066001,"{""US"":13}",13449,61.0,"{""<5"":1,""5-20"":8,""21-60"":5,""61-240"":14,"">240"":1}","{""Saks Off Fifth"":25,""Grocery Outlet"":25,""Doll...","{""United States Postal Service (USPS)"":30,""Sta...","{""android"":5,""ios"":8}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,260093074,sg:8cd95bdcedd44907989687644d5aa004,Remotely Virtual Services,815 E St Unit 120375,San Diego,CA,92112,US,,,...,"[0,0,0,0,1,0,0,0,1,0,1,0,2,1,0,1,1,0,0,0,0,0,0...",060730053002,"{""US"":31}",15528,19.0,"{""<5"":3,""5-20"":24,""21-60"":12,""61-240"":8,"">240"":6}","{""AutoZone"":25,""Pendry"":20,""76"":12,""Domino's P...","{""Westfield"":22,""The Salvation Army"":19,""McDon...","{""android"":24,""ios"":11}",1

,id_x,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,visits_by_each_hour,poi_cbg,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,id_y
0,291851686,sg:4f273d4d065a49768467e8eacc4640aa,Greek God Fit,1222 Fist Ave,San Diego,CA,92187,US,,,...,"[0,1,1,1,0,0,1,1,2,0,2,0,1,1,0,0,3,0,0,0,0,1,0...",060730053003,"{""US"":125}",17902,59.0,"{""<5"":5,""5-20"":47,""21-60"":72,""61-240"":78,"">240...","{""Shell Oil"":13,""Islands Restaurants"":7,""Rubio...","{""Starbucks"":13,""Jack in the Box"":11,""Costco W...","{""android"":81,""ios"":59}",1

{'91910': ['Bella Mia Exclusive Events',
  1,
  ['El Comal', 1],
  ['7-Eleven', 1],
  ['National Glass Experts', 1],
  ["Wings N' Things", 1]],
 '92067': ['Rancho Santa Fe Pharmacy',
  1,
  ['Merrill Lynch', 1],
  ['Caffe Positano', 1],
  ['Del Mar Country Club', 1],
  ['Mille Fleurs', 1]],
 '92135': ['Navy Gateway Inns & Suites',
  1,
  ["Auntie Anne's", 1],
  ['Subway', 1],
  ['Subway', 1],
  ['Pizza Parlor', 1]],
 '92118': ['CrossFit',
  1,
  ['Rotary Park', 1],
  ['Avenue Liquor And Wine Store', 1],
  ['Cutler Field', 1],
  ['Coronado Pathways Charter', 1]],
 '92173': ['Timberland',
  1,
  ['Best Western', 1],
  ['Ghirardelli Chocolate Outlet & Ice Cream Shop', 1],
  ['Boba N More', 1],
  ['JC Power Audio Shop', 1]],
 '91942': ['SpeeDee Oil Change & Auto Service',
  1,
  ['Fix Auto Worldwide', 1],
  ['El Cerrito Veterinary Hospital', 1],
  ['Dream Dinners', 1],
  ['Leo Hamel K 8 Academy', 1]],
 '92025': ['T-Mobile',
  1,
  ['Boot Barn', 1],
  ['Church of St Timothy', 1],
  ['Manee Thai Massage and Spa', 1],
  ['Bodywork By Barbara', 1]],
 '92008': ['Sally Beauty Supply',
  1,
  ['Ooh La La', 1],
  ["Knights' Smokehouse BBQ", 1],
  ['Pedego Electric Bikes Carlsbad', 1],
  ['Deconstructed', 1]],
 '92111': ['San Diego Gun Graphics',
  1,
  ['CrossFit', 1],
  ['Chopstix', 1],
  ['KARAMI Ramen', 1],
  ['Ab Auto Upholstery', 1]],
 '92020': ['Rana Mansour DPM',
  1,
  ['Caldemeyer Cortland S DDS', 1],
  ['BMW of El Cajon', 1],
  ['Neighborhood Healthcare El Cajon', 1],
  ['Wild Orchid Florist', 1]],
 '92110': ['Pardee Legal Research Center',
  1,
  ['Copley Library', 1],
  ['San Diego Rent A Car', 1],
  ['Burger King', 1],
  ["Geppetto's", 1]],
 '92154': ['IMAX',
  1,
  ['Blaze International', 1],
  ['USA Gasoline', 1],
  ["Nieblas Flower's", 1],
  ['Express Auto Auction', 1]],
 '92106': ["Jensen's Foods",
  1,
  ['San Diego Sailing Academy', 1],
  ['Aquarius Yacht Services', 1],
  ['Strolling for Fitness', 1],
  ['The WestBean Coffee Roasters', 1]],
 '92083': ["Howard's Refinishing & Upholstery",
  1,
  ['Olive Avenue RV Resort', 1],
  ['Oriental Medical Arts', 1],
  ["Spicer's Shaggy Dog", 1],
  ['Vista Inn', 1]],
 '91911': ['Economy Upholstery',
  1,
  ["McDonald's", 1],
  ['Great Happiness Chinese Fast Food II', 1],
  ['Stockers Motorcycle', 1],
  ['Harborside State Preschool', 1]],
 '92014': ["Geppetto's",
  1,
  ['Cafe Del Mar', 1],
  ['Trattoria Ponte Vecchio', 1],
  ['Del Mar Antique Show & Sale', 1],
  ['Carmel Valley Market Wine & Spirits', 1]],
 '92081': ['Tri City PET CT',
  1,
  ["Access Children's Dental Group", 1],
  ['Grand Slam Pizza', 1],
  ["Niko's Steak Burgers And Greek Food", 1],
  ['Diamond Body Fitness', 1]],
 '92026': ['Norco Trailers',
  1,
  ['Ross Stores', 1],
  ['El Pollo Loco', 1],
  ['HearUSA', 1],
  ['Meadows Deli Market', 1]],
 '92024': ['Guitar Lesson Live',
  1,
  ['Encinitas Surfboards', 1],
  ['Freewater School of Supernatural Discipleship', 1],
  ['Sugaring By The Sea', 1],
  ['Oak Crest Park', 1]],
 '91977': ['Lonjean Cheveux Studio',
  1,
  ['A1 Smoke Shop', 1],
  ['Best Buy Autos', 1],
  ['CubeSmart', 1],
  ['Little Caesars', 1]],
 '92131': ['Allstate Insurance',
  1,
  ['Saint Gregory The Great Catholic Church', 1],
  ['The Place Catering', 1],
  ['C2 Education', 1],
  ['Renaissance Village Academy', 1]],
 '92029': ['Church of God Escondido',
  1,
  ['The Gift Shops at PPH', 1],
  ["The Men's Wearhouse", 1],
  ['Del Dios Preserve', 1],
  ['SOS Entertainment', 1]],
 '92084': ['Vista Buggy Bath',
  1,
  ['Kents Bromeliad', 1],
  ['Bolanos Earth Works', 1],
  ["Children's Paradise School Age", 1],
  ["Corky's Refinishing & Antique", 1]],
 '92021': ['Financial 21 Community Credit Union',
  1,
  ['Black Angus Steakhouse', 1],
  ['Ready Set Grow Infant', 1],
  ['Stereo Depot', 1],
  ['China 1968', 1]],
 '92101': ['Angkorian Pikestaff',
  1,
  ['SpringHill Suites by Marriott', 1],
  ['Brooklyn Dogs', 1],
  ['Bar One', 1],
  ['Carte Hotel', 1]],
 '92007': ['Sambazon Acai Cafe Cardiff',
  1,
  ['Body Blu', 1],
  ['Encinitas Elks Lodge 2243', 1],
  ["Children's Atelier Center", 1],
  ['F45 Training Cardiff', 1]],
 '91950': ['AAHARN National City',
  1,
  ['SAF Collision Center Inc', 1],
  ['Walmart', 1],
  ['GET FIXED Nails and Spa', 1],
  ['Tacotorro Taco Shop', 1]],
 '92105': ['Spotts Liquor',
  1,
  ['Ban Lao Cuisine', 1],
  ['Beach Club Grammar School', 1],
  ['R Diaz Trucking', 1],
  ['Union Bank', 1]],
 '92139': ['Bee &amp Tea',
  1,
  ['United States Postal Service (USPS)', 1],
  ["McDonald's", 1],
  ['Fade Factory Barbershop', 1],
  ['Opalec Board and Care', 1]],
 '91901': ['The Heights Charter',
  1,
  ['Harris Financial And Insurance Service', 1],
  ['Viejas Fire Department', 1],
  ["Fred's Old Fashioned Burgers", 1],
  ['Tommy Hilfiger', 1]],
 '92004': ['Red Ocotillo',
  1,
  ['J&T Tire Pros', 1],
  ['Oxford Preparatory Academy', 1],
  ['Frugal Coyote Boutique & Resale Shop', 1],
  ['Borrego Springs Sculptures', 1]],
 '92109': ['Tuesday Morning',
  1,
  ['Mission Boulevard Dental Group', 1],
  ['ASL Remodeling', 1],
  ['Koffee Kat', 1],
  ['Beach Treats', 1]],
 '92069': ['UpTop Moving &amp Storage',
  1,
  ["Kent's Bromeliad", 1],
  ['Project Athlete', 1],
  ['Mark Cafagna Cafagna Chiropractic', 1],
  ['Sunbelt Rentals', 1]],
 '92108': ['Staples',
  1,
  ['SAS San Antonio Shoemakers', 1],
  ['Stella Moving & Delivery', 1],
  ['Gehegan & Associates', 1],
  ['John C Johnston DC', 1]],
 '92028': ['Iowa Street',
  1,
  ['Fallbrook Towne Center', 1],
  ['Straight Nutrition', 1],
  ['Phyllis Encouragement Factor', 1],
  ["Aydee's Garnacheria", 1]],
 '92071': ['Undisputed Autowerks',
  1,
  ['Brinegar Chiropractic', 1],
  ['CPR of San Diego', 1],
  ['Lakes Market & Deli', 1],
  ['The Lean Bean', 1]],
 '92104': ['United Pacific',
  1,
  ['North Park Family Health Center', 1],
  ['Caffe Calabria', 1],
  ['H L Beauty', 1],
  ['King Music', 1]],
 '92120': ['Ftd',
  1,
  ['San Diego Combat Academy', 1],
  ['Davison Distributions', 1],
  ['Spine Institute of San Diego', 1],
  ['Goodwill Bookstore', 1]],
 '92019': ['Hilton Head Park',
  1,
  ['Healthy Pet Pantry', 1],
  ['Monette Tree Service', 1],
  ['CA Clothing', 1],
  ['Shell Oil', 1]],
 '92127': ['KinderCare',
  1,
  ['San Diego Liberal Arts Academy', 1],
  ['Team Koch', 1],
  ['Spreckels Park', 1],
  ['Just Run', 1]],
 '92121': ['Lean and Green Cafe',
  1,
  ['Weebikeshop', 1],
  ['MRI Scan Group', 1],
  ['National Motors', 1],
  ['Manna Auto Center', 1]],
 '92161': ['San Diego VA Medical Center',
  1,
  ['San Diego VA Hospital Cafeteria', 1],
  ['Veterans Medical Research Foundation', 1],
  ['Palm Desert Resuscitation Education San Diego', 1],
  ['Academic Integrity Office', 1]],
 '92103': ['Taqueria',
  1,
  ['La Vecindad', 1],
  ["Micho'z Fresh Lebanese Grill", 1],
  ['Body Align Massage', 1],
  ['Hookabana Lounge', 1]],
 '91915': ['Famous Footwear',
  1,
  ['Goodwill Industries', 1],
  ["Jersey Mike's", 1],
  ['Subway', 1],
  ['Professional Tax Service', 1]],
 '92117': ['Hawthorne Elementary',
  1,
  ['Rose Canyon Animal Hospital', 1],
  ['Taco Bell', 1],
  ['Clairemont Village', 1],
  ['Easy Fast Cheap Online Traffic School', 1]],
 '92129': ['Rolling Hills Elementary School Preschool',
  1,
  ['Jack in the Box', 1],
  ['Four Seasons Flowers', 1],
  ['CVS', 1],
  ['Evans Tire & Service Centers', 1]],
 '92115': ['Rolando Best Appliance Services',
  1,
  ['Duet Coffee', 1],
  ['La Mesa TV Supply', 1],
  ['Farmers Insurance Group', 1],
  ['Sala Thai', 1]],
 '92065': ['Dollar Tree',
  1,
  ["Charlie's Garage", 1],
  ['MDS Diesel Service', 1],
  ['B Street Express Car Wash', 1],
  ['R Town Strength & Wellness', 1]],
 '92056': ['USP Incorporated',
  1,
  ['The Crimson Cake', 1],
  ['Starbucks', 1],
  ["Kohl's", 1],
  ['Enchanted Elephant Healing', 1]],
 '92122': ['Starbucks',
  1,
  ['Lacoste', 1],
  ['Oxford auto outlet', 1],
  ['LEGO', 1],
  ['SAS Towing', 1]],
 '92107': ['Bela Development',
  1,
  ['AutoZone', 1],
  ['San Diego Fire Rescue Department Station 15', 1],
  ['The Black', 1],
  ["Poma's Italian Deli", 1]],
 '91913': ["MJ's Yogurt Time and Deli",
  1,
  ["D K Che'", 1],
  ['7-Eleven', 1],
  ['Phase 4 Computer Repair', 1],
  ['Chula Vista Heritage Skatepark', 1]],
 '92064': ['Pomerado Manor',
  1,
  ["Tio Leo's Cantina", 1],
  ['Starbucks', 1],
  ['Polo Lessons San Diego', 1],
  ['Poway Vision Care', 1]],
 '92102': ['La Fachada',
  1,
  ['Foundation Building Materials (FBM)', 1],
  ['Center For Employment Training San Diego', 1],
  ['FIX Salon', 1],
  ['Iglesia Presbiteriana Hispana', 1]],
 '92128': ['Krispy Kreme Doughnuts',
  1,
  ['Sun Orthodontics Melanie H Duong DMD MS', 1],
  ['Starbucks', 1],
  ['The Baked Bear', 1],
  ['iGifts And Cards', 1]],
 '92037': ['Elixir Espresso & Wine Bar',
  1,
  ['All About Animals', 1],
  ['La Jolla Village Square', 1],
  ['J Mclaughlin', 1],
  ['The Promiscuous Fork', 1]],
 '92116': ['Coastal Ink and Toner',
  1,
  ['Pop Pie Co', 1],
  ['Bench Home', 1],
  ['Normal Heights Barbershop', 1],
  ['Hayk & Bel Sport Club', 1]],
 '92123': ['First Fishery Development Services',
  1,
  ['Larson Sharpening', 1],
  ['San Diego Superior Court Traffic Division', 1],
  ['Learn To Fly San Diego', 1],
  ['Accel Motors', 1]],
 '92075': ['Hallmark Communities',
  1,
  ['Casa de las Orquideas', 1],
  ['David Alan Collection', 1],
  ['Solana Beach Fire Department', 1],
  ['Verve Plastic Surgery', 1]],
 '92126': ['Metroplex Shopping Center',
  1,
  ['Miramar H&A Auto Repair Center II', 1],
  ['PORSCHE SAN DIEGO', 1],
  ['IHOP', 1],
  ['Ku Champions Llc Salk Elementary Preschool', 1]],
 '92054': ['Oceanside Driveline',
  1,
  ['Impulse Surf Products', 1],
  ['Cameron Fitness', 1],
  ['Harbor Freight Tools', 1],
  ['Oceanside Florist', 1]],
 '92078': ['Streamline Autobody',
  1,
  ['Fresh MXN Food', 1],
  ['TekDeals', 1],
  ['Center For Children & Families At Cal State Sms', 1],
  ['Quick Charge Power', 1]],
 '91906': ['Saint Adelaide Church',
  1,
  ['El Paso Taco Shop', 1],
  ['Cameron Corners Convenient Store', 1],
  ['Circle K', 1],
  ['Campo Green Store', 1]],
 '92027': ['Escondido Fire Department Station 2 East Valley',
  1,
  ['Prestige Exteriors Landscaping', 1],
  ['Vietnam Veterans of America Donation Pickup Service', 1],
  ['El Huarache Taco Shop', 1],
  ['Escondido Barber Shop', 1]],
 '91945': ['Big Boyz Car Audio',
  1,
  ['Gold Coast Motors', 1],
  ["Blanca's Family Day Care", 1],
  ['St John Of The Cross School', 1],
  ['David Labrana DC', 1]],
 '92058': ['Freeway Insurance Services',
  1,
  ['Kaad Engineering', 1],
  ["Milano's Liquor", 1],
  ['San Luis Rey Bakery & Restaurant', 1],
  ["Sew O'side", 1]],
 '92082': ['All American Septic Pumping & Services',
  1,
  ['The Cafe', 1],
  ['Heatshield Products', 1],
  ['C87 Roofing', 1],
  ['Greens Storage', 1]],
 '92060': ['Palomar Mountain General Store',
  1,
  ['Fry Creek Campground', 1],
  ['Palomar Observatory', 1],
  ['Fama Living San Diego', 1],
  ["Mother's Kitchen", 1]],
 '92011': ['Tip Top Meats & European Delicatessen',
  1,
  ['Argyle Steakhouse', 1],
  ['K1 Speed', 1],
  ['Lift Supports Depot', 1],
  ['United States Postal Service (USPS)', 1]],
 '91932': ['A & M Mobile Auto Repair',
  1,
  ['Dollar Tree', 1],
  ['Corrales Tax & Insurance Services', 1],
  ['13th St Market', 1],
  ['Imperial Beach Fire Department Station 39', 1]],
 '91941': ['Fuel Deli',
  1,
  ['IHOP', 1],
  ['Sierra Markets', 1],
  ["Abc Barn Children's Place Extended Day", 1],
  ['KinderCare', 1]],
 '92113': ['All Rider Gear',
  1,
  ['Six Maritime Weapons Simulator', 1],
  ["Ol' Fashioned Lumber", 1],
  ['Dough Nations', 1],
  ['Diamond Maintenance Services', 1]],
 '91905': ['B D Masonry',
  1,
  ['Manzanita Diner', 1],
  ['United States Postal Service (USPS)', 1],
  ['Clover Flat Elementary', 1],
  ['Wisteria Candy Cottage', 1]],
 '91980': ['TC Worthy Cash & Carry',
  1,
  ['Baja Mex Video', 1],
  ['Tecate Christian School', 1],
  ['JMM Construction & Remodeling', 1],
  ['Ramco Petroleum', 1]],
 '92114': ['Stevens moving & junk hauling service',
  1,
  ['Nye Elementary', 1],
  ['Evangeline Roberts Institute Of Learning P S', 1],
  ['Morse High', 1],
  ['Master Barbers', 1]],
 '92119': ['BRSH FLSS Pediatric Dentistry',
  1,
  ['5 Star Customs', 1],
  ['Richie Heating Air Conditioning Units Services', 1],
  ["Grow Smart Children's Academy", 1],
  ['Cowles Mountain Coffee', 1]],
 '91962': ['United States Postal Service (USPS)',
  1,
  ['Mountain Empire Special Education Preschool', 1],
  ["Major's Diner", 1],
  ['Mountain Empire High', 1],
  ['Pine Valley Store', 1]],
 '92040': ['Socal Auto Repair Center',
  1,
  ["Lakeside Presb Preschool & Children's Ctr", 1],
  ['JT Diesel', 1],
  ["Rosarito's Mexican Food", 1],
  ['Greek Chicken', 1]],
 '92070': ['Wynola Pizza & Bistro',
  1,
  ['California Mountain Bakery', 1],
  ['Mountain Source Santa Ysabel', 1],
  ["Don's Market", 1],
  ['The Barn Vintage Marketplace', 1]],
 '91902': ['Town & Country Animal Hospital',
  1,
  ['Frutas 100 Natural', 1],
  ['Pinata District Party Supply & Candy', 1],
  ['Accountants', 1],
  ['J E T S Espresso', 1]],
 '92009': ['TCO Appraisals',
  1,
  ['Casero Taqueria', 1],
  ['Shelley Lee Boyce', 1],
  ['La Costa Glen', 1],
  ['Faith Community Church', 1]],
 '92057': ['Peppertree Montessori',
  1,
  ["McDonald's", 1],
  ['Sally Beauty Supply', 1],
  ["Victoria's Mexican Food", 1],
  ['GNC (General Nutrition Centers)', 1]],
 '91978': ['Ice Cream Depot',
  1,
  ['Liberty Call Distilling LLC', 1],
  ['Circle K', 1],
  ['Wienerschnitzel', 1],
  ['Atonement Lutheran Church Missouri Synod', 1]],
 '92182': ['The Habit Burger Grill',
  1,
  ['Salad Bistro', 1],
  ['Juice It Up!', 1],
  ['Parking Structure 6', 1],
  ['Associated Students Child Care Center Infant Ctr', 1]],
 '92130': ['Bdo',
  1,
  ['The League of Amazing Programmers', 1],
  ["Sammy's Woodfired Pizza and Grill", 1],
  ['Little Rookies T Ball School', 1],
  ['Yoga Six', 1]],
 '91914': ['Office Depot',
  1,
  ['Aaron Chaney Fitness', 1],
  ['The Phana Par Group at Caliber Home Loans', 1],
  ['Foundry United Methodist Church', 1],
  ['Credit Corner', 1]],
 '92036': ["Fat Anthony's Delicatessen",
  1,
  ['All State Propane', 1],
  ['Julian Homes and Happenings', 1],
  ['Redding Ray High Continuation', 1],
  ['La Cima Conservation Camp 42', 1]],
 '92010': ['Drain Crew',
  1,
  ['Schreyer Audio', 1],
  ['Carlsbad Training Camp', 1],
  ['Frank Financial Advisors', 1],
  ['Build at Home Skateparks', 1]],
 '92055': ['Leatherneck Lanes',
  1,
  ['Subway', 1],
  ["McDonald's", 1],
  ['Pendleton Family Dental', 1],
  ['United States Postal Service (USPS)', 1]],
 '92003': ['Bonsall Flowers and Gifts',
  1,
  ['Outrider Motorcycles', 1],
  ['San Luis Rey River Park', 1],
  ['Rainbow Meal Worms', 1],
  ['Bonsall Fine Wine and Spirits', 1]],
 '92136': ['Fleet and Family Support Center',
  1,
  ['MAC Cosmetics', 1],
  ['Admiral Robinson Recreation Centre', 1],
  ['Navy Federal Credit Union Restricted Access', 1],
  ["Bruegger's", 1]],
 '92059': ['Gems of Pala',
  1,
  ['Pala Fitness Center', 1],
  ['Cave', 1],
  ['Mission San Antonio De Pala', 1],
  ['Pala Reservation Fire Department', 1]],
 '92124': ['SD Prime Limo Service',
  1,
  ['Spa No 5', 1],
  ['Lucas River Drums', 1],
  ['Canine Cleaners', 1],
  ['Tierrasanta Lutheran Church', 1]],
 '92091': ['Top3Dentists com',
  1,
  ['Allstate Insurance', 1],
  ['Von Henkle Equestrian', 1],
  ['Rancho Riding Club', 1],
  ['Kupiec Orthodontics & Pediatric Dentistry', 1]],
 '92061': ['Village Nurseries',
  1,
  ['Maac Project Pauma Valley Headstart State Preschoo', 1],
  ['Kica Mik Overlook', 1],
  ['St Francis Episcopal Church', 1],
  ['Pauma Valley Trading Center', 1]],
 '91916': ['Descanso Hay & Feed',
  1,
  ['Descanso Branch Library', 1],
  ['Descanso Elementary', 1],
  ['Descanso Mercantile', 1],
  ['Amos Fence', 1]],
 '91935': ['Greater San Diego Academy',
  1,
  ['coyote canyon Cafe', 1],
  ["Tony Gwynn's Sports Pub", 1],
  ['Jamul Dulzura Union School District Preschool', 1],
  ['True Value Hardware', 1]],
 '92140': ['Frontwave Credit Union',
  1,
  ['United States Postal Service (USPS)', 1],
  ['NTC MCRD Energy Facility', 1],
  ['Duncan Hall', 1],
  ['Marine Corps Recruit Depot Library', 1]],
 '92093': ['Starbucks',
  1,
  ['Allen Field', 1],
  ['Shiley Eye Institute at UC San Diego Health', 1],
  ['Digital Media Academy', 1],
  ['USE Credit Union', 1]],
 '92132': ['San Diego Aircraft Carrier Museum',
  1,
  ['Animae', 1],
  ['Nima Cafe', 1],
  ['Quality Coast Gourmet Street Kitchen', 1]],
 '92086': ['Warner Union School District Pre School',
  1,
  ['San Jose Valley Continuation High', 1],
  ['Warner Carrillo Ranch House Museum', 1],
  ['Warner Springs Resort', 1],
  ['Warner Springs Ranch Resort', 1]],
 '92155': ["Surinder's Coffeeshack",
  1,
  ['Navy Gateway Inn & Suites', 1],
  ['Subway', 1],
  ['Navy Exchange', 1],
  ['Naval Amphibious Base Coronado', 1]],
 '91963': ['Rancho Noel',
  1,
  ['Potrero Elementary', 1],
  ['Cafe 94', 1],
  ['Potrero Elementary State Preschool Center', 1],
  ['San Diego Rural Fire Protection District Station 39 Potrero', 1]],
 '92145': ['Firestone Complete Auto Care',
  1,
  ['A 1 Soils Hanson Aggregates', 1],
  ['Jamba', 1],
  ["Dunkin'", 1],
  ['MCAS Miramar Memorial Golf Course', 1]],
 '92092': ['Foodworx', 1],
 '92134': ['Vincennes University Nab',
  1,
  ['Navy Exchange', 1],
  ['San Diego Lawn Bowling Club', 1],
  ['Saint Tropez Bistro', 1],
  ['NMC San Diego', 1]],
 '91944': ['Grossmont High',
  1,
  ['Grossmont Union High Special Education Program', 1],
  ['Express Gasoline', 1],
  ['Skatedogz', 1]],
 '92150': ['Bias Handyman Services', 1],
 '92038': ['San Diego Seaplanes', 1],
 '91917': ['Active Shooter Defense School',
  1,
  ['Barrett Junction Cafe & Mercantile', 1],
  ['San Diego Rural Fire Protection District Station 35 Dulzura', 1],
  ['911academy', 1],
  ['Dulzura California', 1]],
 '92179': ['DaVita',
  1,
  ['Richard J Donovan Correctional Facility', 1],
  ['R J Donovan Correctional Facility Rjd', 1]],
 '92066': ['Montezuma Valley Market', 1],
 '92049': ['Aliso Creek Rest Area', 1, ['Sunset Market', 1]],
 '91934': ['Shell Oil',
  1,
  ['Wright Fuel Stop Jacumba', 1],
  ['San Diego Rural Fire Protection District Station 43 Jacumba', 1],
  ['Desert View Tower', 1],
  ['Jacumba Library', 1]],
 '92096': ["Crash's Cafe",
  1,
  ['Panda Express', 1],
  ['Annual San Marcos Fitness Roundup', 1],
  ['Jamba', 1],
  ['Campus Coffee Cart', 1]],
 '92153': ['Sharp Perfection', 1],
 '92023': ['Stylehawk Event Services', 1],
 '92158': ['San Diego Rural Fire Protection District Station 22 Otay Mesa',
  1,
  ['George F Bailey Detention Facility', 1],
  ['East Mesa Juvenile Detention Facility', 1],
  ['Facility 8 Detention Facility', 1],
  ['East Mesa Reentry Facility', 1]],
 '92199': ['Greasy Spoon Mls Cafeteria',
  1,
  ['United States Postal Service (USPS)', 1]],
 '92079': ['Montiel Park Disc Golf Course', 1],
 '92174': ['Excellence General Construction', 1],
 '91931': ['Guatay Mountain Nursery',
  1,
  ['Guatay Country Store', 1],
  ['Guatay Christian Fellowship', 1],
  ['Tryyn Wooden Spoon Gallery', 1]],
 '92022': ['SDR Contracting', 1],
 '92152': ['Subway', 1, ['SPAWAR Systems Center Pacific Cafeteria', 1]],
 '92169': ['Taylor Made Fitness', 1, ['RJ Landscape Construction', 1]],
 '92147': ['Navy Base Point Loma Gym',
  1,
  ['NMAWC Fitness Center', 1],
  ['Admiral Kidd Catering & Conference Center', 1],
  ['US Navy Recruiting Office', 1],
  ['Naval Base Point Loma', 1]],
 '92039': ['International Center Resale Shop', 1],
 '92125': ["City Heights Farmers' Market", 1],
 '92088': ['Lawn', 1, ['I Metro', 1]],
 '92178': ['Glorietta Bay Park', 1],
 '92085': ['JJ Septic & Drain Service', 1],
 '92033': ['Guanni Chocolate', 1],
 '91948': ['Mount Laguna Campground', 1, ['Tiny House Block', 1]],
 '92138': ['Drama Kids', 1],
 '92112': ['Remotely Virtual Services', 1],
 '92187': ['Greek God Fit', 1]}