# Data Source Check
Th purpose of this notebook is to do a lightweight exploration of any of the datasets within the SafeGraph project. If there's an issue with loading in the dataset into the SQL database, then you can explore that issue in here. (This of it as a scratchbook)

In [1]:
# import statements
import pandas as pd

#### ---- Update Date: 12/02/2020 ----

In [2]:
new_data = pd.read_csv('//sandag.org/home/shared/Technical Services/EDAM/SafeGraph_COVID19/v2/main-file/2020-01-13-weekly-patterns-fixed.csv', nrows=100)
new_data.head()

,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,date_range_start,...,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type
0,sg:0013bd02b3564a9187a52f8e2799233e,Small Business Transactions,1007 Mill Crescent Pl Ste 274,Arlington,TX,76006,US,NaN,NaN,2020-01-13T00:00:00-06:00,...,484391131041,"{""484391131041"":15,""484391141024"":4,""481130141...","{""484391131041"":12,""484391054051"":4,""484391136...","{""US"":34}",3247.0,122.0,"{""<5"":0,""5-20"":18,""21-60"":13,""61-240"":26,"">240...","{""Wingstop"":12,""Best Western"":12,""Shell Oil"":1...","{""Walmart"":13,""Jack in the Box"":9,""Exxon Mobil...","{""android"":24,""ios"":14}"
1,sg:001955fa1c994b4c8c877316a66dd986,McDonald's,1134 280 By Pass,Phenix City,AL,36867,US,SG_BRAND_5179b21fc1d50950b99b4eecaa48c614,McDonald's,2020-01-13T00:00:00-06:00,...,11130306001,"{""011130309021"":19,""011130309022"":18,""01113030...","{""011130309022"":17,""011130309021"":17,""01113030...","{""US"":284}",7691.0,9.0,"{""<5"":25,""5-20"":233,""21-60"":45,""61-240"":25,"">2...","{""Marathon"":10,""Walmart"":9,""Waffle House"":8,""F...","{""Walmart"":34,""Dollar General"":16,""Marathon"":1...","{""android"":177,""ios"":109}"
2,sg:001e39c6b18645a5950b13a278b242c3,Peking House,9617 Liberty Ave,Ozone Park,NY,11417,US,NaN,NaN,2020-01-13T00:00:00-05:00,...,360810040021,"{""360810040021"":7,""360810040011"":6,""3610312340...","{""360810062022"":5,""360610245001"":4,""3606100890...","{""US"":79}",2233.0,16.5,"{""<5"":3,""5-20"":48,""21-60"":29,""61-240"":5,"">240""...","{""Burger King"":22,""White Castle"":11,""Stop & Sh...","{""Dunkin'"":14,""BP"":11,""Baskin Robbins"":11,""Bur...","{""android"":43,""ios"":36}"
3,sg:0021f605c7904ed2a3f7bd28d6c40844,ATI Physical Therapy,1111 E 87th St Ste 600,Chicago,IL,60619,US,SG_BRAND_0f6312930cd009ca4e8d974d0a302ec3,ATI Physical Therapy,2020-01-13T00:00:00-06:00,...,170314701002,{},{},{},NaN,17.0,"{""<5"":0,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":0}"
4,sg:0023804ee36c4056886ef54e5a0cb773,American Express Financial Advisors,4210 Metro Pkwy Ste 230,Fort Myers,FL,33916,US,NaN,NaN,2020-01-13T00:00:00-05:00,...,120710012011,"{""120710101033"":4,""120710502041"":4,""1207108020...","{""120710012011"":14,""120710201012"":4,""120710101...","{""US"":34}",12173.0,104.0,"{""<5"":3,""5-20"":13,""21-60"":10,""61-240"":25,"">240...","{""Walmart"":15,""7-Eleven"":7,""Tires Plus"":6,""Hon...","{""Walmart"":22,""7-Eleven"":19,""Walgreens"":11,""Sh...","{""android"":23,""ios"":10}"

In [3]:
new_data.columns

Index(['safegraph_place_id', 'location_name', 'street_address', 'city',
       'region', 'postal_code', 'iso_country_code', 'safegraph_brand_ids',
       'brands', 'date_range_start', 'date_range_end', 'raw_visit_counts',
       'raw_visitor_counts', 'visits_by_day', 'visits_by_each_hour', 'poi_cbg',
       'visitor_home_cbgs', 'visitor_daytime_cbgs',
       'visitor_country_of_origin', 'distance_from_home', 'median_dwell',
       'bucketed_dwell_times', 'related_same_day_brand',
       'related_same_week_brand', 'device_type'],
      dtype='object')

In [4]:
old_data = pd.read_csv('//sandag.org/home/shared/Technical Services/EDAM/SafeGraph_COVID19/v2/main-file/2020-12-02-weekly-patterns-part1.csv', nrows=100)
old_data.head()

,placekey,safegraph_place_id,location_name,street_address,city,region,postal_code,iso_country_code,safegraph_brand_ids,brands,...,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,visitor_country_of_origin,distance_from_home,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type
0,226-223@8fc-8ct-cnq,sg:00011ea2089a4795874f987b8ae534fe,Oriental Gourmet,8456 Gulf Fwy,Houston,TX,77017,US,NaN,NaN,...,482013332012,"{""482013340012"":4,""480396604003"":4,""4820123230...","{""482014229001"":4,""482014106001"":4,""4816772400...","{""US"":30}",9781.0,60.5,"{""<5"":1,""5-20"":2,""21-60"":14,""61-240"":10,"">240"":7}","{""Monroe"":100,""Floor and Decor"":20,""Dollar Gen...","{""Monroe"":100,""Walmart"":24,""Sellers Bros."":16,...","{""android"":27,""ios"":6}"
1,222-222@5z7-z4p-52k,sg:00035ee2a75e41c7a6fe143a7f1895e9,BV Grill,10256 Golf Course Rd,Taft,CA,93268,US,NaN,NaN,...,60290033041,"{""060290032063"":4}","{""060290038093"":4}","{""US"":12}",27486.0,9.5,"{""<5"":2,""5-20"":8,""21-60"":4,""61-240"":0,"">240"":0}","{""T.J. Maxx"":19}","{""Costco Gasoline"":22,""Starbucks"":19,""Dick's S...","{""android"":9,""ios"":6}"
2,zzw-223@646-9rk-nqz,sg:00083de836884deeae33d8f5aa622049,Cash & Dash 7,701 Highway 701 N,Loris,SC,29569,US,NaN,NaN,...,450510202001,"{""450510202001"":4}","{""450679505004"":4}","{""US"":5}",7252.0,10.0,"{""<5"":0,""5-20"":4,""21-60"":3,""61-240"":0,"">240"":0}","{""Family Dollar Stores"":49}","{""Hardee's"":66,""Food Lion"":49,""Dollar General""...","{""android"":4,""ios"":4}"
3,zzy-222@8dj-gdv-5fz,sg:0009738f1e8f43aabbe5a18cc249ade6,Mahalos Sweet Ice Co,400 Trillium Blvd,Spring Hill,FL,34604,US,NaN,NaN,...,120530409112,"{""120530409112"":4,""121010315071"":4}","{""121010315071"":4}","{""US"":6}",485.0,183.5,"{""<5"":0,""5-20"":7,""21-60"":4,""61-240"":5,"">240"":14}","{""Five Below"":25,""7-Eleven"":25}","{""Rural King"":25,""Applebee's"":25,""Wawa"":24,""Du...","{""android"":4,""ios"":4}"
4,zzy-222@8gm-r4c-qzz,sg:0009e0fc0cb84885a115381d73635118,Geraldine Convenient Storage Al Hwy 75 N,41758 AL Highway 75,Geraldine,AL,35974,US,NaN,NaN,...,10499606003,"{""010499605001"":4,""010499606003"":4}",{},"{""US"":4}",13719.0,31.0,"{""<5"":0,""5-20"":2,""21-60"":2,""61-240"":3,"">240"":0}","{""Subway"":32}","{""Dollar General"":56,""Tractor Supply Co."":39,""...","{""android"":4,""ios"":4}"

In [5]:
old_data.columns

Index(['placekey', 'safegraph_place_id', 'location_name', 'street_address',
       'city', 'region', 'postal_code', 'iso_country_code',
       'safegraph_brand_ids', 'brands', 'date_range_start', 'date_range_end',
       'raw_visit_counts', 'raw_visitor_counts', 'visits_by_day',
       'visits_by_each_hour', 'poi_cbg', 'visitor_home_cbgs',
       'visitor_daytime_cbgs', 'visitor_country_of_origin',
       'distance_from_home', 'median_dwell', 'bucketed_dwell_times',
       'related_same_day_brand', 'related_same_week_brand', 'device_type'],
      dtype='object')

In [6]:
print(new_data.info())
print(old_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   safegraph_place_id         100 non-null    object
 1   location_name              100 non-null    object
 2   street_address             100 non-null    object
 3   city                       100 non-null    object
 4   region                     100 non-null    object
 5   postal_code                100 non-null    int64
 6   iso_country_code           100 non-null    object
 7   safegraph_brand_ids        33 non-null     object
 8   brands                     33 non-null     object
 9   date_range_start           100 non-null    object
 10  date_range_end             100 non-null    object
 11  raw_visit_counts           100 non-null    int64
 12  raw_visitor_counts         100 non-null    int64
 13  visits_by_day              100 non-null    object
 14  visits_by_each_hour        100 non-null    object
 15  poi_cbg                    100 non-null    int64
 16  visitor_home_cbgs          100 non-null    object
 17  visitor_daytime_cbgs       100 non-null    object
 18  visitor_country_of_origin  100 non-null    object
 19  distance_from_home         78 non-null     float64
 20  median_dwell               100 non-null    float64
 21  bucketed_dwell_times       100 non-null    object
 22  related_same_day_brand     100 non-null    object
 23  related_same_week_brand    100 non-null    object
 24  device_type                100 non-null    object
dtypes: float64(2), int64(4), object(19)
memory usage: 19.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   placekey                   100 non-null    object
 1   safegraph_place_id         100 non-null    object
 2   location_name              100 non-null    object
 3   street_address             100 non-null    object
 4   city                       100 non-null    object
 5   region                     100 non-null    object
 6   postal_code                100 non-null    int64
 7   iso_country_code           100 non-null    object
 8   safegraph_brand_ids        25 non-null     object
 9   brands                     25 non-null     object
 10  date_range_start           100 non-null    object
 11  date_range_end             100 non-null    object
 12  raw_visit_counts           100 non-null    int64
 13  raw_visitor_counts         100 non-null    int64
 14  visits_by_day              100 non-null    object
 15  visits_by_each_hour        100 non-null    object
 16  poi_cbg                    100 non-null    int64
 17  visitor_home_cbgs          100 non-null    object
 18  visitor_daytime_cbgs       100 non-null    object
 19  visitor_country_of_origin  100 non-null    object
 20  distance_from_home         78 non-null     float64
 21  median_dwell               100 non-null    float64
 22  bucketed_dwell_times       100 non-null    object
 23  related_same_day_brand     100 non-null    object
 24  related_same_week_brand    100 non-null    object
 25  device_type                100 non-null    object
dtypes: float64(2), int64(4), object(20)
memory usage: 20.4+ KB
None

In [8]:
# check if there are any new columns between the data --> in this case, no
for col_names in new_data.columns:
    if col_names not in old_data.columns:
        print(col_names)

In [9]:
# visually the device type rows are the same as well (showed that there was an error here when loading into SQL database)
display(new_data['device_type'])
display(old_data['device_type'])

0       {"android":24,"ios":14}
1     {"android":177,"ios":109}
2       {"android":43,"ios":36}
3         {"android":0,"ios":0}
4       {"android":23,"ios":10}
                ...
95        {"android":0,"ios":4}
96       {"android":14,"ios":5}
97       {"android":11,"ios":5}
98       {"android":15,"ios":7}
99      {"android":88,"ios":35}
Name: device_type, Length: 100, dtype: object

0     {"android":27,"ios":6}
1      {"android":9,"ios":6}
2      {"android":4,"ios":4}
3      {"android":4,"ios":4}
4      {"android":4,"ios":4}
               ...
95    {"android":8,"ios":21}
96     {"android":0,"ios":0}
97    {"android":4,"ios":23}
98     {"android":0,"ios":0}
99     {"android":6,"ios":5}
Name: device_type, Length: 100, dtype: object